### PR TITLE
add toCharArray() to IPAddress class

### PR DESCRIPTION
**Pull request by martinayotte**
I was tired to grab/merge this personal change from one version to the other.

### CODE REVIEW

**Comment by igrr** [comment]
Why not add a "toString" method which would return a String? This way you could avoid the hack with a static char array.

**Comment by sdrsdr** [comment]
why not snprintf to the buffer:

 snpintf(szRet,20,"%u.%u.%u.%u",(unsigned int) _address.bytes[0],(unsigned int) _address.bytes[1],(unsigned int) _address.bytes[2],(unsigned int) _address.bytes[3]);

**Comment by Links2004** [comment]
using ```static char szRet[20];``` will restiveness 20 byte even when you never use this function.
i think the string way is the better one. you can easy make a char array out of the String.

i prefer 
```cpp
String IPAddress::toString()
{
     char szRet[16];
     sprintf(szRet,"%u.%u.%u.%u", _address.bytes[0], _address.bytes[1], _address.bytes[2], _address.bytes[3]);
    return String(szRet);
}
```

or for char*
```cpp
char * IPAddress::toString(char * buf)
{
    sprintf(buf, "%u.%u.%u.%u", _address.bytes[0], _address.bytes[1], _address.bytes[2], _address.bytes[3]);
return buf;
}

then its the same way we do it for the mac for example:
https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.cpp#L296

**Comment by martinayotte** [comment]
Ok ! I've pushed the first suggestion from Links2004.
I didn't took second suggestion, since it requires the caller to provide the storage, and that why I used static in the first version. Callers can still do toString().c_str() if "char *" is required.

**Comment by martinayotte** [comment]
The following thread is meaningful for my last commit : 
https://github.com/esp8266/Arduino/issues/596

**Pull request merged**
