### PR TITLE
Slow serial baudrates: add yields

### PR DESCRIPTION
**Pull request by HakamSaffour**
As discussed in : https://github.com/esp8266/Arduino/issues/7746

Signed-off-by: Hakam Saffour <hakam.saffour@gmail.com>

### CODE REVIEW

**Review by earlephilhower — CHANGES_REQUESTED** [review]
@HakamSaffour this PR looks like a bunch of stuff got thrown into the 1-line change you were trying to submit.  Please look at it and clear out the unneeded changes.

**Comment by d-a-v** [comment]
@HakamSaffour It seems you didn't start your pull request on top of the master branch.
You have the option to fix it, or you can start over from a fresh git version of the master branch.

**Comment by HakamSaffour** [comment]
Hello @earlephilhower and @d-a-v 
I do not have access to create a new branch, therefore I went to branch 2.7.4 and added my changes to uart.cpp

Can you explain to me, how to create a new branch? or can you do it yourself?

I am closing this PR

**Comment by d-a-v** [comment]
You need to 
```
git checkout master
git pull upstream master      # upstream is esp8266/arduino
git checkout -b mypatchname   # create your local branch
# apply your patch
git add -p                    # add your change to the branch
git commit
git push origin mypatchname     # push your changes to your repository/clone on github
```
Then on gihub you have the ability to create the PR.

**Comment by HakamSaffour** [comment]
Hello @d-a-v 

I do not have permission to push to the repo, see below

> ```
> git push origin mypatchname     # push your changes to your repository/clone on github
> ```

```
$ git push origin slowbaudrate
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Username for 'https://github.com': hakam.saffour@gmail.com
remote: Permission to esp8266/Arduino.git denied to HakamSaffour.
fatal: unable to access 'https://github.com/esp8266/Arduino.git/': The requested URL returned error: 403
```

**Pull request closed without merging**
