### PR TITLE
add Stream::readStringUntil function that uses string terminator

### PR DESCRIPTION
**Pull request by Arian8j2**
currently there is a
```c++
String readStringUntil(char terminator)
```
function, but there is no equivalent of it that uses string terminator. this pr implements
```c++
String readStringUntil(const char* terminator, uint32_t count = 1)
```
i found this useful for small html parsing or truncating.

### CODE REVIEW

**Comment by d-a-v** [comment]
It is not a breaking change and does not override the Arduino API, so looks good.
However the `count` name is not intuitive.
Is it a ` int until_total_number_of_occurrences = 1` ?

**Comment by Arian8j2** [comment]
> Is it a ` int until_total_number_of_occurrences = 1` ?

yes

**Comment by d-a-v** [comment]
Can you please add a comment or rename the variable ?

**Comment by Arian8j2** [comment]
> Can you please add a comment or rename the variable ?

done

**Review by d-a-v — APPROVED** [review]
Approving: Next step is to simplify [our calls to `readStringUntil()`](https://github.com/search?q=repo%3Aesp8266%2FArduino%20readStringUntil&type=code) from our libraries (especially but not only `parsing-impl.h`)

*edit* (or improve `Stream::sendUntil()` with this same new API) - see #9005)

**Pull request merged**
