### PR TITLE
Speed-up compilation speed in a great magnitude for free

### PR DESCRIPTION
**Pull request by andyhu**
Don't ask me why, but this PR will speed up the compilation speed for more than 70%! Try it to prove.

### CODE REVIEW

**Comment by igrr** [comment]
Did you test this change with Arduino Eclipse plugin?

**Comment by reaper7** [comment]
I do not see any difference.
Arduino 1.6.11 + latest github version of esp
with and without this changes 45sec compilation and 17sec recompilation(without changing my code)

**Comment by andyhu** [comment]
@reaper7 If you have already installed Arduino, you may need to modify "%LOCALAPPDATA%\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\platform.txt" (on windows, not tested other platforms).

**Comment by andyhu** [comment]
@igrr No I only tested on ArduinoIDE

**Comment by reaper7** [comment]
@andyhu - I modify correct platform.txt file and as I wrote ... compilation time is the same
(win10)

**Comment by krzychb** [comment]
Hi @andyhu,

How this change is supposed to alter compilation process to speed it up?
I do not see any differences in compilation or recompilation speed as well.

Checked with sketch [HelloServer.ino](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WebServer/examples/HelloServer/HelloServer.ino) compiled using with Arduino IDE 1.6.11, esp8266 / Arduino core 2.3.0, with exisitng and then new file  (...)Arduino15\packages\esp8266\hardware\esp8266\2.3.0\platform.txt (Windows 7)


Krzysztof

**Pull request closed without merging**
