### PR TITLE
Remove @PlatformIO library.json from GDBStub; fix pattern in LD

### PR DESCRIPTION
**Pull request by ivankravets**
Resolve #4355

### CODE REVIEW

**Comment by kylefleming** [comment]
@ivankravets It seems like this is actually causing GDBStub to not link weak symbols properly anymore. I'm sure the exact cases where it does and doesn't link though.

**Comment by ivankravets** [comment]
Do you use the latest PIO Core 3.5.2b4?

**Comment by kylefleming** [comment]
Yep: `PlatformIO, version 3.5.2b4`

**Comment by ivankravets** [comment]
Thanks! I reverted back `library.json` config in https://github.com/esp8266/Arduino/pull/4393

**Pull request merged**
