### PR TITLE
Update SPIFFS to 3993774 (v3.6)

### LINKED ISSUE #2450: SPIFFS read speed varies depending on location in file
#### Hardware

Hardware:           ESP-12
Core Version:       2.2
### Description

I experience good read speed over most of the file system however sometimes it is terrible.

E.g. if I have a 2MB image file, the read speed is extremely slow  in some parts of the file (37ms / byte) but ok in others (<1ms / byte).
### Settings in IDE

Module:             NodeMCU 1.0
Flash Size:         4MB/3MB SPIFFS
CPU Frequency:      160MHz
Flash Mode:         ?
Flash Frequency:    ?
Upload Using:       SERIAL
Reset Method:       Nodemcu
### Sketch

``` cpp
#include "FS.h"
#include <Arduino.h>


void setup() {
Serial.begin(115200);
SPIFFS.begin();

}

void loop() {

    File my_file = SPIFFS.open("/starwars.bmp","r");
    unsigned long start_time;
    unsigned long delta;
    unsigned long byte_count=0;
    while (my_file.available()){

       start_time=millis();
       my_file.read();

       delta = millis()-start_time;
       byte_count++;
       if (delta > 5)
          Serial.println("Byte no: " + String(byte_count) + ", read latency: " + String(delta));
    }
   my_file.close();
   Serial.println("Loop");

}

### Debug Messages
Byte no: 2173912, read latency: 38
Byte no: 2173913, read latency: 37
Byte no: 2173914, read latency: 37
Byte no: 2173915, read latency: 38
Byte no: 2173916, read latency: 37
Byte no: 2173917, read latency: 37
Byte no: 2173918, read latency: 38
Byte no: 2173919, read latency: 37
Byte no: 2173920, read latency: 37
Byte no: 2173921, read latency: 37
Byte no: 2173922, read latency: 37
Byte no: 2173923, read latency: 37
Byte no: 2173924, read latency: 37
Byte no: 2173925, read latency: 38
Byte no: 2173926, read latency: 37
Byte no: 2173927, read latency: 37
Byte no: 2173928, read latency: 37
Byte no: 2173929, read latency: 38
Byte no: 2173930, read latency: 37
Byte no: 2173931, read latency: 37
Byte no: 2173932, read latency: 38
Byte no: 2173933, read latency: 37
Byte no: 2173934, read latency: 37
Byte no: 2173935, read latency: 37
Byte no: 2173936, read latency: 37
...
...


```

messages here

```


```

### PR DESCRIPTION
**Pull request by WereCatf**
Fixes #2450 

SPIFFS v3.6 seems to work fine even with the old mkspiffs, too.

### CODE REVIEW

**Comment by WereCatf** [comment]
I updated mkspiffs at https://github.com/WereCatf/mkspiffs to the same spiffs-version, but I haven't exactly tested it thoroughly; I only tested uploading sketch data, which seems to work without an issue, the files are readable and all, but that's as far as my testing extended.

**Comment by igrr** [comment]
Out of curiosity, have you ran `tests/device/test_FS/test_FS.ino` test? I do see changes there, but at the same time you have mentioned that that you had only tested uploading sketch data.

**Comment by WereCatf** [comment]
I did and it compiled fine. Besides, doesn't travis also compile it? I don't see travis complaining about it, either.

**Comment by WereCatf** [comment]
Oh, the changes to the test_FS.ino are yours :D I just took the changes you yourself made in the earlier SPIFFS pull-request for v3.5

**Comment by igrr** [comment]
I meant flash & run it on the ESP. Travis doesn't do it because it doesn't have ESPs connected to its build servers (what a shame).

**Comment by WereCatf** [comment]
Well no, I didn't. Though I can do it, will only take a couple of minutes.

**Comment by igrr** [comment]
Ah, right, i thought they looked somehow familiar!
Awesome, thanks for adding them.

**Comment by WereCatf** [comment]
test_FS.ino runs fine, no issues.

Note: need to add a pull-request later on to add real hardware to travis. Maybe blackjack and hookers, too, for completeness's sake.

**Comment by igrr** [comment]
I've updated mkspiffs to use SPIFFS 3.7. Any takers updating this branch to v3.7 as well? :)

**Comment by me-no-dev** [comment]
Maybe I should do it since I'm onto SPIFFS anyway :D

**Comment by me-no-dev** [comment]
it's here: https://github.com/esp8266/Arduino/pull/3578

**Comment by igrr** [comment]
Updated to 3.7!

**Pull request closed without merging**
