### PR TITLE
Use hourly Arduino builds on Travis

### PR DESCRIPTION
**Pull request by igrr**
Let's see if we can build all the sketches using the latest Arduino software.

Triggered by https://github.com/arduino/arduino-builder/issues/68#issuecomment-179664401.

### CODE REVIEW

**Comment by marvinroger** [comment]
Looks like there is another issue, not only the ctag one.

**Comment by igrr** [comment]
Yeah, it looks like a name defined in another file (tab) is not recognized. This does work for simple cases though.

**Comment by marvinroger** [comment]
And I am pretty sure most people use a single ".ino" file without any headers, so this is no big deal for the average Arduino user.

**Comment by igrr** [comment]
Found that this issue is triggered by `#include <DNSServer.h>`.

**Comment by mkeyno** [comment]
hi guys
this is the first time that face many annoying problem when I update my Arduino & library , both program shows less reliability regard their prior , I've tried to solve the Arduino pre process issue with creation utility.h header in core folder location but I've had the partial score and new issue just come out such as "Sketch Data Upload" function in IDE, following is the error that come out

> Exception in thread "AWT-EventQueue-0" java.lang.IllegalAccessError: tried to access method processing.app.Sketch.prepareDataFolder()Ljava/io/File; from class com.esp8266.mkspiffs.ESP8266FS
	at com.esp8266.mkspiffs.ESP8266FS.createAndUpload(ESP8266FS.java:165)
	at com.esp8266.mkspiffs.ESP8266FS.run(ESP8266FS.java:226)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I'm kinda exhausted and maybe decide to come back to previous version and drop up all these new features

**Comment by igrr** [comment]
@mkeyno thanks for reporting that

**Comment by mkeyno** [comment]
thanks to you Iggr for your concern

**Comment by igrr** [comment]
Okay, the issue at hand is the use of `enum class` feature in DNSServer library: https://github.com/esp8266/Arduino/blob/master/libraries/DNSServer/src/DNSServer.h#L9
ctags is not aware of this new C++11 construct, which breaks parsing.

**Comment by mkeyno** [comment]
@Iggr what single header file hast to do with IDE java runtime error, this issue come with IDE, even with empty code sketch , I think this java malfunction not related with any installed library

**Comment by igrr** [comment]
@mkeyno I have attempted to reproduce the issue with arduino-esp8266fs-plugin, but was unable to do so with an hourly build downloaded just now. I'm on OS X. Please make sure you use the latest version of the plugin: https://github.com/esp8266/arduino-esp8266fs-plugin/releases/tag/0.2.0. If it still doesn't work, please open an issue at https://github.com/esp8266/arduino-esp8266fs-plugin/issues so we can get more details from you and investigate.

**Comment by mkeyno** [comment]
@igrr  yes buddy , same error,  but can you tell me where exact location should I paste this file

my portable arduino located in drive D whereas the stable library make location in C:\Users\Private\AppData\Local\Arduino15

I copy this file almost every where , because there is many folder named tools

**Comment by igrr** [comment]
@mkeyno No problem, please open the issue on arduino-esp8266fs-plugin tracker and we will take a look.

**Comment by igrr** [comment]
Waiting for https://github.com/arduino/ctags/pull/5 to be merged and Arduino ctags to be updated.

**Comment by mkeyno** [comment]
sure buddy , also can you give me or direct me to the  link which is use PROGMEM instead the SPIFF to keep the webpage , I intend to use the reliable methods for my web server until all issue related the flash memory get fixed

**Comment by igrr** [comment]
See how it is done in WiFiManager library:
https://github.com/tzapu/WiFiManager/blob/0f75d745feafdcd2f3ac26f2d3ceba02a6f1bb60/WiFiManager.h#L22-L37
https://github.com/tzapu/WiFiManager/blob/0f75d745feafdcd2f3ac26f2d3ceba02a6f1bb60/WiFiManager.cpp#L294-L306

**Comment by marvinroger** [comment]
Yet another issue with ctag?

**Comment by igrr** [comment]
@marvinroger this one is not related to ctags, i believe arduino-builder is placing the `manageRequest` declaration before the first function in the sketch, therefore it is not yet defined at the point of global declaration.

Relevant ticket: https://github.com/arduino/arduino-builder/issues/85

**Pull request merged**
