### PR TITLE
core: mask GPIO interrupts while attaching/detaching ISR handler

### PR DESCRIPTION
**Pull request by igrr**
Fixes https://github.com/esp8266/Arduino/issues/2916.

### CODE REVIEW

**Comment by igrr** [comment]
@ivankravets it looks like `pip install -U https://github.com/platformio/platformio/archive/develop.zip` fails in Travis CI, could you please take a look?

https://travis-ci.org/esp8266/Arduino/builds/274115561
https://travis-ci.org/esp8266/Arduino/builds/274563672
https://travis-ci.org/esp8266/Arduino/builds/274563832

**Comment by ivankravets** [comment]
@igrr I don't know how did it work before 😱 

Please merge this PR: https://github.com/esp8266/Arduino/pull/3599

**Comment by igrr** [comment]
@ivankravets thanks, I see the same line in arduino-esp32 travis-ci script, should it be updated there as well?

**Comment by ivankravets** [comment]
@igrr arduino-esp32 is OK because it uses [language: python](https://github.com/espressif/arduino-esp32/blob/29a253ac9823fdb8189cfd72745a28143fe3c37d/.travis.yml#L3). So, Travis.CI will create Python virtual environment automatically before a build start. In case with `language: bash`, `pip install` will install packages to system "storage" where we need `sudo` permissions.

**Comment by teprom** [comment]
Just giving my feedback on that: I have installed the last release with the above fix and now the system is not being reset anymore. Seems like this solved the problem. Thanks...

**Pull request merged**
