### PR TITLE
rewrite HardwareSerial code for UART0 + UART1 support in ESP8266

### PR DESCRIPTION
**Pull request by Links2004**
see issues #16

### CODE REVIEW

**Comment by igrr** [comment]
Great, thanks!

**Comment by hallard** [comment]
Hi guys,
Excellent, I was just looking into this for adding a 2nd UART, you done it; good. But I need a full 2nd UART. So do you think it would be possible to add the same for UART2 to have a full 2nd UART (GPIO13=RXD2 and TXD2=GPIO15) on ESP12 modules ?

**Comment by hallard** [comment]
Forget my message, just saw that UART2 (declared on nodemcu boards) is a "shared" uart with UART0 so need a kind of multiplex soft to have both working at the same time.
Sorry about this, I'm learning this new chip since only few days.

**Comment by crteensy** [comment]
Is there any example code available that demonstrates the use of Serial1? I'm using an ESP-01 module and can't seem to transmit data with it in my arduino sketch. However, during flashing, data seems to be received by the device connected to GPIO1 (Serial1 Tx).

**Comment by Links2004** [comment]
```cpp
Serial1.begin(921600); // or any other Baudrate
Serial1.println("Test123");
```

**Pull request merged**
