### PR TITLE
Remove forced OTA DNS announce

### PR DESCRIPTION
**Pull request by jonatanolofsson**
OTA should not force a DNS publication. This is not the job of the OTA server, and it interferes with previously configured DNS announcements.

### CODE REVIEW

**Comment by igrr** [comment]
I agree that we should avoid overriding previously configured mDNS. But as it is, the change will break existing sketches which did just ArduinoOTA.begin. From the perspective of the user who just wants to use OTA, but doesn't care about mDNS, ArduinoOTA should take care of mDNS registration.

How about adding a function to mDNS class to check if mDNS is configured, and then using it in ArduinoOTA? If not configured, then ArduinoOTA must call mDNS.begin, otherwise OTA will not work (Arduino IDE will not see the device on the network).

Also suggest keeping 'setHostname'/'getHostname' function for compatibility with existing sketches.

**Comment by jonatanolofsson** [comment]
I rewrote the commit per your suggestion and added a check if the mDNS had already been started

**Comment by jonatanolofsson** [comment]
@igrr I just rebased this. Should I do something more before it is merged?

**Comment by igrr** [comment]
Thanks, the changes look good. This will be merged once 2.4.1 is released, which should happen very soon.

**Comment by CZEMacLeod** [comment]
Would be better if we could have OTA enabled without mDNS at all.
Perhaps an optional `#define ArduinoOTA_No_mDNS` and some `#ifndef ArduinoOTA_No_mDNS`'s around the include and calls?
I have problems with mDNS crashing and causing other problems if it is started at all, so would prefer (for now at least) to leave it out altogether.
But this helps and is backwards compatible which is always good.

**Comment by jonatanolofsson** [comment]
@igrr I just rebased this. Should I do something more before it is merged?

**Comment by d-a-v** [comment]
duplicate #5494 which is already merged

**Pull request closed without merging**
