### PR TITLE
Add SPIFFS wrapper for info function

### PR DESCRIPTION
**Pull request by luc-github**
this allow to display total space and used space on SPIFFS

### CODE REVIEW

**Comment by luc-github** [comment]
Thank you :smile:

**Comment by luc-github** [comment]
Do you need me to do the modifications you requested about using  structure similar to [statvfs](http://linux.die.net/man/2/statvfs) structure ?

**Comment by igrr** [comment]
I'll do that myself, no problem, just got a bit busy yesterday shuffling files around.

**Comment by luc-github** [comment]
no problem - you do a great work - thank you for all you did / do / will do :smile:

**Pull request merged**
