### PR TITLE
Point to proper uploaded python repackage w/subdir

### PR DESCRIPTION
**Pull request by earlephilhower**
Fixes problem of python files expanding in tools/ dir and not
in tools/python.

### CODE REVIEW

**Comment by earlephilhower** [comment]
@d-a-v, let's get some feedback and see if I missed something else before merging...

**Comment by earlephilhower** [comment]
I've got a better way to refactor this completely.

`upload.py` can just import esptool and pyserial directly and use esptool.main() to do the work, without messing around with threads or forks and winding up much simpler.

Gonna be a day or so before I can test and commit a patch, but it's on the way.

**Comment by earlephilhower** [comment]
Just did a compile and upload with full flash erase under Windows with the latest push, LGTM now.  @reaper7 , et. al., please give this a try (be sure to run "git submodule init" and "git submodule update" at least once to make sure you have the esptool and pyserial submodule sources in your tree).

**Comment by reaper7** [comment]
@earlephilhower - looks OK!

```
Linking everything together...
"C:\\PROGRAMY\\Arduino\\hardware\\esp8266com\\esp8266/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc" -CC -E -P -DVTABLES_IN_FLASH "C:\\PROGRAMY\\Arduino\\hardware\\esp8266com\\esp8266/tools/sdk/ld/eagle.app.v6.common.ld.h" -o "C:\\tmp\\arduino_build_246277/local.eagle.app.v6.common.ld"
"C:\\PROGRAMY\\Arduino\\hardware\\esp8266com\\esp8266/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc" -fno-exceptions -Wl,-Map "-Wl,C:\\tmp\\arduino_build_246277/Blink.ino.map" -g -Wall -Wextra -Os -nostdlib -Wl,--no-check-sections -u app_entry -u _printf_float -u _scanf_float -Wl,-static "-LC:\\PROGRAMY\\Arduino\\hardware\\esp8266com\\esp8266/tools/sdk/lib" "-LC:\\PROGRAMY\\Arduino\\hardware\\esp8266com\\esp8266/tools/sdk/lib/NONOSDK221" "-LC:\\PROGRAMY\\Arduino\\hardware\\esp8266com\\esp8266/tools/sdk/ld" "-LC:\\PROGRAMY\\Arduino\\hardware\\esp8266com\\esp8266/tools/sdk/libc/xtensa-lx106-elf/lib" -Teagle.flash.4m.ld -Wl,--gc-sections -Wl,-wrap,system_restart_local -Wl,-wrap,spi_flash_read -o "C:\\tmp\\arduino_build_246277/Blink.ino.elf" -Wl,--start-group "C:\\tmp\\arduino_build_246277\\sketch\\Blink.ino.cpp.o" "C:\\tmp\\arduino_build_246277\\core\\core.a" -lhal -lphy -lpp -lnet80211 -llwip2-536-feat -lwpa -lcrypto -lmain -lwps -lbearssl -laxtls -lespnow -lsmartconfig -lairkiss -lwpa2 -lstdc++ -lm -lc -lgcc -Wl,--end-group "-LC:\\tmp\\arduino_build_246277"
"C:\\PROGRAMY\\Arduino\\hardware\\esp8266com\\esp8266/tools/python/python.exe" "C:\\PROGRAMY\\Arduino\\hardware\\esp8266com\\esp8266/tools/elf2bin.py" --eboot "C:\\PROGRAMY\\Arduino\\hardware\\esp8266com\\esp8266/bootloaders/eboot/eboot.elf" --app "C:\\tmp\\arduino_build_246277/Blink.ino.elf" --flash_mode dio --flash_freq 40 --flash_size 4M --path "C:\\PROGRAMY\\Arduino\\hardware\\esp8266com\\esp8266/tools/xtensa-lx106-elf/bin" --out "C:\\tmp\\arduino_build_246277/Blink.ino.bin"
Creating BIN file "C:\tmp\arduino_build_246277/Blink.ino.bin" using "C:\tmp\arduino_build_246277/Blink.ino.elf"

"C:\\PROGRAMY\\Arduino\\hardware\\esp8266com\\esp8266/tools/python/python.exe" "C:\\PROGRAMY\\Arduino\\hardware\\esp8266com\\esp8266/tools/signing.py" --mode sign --privatekey "C:\\PROGRAMY\\Arduino\\examples\\01.Basics\\Blink/private.key" --bin "C:\\tmp\\arduino_build_246277/Blink.ino.bin" --out "C:\\tmp\\arduino_build_246277/Blink.ino.bin.signed"
"C:\\PROGRAMY\\Arduino\\hardware\\esp8266com\\esp8266/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-size" -A "C:\\tmp\\arduino_build_246277/Blink.ino.elf"
Szkic używa 257256 bajtów (24%) pamięci programu. Maksimum to 1044464 bajtów.
Zmienne globalne używają 26556 bajtów (32%) pamięci dynamicznej, pozostawiając 55364 bajtów dla zmiennych lokalnych. Maksimum to 81920 bajtów.
esptool.py v2.6
2.6
esptool.py v2.6
Serial port COM14
Connecting....
Chip is ESP8266EX
Features: WiFi
MAC: 5c:cf:7f:11:5c:bd
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 261408 bytes to 190957...

Writing at 0x00000000... (8 %)
Writing at 0x00004000... (16 %)
Writing at 0x00008000... (25 %)
Writing at 0x0000c000... (33 %)
Writing at 0x00010000... (41 %)
Writing at 0x00014000... (50 %)
Writing at 0x00018000... (58 %)
Writing at 0x0001c000... (66 %)
Writing at 0x00020000... (75 %)
Writing at 0x00024000... (83 %)
Writing at 0x00028000... (91 %)
Writing at 0x0002c000... (100 %)
Wrote 261408 bytes (190957 compressed) at 0x00000000 in 4.5 seconds (effective 468.3 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

**Pull request merged**
