### PR TITLE
Add 20/26MHz Flash frequencies for slow/cheap flash chips on the Generic ESP Board

### PR DESCRIPTION
**Pull request by ChocolateFrogsNuts**
A number of non-genuine boards exist mainly from flea-bay sellers that
use under-sized and/or low quality flash chips which can not handle
a 40MHz FlashFreq properly.

This patch adds slower flash frequencies to the menu for generic ESP boards
so that these cheap knock-offs can be run in a stable manner, hopefully saving
some people a few headaches and keeping these boards out of landfill.

see #6366 final solution.

### CODE REVIEW

**Comment by Jason2866** [comment]
Imho bad cheap flash chips will not become reliable with tricks.
The should simply avoided. Strange errors will occur and Arduino core will be blamed
So the bin is the best place for this crap

**Comment by devyte** [comment]
@Jason2866 there's a reason that the generic board options allow selection of the flash frequency.

**Comment by ChocolateFrogsNuts** [comment]
@Jason2866 agreed that if the chip is in fact bad, it won't become good and it belongs in the bin.

Where this is useful is when the chip is storing the data correctly and reliably, but during the read cycle is not getting the data stable on the output fast enough for a 40mhz clock, resulting in intermittent bad reads.
The lower clock does in fact work in these cases - which I have seen with XM branded flash chips.
It is the difference between "why does this board crash randomly" and "this board is rock solid".

**Comment by Jason2866** [comment]
@d-a-v  I replace flash chips (Puya...). But most user wont do ;-)

**Pull request merged**
