### PR TITLE
Added GZipped OTA support in elf2bin and PlatformIO

### PR DESCRIPTION
**Pull request by drzony**

### CODE REVIEW

**Comment by d-a-v** [comment]
Thanks @drzony ! That looks fine.
Basically from what I understand, the regular firmware file is replaced by the compressed one, and the original one renamed to `.orig`.
Is that because PIO can't handle another name than `sketch.bin` ?

**Comment by drzony** [comment]
No, that's because `elf2bin.py` takes `--out` parameter, so the gzipped file needs to be named according to this parameter. The `.orig` file is just a backup for reference

**Review by earlephilhower — APPROVED** [review]
LGTM.  Only PIO and custom scripts will use this action, so I don't see any core impact.

**Review by d-a-v — APPROVED** [review]
Thanks !

**Pull request merged**
