### PR TITLE
platform.txt: Override python3 anon pipe encoding to utf-8 for 'tools/sizes.py'

### PR DESCRIPTION
**Pull request by jjsuwa-sys3175**
see https://github.com/esp8266/Arduino/commit/da4a19fdacd7a859da395e014c9e0fded99aa985#commitcomment-73793209

### CODE REVIEW

**Review by d-a-v — APPROVED** [review]
no change w/linux

**Comment by jjsuwa-sys3175** [comment]
> no change w/linux

thx

a little concern: `-X utf8` requires python 3.7 or later

**Comment by mcspr** [comment]
Thanks. Also a good reminder to double-check any python scripts to force text encoding :)
BTW, what happens with legacy cmd.exe when invoking the script manually?

**Comment by jjsuwa-sys3175** [comment]
> BTW, what happens with legacy cmd.exe when invoking the script manually?

scrnshot

**Pull request merged**
