### PR TITLE
The properly built lwip2 binaries for #7121

### LINKED ISSUE #7127: Regression in master merged with PR #7022: WDT resets
Details in #7022 and #7121.
PR #7022 works without lock-ups or reboots up to and including master commit 2c435b1f427dfdc1567bd52ca6d966d5640d6bb9. So commit c61b70de865531f62218541fa0f32715c153a449 introduces some change that breaks the timing and causes continual WDT resets (1 per minute or so) in the MVCE I've supplied in #7121.
Without PR #7022, I have not been able to reproduce this malfunction, but that shouldn't make it any less significant.

### PR DESCRIPTION
**Pull request by dok-net**
From clean git checkout, "make install".
Fixes #7127

### CODE REVIEW

**Comment by d-a-v** [comment]
`tcp_priv.h` is correct but willingly not merged like you propose to avoid gcc warns. To solve it cleanly, a lwIP patch would be needed but has not been done yet.

I don't understand the rest of this PR, please elaborate what is wrong with current master.

**Comment by dok-net** [comment]
tcp_priv.h reverted, thanks for clarifying.

**Comment by dok-net** [comment]
These binaries are the result of `make install`, as per your and the README details, for lwIP2 in ESP8266 git master fresh clone. It can only guess that the binaries you merges the other day are broken.

As these are binaries, produced from a make process that's mostly opaque, I cannot comment further, except that in my tests, that fail on ESP8266 git master, this PR fixes the WDT resets completely.

**Comment by d-a-v** [comment]
OK. Because the make process is not opaque at all from this side of internet, 
I will produce these binaries myself (or if another maintainer propose to do it) as I always did, from a computer and a clean repository, different than the one used to produce the binaries that you find offending so you can test them.

**Comment by dok-net** [comment]
Great, could you elaborate for the sake of quick research how to match what is landed in ESP8266 Arduino to the sources used, i.e. GNU lwIP? The Makefiles do traverse up and down and do a cascade of includes, on both sides of the internet, I assume :-)
As of writing this, I haven't had a WDT reboot in hours, now, using the "contributor" binaries instead of the "collaborator" ones.

**Comment by d-a-v** [comment]
@dok-net will this file work for you ?
https://github.com/d-a-v/Arduino/raw/90347e719d6c5082ad88d20e617cb79f3aabef1d/tools/sdk/lib/liblwip2-536-feat.a

**Comment by dok-net** [comment]
This clean-built binary doesn't WDT reset every so often, please commit them all, or mine to your liking.
With regard to the source revision, you wouldn't give me the answer, so it appears to be as follows:
lwip2-src is cloned from `https://git.savannah.nongnu.org/git/lwip.git`, checkout is done for the tag given in `lwip2/builder/makefiles/Makefile.defs`, currently `UPSTREAM_VERSION = STABLE-2_1_2_RELEASE`.
Also, the contents of `tools/sdk/lwip2/include/lwip-git-hash.h`,
```
// generated by makefiles/make-lwip2-hash
#ifndef LWIP_HASH_H
#define LWIP_HASH_H
#define LWIP_HASH_STR "STABLE-2_1_2_RELEASE/glue:1.2-30-g92add50"
#endif // LWIP_HASH_H
```
detail the revisions of the lwip repository, obviously, and the `builder` submodule, a.k.a. `lwip2`, a.k.a. `https://github.com/d-a-v/esp82xx-nonos-linklayer.git`, a.k.a. `glue` , in `git describe --tag` syntax.

**Comment by dok-net** [comment]
@d-a-v closed this in anticipation of your fix commit for the lwip binaries.
PR #7128 is (loosely) related to this, in any case, the nullptr checks I've added fix the broken OTA for me (issue #7124) and should be best practice anyway.

**Pull request closed without merging**
