### PR TITLE
Clean up use of "byte" as a type. uint8_t or (C++17) std::byte are better

### LINKED ISSUE #8089: weird error in arduino.h on makeWord () with core 3.0.0
hi,
i have a weird error in arduino.h on makeWord ().
I use word (h, l) in my code and with core 3.0.0 it gives a fatal error during compilation.

```
In file included from C:\Users\stephane\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266WiFi\src/WiFiClient.h:25,
                 from C:\Users\stephane\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:39,

C:\Users\stephane\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/Arduino.h:247:19: error: 'uint16_t makeWord' redeclared as different kind of entity
  247 | uint16_t makeWord(byte h, byte l);
      |                   ^~~~
C:\Users\stephane\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/Arduino.h:246:10: note: previous declaration 'uint16_t makeWord(uint16_t)'
  246 | uint16_t makeWord(uint16_t w);
      |          ^~~~~~~~
C:\Users\stephane\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/Arduino.h:247:19: error: reference to 'byte' is ambiguous
  247 | uint16_t makeWord(byte h, byte l);
      |                   ^~~~
```

i got around the problem by changing in arduino.h
```
uint16_t makeWord (byte h, byte l); -> uint16_t makeWord (uint8_t h, uint8_t l);
```
What do you think ?

### PR DESCRIPTION
**Pull request by dok-net**
Related to #8089

### CODE REVIEW

**Review by earlephilhower — CHANGES_REQUESTED** [review]
Not a fan of the way Arduino did it, but this breaks Arduino compatibility.

https://github.com/arduino/ArduinoCore-API/blob/173e8eadced2ad32eeb93bcbd5c49f8d6a055ea6/api/Common.h#L151-L153

````
uint16_t makeWord(uint16_t w);
uint16_t makeWord(byte h, byte l);
````

Removing byte elsewhere seems fine, but the 2-param makeword seems like it should be moved from `unsigned char` to `byte` in `WMath.cpp`.

**Comment by dok-net** [comment]
In the light of even, say:
```
#define lowByte(w) ((uint8_t) ((w) & 0xff))
#define highByte(w) ((uint8_t) ((w) >>; 8))
```
using `uint8_t`, I find it all rather inconsistent to begin with. Also, while C++ (at least when I read the specs a long time ago, LOL) was based on type-name, not type-structure, if you like to convince me please explain the difference that it makes, when all the while
```
typedef uint8_t byte;
```
lets the compiler cast and then link just fine. My reckoning in this is to get rid of "byte" as much as possible - rationale (byte is used as object ident) was given above.
As a compromise, we could leave `Arduino.h` as it is ...

By the way, I messed up, doing the ESP32 in kind of at the same time, and didn't fix the return type inconsistency here in ESP8266 Core. I have done that now (fixup and rebase).

There are other indications that this discussion is moot, like:
```
-typedef unsigned int word;
+typedef uint16_t word;
```
and the AVR `Arduino.h` and ESP8266 `Arduino.h` are not really very much alike anymore overall. So keep things straight and simple, let's adapt in `Arduino.h` to `uint8_t`, too, please.

**Comment by dok-net** [comment]
Regarding Arduino compatibility: https://github.com/arduino/ArduinoCore-API
Loads of unrewarding differences to merge, figure out, repair, refactor.

**Review by earlephilhower — APPROVED** [review]
LGTM

**Review by d-a-v — APPROVED** [review]

**Pull request merged**
