### PR TITLE
rework WiFi

### PR DESCRIPTION
**Pull request by Links2004**
rework WiFi class
- move docu to cpp and make it doxygen compatible
- rework mode management
- reduce memory footprint (less static variables inside functions)
- split code in several files for better overview (API access not changed)
- improve error handling and return values
- many small changes
- new functions
 - Generic 
   - hook WiFi events
    - force Sleep Mode 
    - set Output Power
 - STA
   - reconnect 
    - setAutoConnect
    - getAutoConnect
    - setAutoReconnect
    - isConnected
 - AP
   - softAPgetStationNum

### CODE REVIEW

**Comment by Links2004** [comment]
@sticilface see: https://github.com/Links2004/Arduino/commit/640d0bb65e2e891162f4fed617324d4ede59913e

**Comment by sticilface** [comment]
Whoops, good work!  sorry still working my way through a lot of changes:)

**Comment by asetyde** [comment]
:+1:

**Comment by Links2004** [comment]
@sticilface the IP is not stored by the SDK or the WiFi class.
currently: if needed the user need to store the info itself.
if we want to change this we need a new memory segment for storing core internal infos.
for the moment I dont want to create a segment like this.

**Comment by sticilface** [comment]
Agree.  :)

**Comment by Links2004** [comment]
rework done for now.
will keep the pull request open until tomorrow evening.
some review / testings are welcome its a big change ;)

**Comment by Links2004** [comment]
doxygen:
http://links2004.github.io/Arduino/d8/ded/class_e_s_p8266_wi_fi_class.html

**Comment by drmpf** [comment]
Any chance of adding support for client.isSendWaiting() to these changes
see the bottom of Request Event Driven (non-blocking) WiFi API https://github.com/esp8266/Arduino/issues/922  for the small number of changes needed to support this.

**Comment by Links2004** [comment]
i currently not rework the TCP / UDP stuff.
only the WiFi handling itself.

will take a look later.

**Comment by tzapu** [comment]
test results for the auto connect modifications
```
WiFi.setAutoConnect(false); & WiFi.begin("SSID", "password", 0, NULL, false);
does not connect
WiFi.setAutoConnect(false); & WiFi.begin("SSID", "password", 0, NULL, true);
does not connect 
WiFi.setAutoConnect(true); & WiFi.begin("SSID", "password", 0, NULL, false);
connects 
WiFi.setAutoConnect(true); & WiFi.begin("SSID", "password", 0, NULL, true);
connects
just WiFi.setAutoConnect(false); 
does not connect
just WiFi.setAutoConnect(true); 
connects
```
test code
```
  WiFi.mode(WIFI_STA);
  WiFi.setAutoConnect(true);
  WiFi.begin("SSID", "password", 0, NULL, false);
  int connRes = WiFi.waitForConnectResult();
```

It all seems OK, thank you very much. Maybe a bit confusing when setting connect to false and it still connects.

**Comment by Links2004** [comment]
@tzapu is the ESP may already connected when you call begin?
the SDK connects to the latest config, without any code in setup or loop.
can you test it with a WiFi.disconnect(true); delay(1000); before your test code?

**Pull request merged**
