### PR TITLE
support new board (invent one)

### PR DESCRIPTION
**Pull request by inventvictor**
Please Add support for the Invent One

Information of the product can be found here : htps://inventone.ng.
More information on the board can be found here : https://blog.inventone.ng

Thank you!

### CODE REVIEW

**Comment by d-a-v** [comment]
Please remove `.orig` files from this PR :)

**Comment by inventvictor** [comment]
> Please remove `.orig` files from this PR :)

Done. Thanks

**Comment by inventvictor** [comment]
Please else needs to be done to get this merged?

**Comment by inventvictor** [comment]
Please help merge this branch.

Thanks

**Comment by inventvictor** [comment]
Thank you D-a-v

I didn't see Invent One when I downloaded the esp8266 package for the Arduino Software.

I expected it to be there already. 
Am I wrong?

**Comment by d-a-v** [comment]
It will appear on next release, probably in december.
In the mean time, you'll have it with git.
Just update master.

**Comment by inventvictor** [comment]
Thank you D-a-v

**Comment by smartynov** [comment]
@inventvictor it seems that Invent One project is down (website and social network accounts abandoned, no boards can be seen). Do you still need this board to be presented in IDE?

@d-a-v it's probably a good idea to clean up the board list from time to time.

**Comment by d-a-v** [comment]
@inventvictor You board is defined with the "nodemcu" reset method,
so it needs the "nodemcu" reset circuit with two transistors.

**Comment by inventvictor** [comment]
Thanks for the information @d-a-v 

What should we have used as the reset method?
What could we have done better?

Looking forward to your response
Thanks in advance

**Comment by d-a-v** [comment]
You can check nodemcu initial documentation with schematics, also wemos boards reset circuit borrowed, I believe, from nodemcu.
https://arduino-esp8266.readthedocs.io/en/latest/boards.html#nodemcu-1-0-esp-12e-module
https://wiki.wemos.cc/_media/products:d1:sch_d1_mini_v3.0.0.pdf

**Pull request merged**
