### PR TITLE
Add url redirect

### PR DESCRIPTION
**Pull request by hmueller01**
Add redirect function like [ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer).
Sorry for the wrong commits/reverts. Obviously my master wasn't clean.

### CODE REVIEW

**Comment by hmueller01** [comment]
Is it possible to merge this, also there is a build problem on Linux? Seems to be not the fault of this PR ...

**Comment by d-a-v** [comment]
What about using this API [in our examples](https://github.com/search?q=repo%3Aesp8266%2FArduino%20send\(302&type=code) ?

**Comment by hmueller01** [comment]
@d-a-v Sorry, but I do not understand your comment. These are examples that do a redirect. My proposal was to add this out-of-the-box of the ESP8266WebServer ...

**Comment by d-a-v** [comment]
Sorry for lack of clarity.
You added  a new API.
I propose you to update our examples to use it.
They would become examples of how to use your new API, examples are meant for that.
Lots of users take them as basis to start their project.
My link above shows you where you *could* make these changes.

**Comment by hmueller01** [comment]
Oh, sry for being so stupid. Sure, I'll do this in the next few days.

**Comment by hmueller01** [comment]
Looking through the examples I found this:
```
  server.send(302, "text/plain", "");  // Empty content inhibits Content-length header so we have to close the socket ourselves.
  server.client().stop();  // Stop is needed because we sent no content length
```
Why is it needed to stop the client? Should this be done in `redirect()` as well, if I do not send content?

**Comment by d-a-v** [comment]
> Why is it needed to stop the client? Should this be done in `redirect()` as well, if I do not send content?

It seems to be a good idea.

**Comment by hmueller01** [comment]
@d-a-v Ok, I finished my work on this. Also did some tests and it looks good.

**Comment by hmueller01** [comment]
Fixed. All checks have passed. 👍

**Comment by hmueller01** [comment]
I just merged with master and it still looks clean.
@d-a-v Is this ready form merging now (and adding to a new release you just mentioned)?

**Comment by mcspr** [comment]
(sry for delay)

I don't think you have to rename params this much.
Request object is the one we care about the most, either 'friend'ing the Server class or simply using different signature to access the vector would probably be a shorter solution?
New Server method can keep its name

**Review by d-a-v — APPROVED** [review]

**Pull request merged**
