### PR TITLE
Add new boards Phoenix 1.0 & Phoenix 2.0

### PR DESCRIPTION
**Pull request by NAzT**

### CODE REVIEW

**Comment by igrr** [comment]
New boards should also be added to doc/boards.md and package/package_esp8266com_index.template.json

**Comment by NAzT** [comment]
@igrr Oh sorry for my fault, I've fixed that

thank you 👍

**Comment by igrr** [comment]
Another thing, boards.txt refers to two new variants, but I don't see them added.
`phoenix_v2.build.variant=phoenix_v2`
`phoenix_v1.build.variant=phoenix_v1`
So there should be phoenix_v1 and phoenix_v2 subfolders in under variants/ with pins_arduino.h in them.

**Comment by NAzT** [comment]
@igrr fixed now! sorry so much.

**Pull request merged**
