### PR TITLE
fix parseArgument

### PR DESCRIPTION
**Pull request by d-a-v**
```
url: 'foo'
args=1
arg(0): 'foo' = ''

url: 'foo='
args=1
arg(0): 'foo' = ''

url: 'foo=bar'
args=1
arg(0): 'foo' = 'bar'

url: 'foo&bar&lol=&ness=&key=val;another=way;to;separate'
args=8
arg(0): 'foo' = ''
arg(1): 'bar' = ''
arg(2): 'lol' = ''
arg(3): 'ness' = ''
arg(4): 'key' = 'val'
arg(5): 'another' = 'way'
arg(6): 'to' = ''
arg(7): 'separate' = ''

url: 'foo&bar&lol=&ness=&key=val;another=way;to;separate='
args=8
arg(0): 'foo' = ''
arg(1): 'bar' = ''
arg(2): 'lol' = ''
arg(3): 'ness' = ''
arg(4): 'key' = 'val'
arg(5): 'another' = 'way'
arg(6): 'to' = ''
arg(7): 'separate' = ''

url: 'foo&bar&lol=&ness=&key=val;another=way;to;separate=sobeit'
args=8
arg(0): 'foo' = ''
arg(1): 'bar' = ''
arg(2): 'lol' = ''
arg(3): 'ness' = ''
arg(4): 'key' = 'val'
arg(5): 'another' = 'way'
arg(6): 'to' = ''
arg(7): 'separate' = 'sobeit'

url: 'foo&;bar&;lol=&;ness=&;&key=val;&another=way;&to;&separate=sobeit'
args=8
arg(0): 'foo' = ''
arg(1): 'bar' = ''
arg(2): 'lol' = ''
arg(3): 'ness' = ''
arg(4): 'key' = 'val'
arg(5): 'another' = 'way'
arg(6): 'to' = ''
arg(7): 'separate' = 'sobeit'

url: 'foo&;bar&;lol=&;ness=&;&key=val;&another=way;&to;&separate=sobeit&&&;;;'
args=8
arg(0): 'foo' = ''
arg(1): 'bar' = ''
arg(2): 'lol' = ''
arg(3): 'ness' = ''
arg(4): 'key' = 'val'
arg(5): 'another' = 'way'
arg(6): 'to' = ''
arg(7): 'separate' = 'sobeit'

url: ';;;;'
args=0

url: ';;a;;'
args=1
arg(0): 'a' = ''
```
*edit* 
~```url: ''```~
~```args=1```~
~```arg(0): '' = ''```~

it is really:

```
...

url: ';;;;'
args=0

url: ';;a;;'
args=1
arg(0): 'a' = ''

url: ''
args=0
```
(bad copy paste)

### CODE REVIEW

**Comment by devyte** [comment]
@d-a-v recursive calls are hard to understand at a glance, and they're dangerous on a stack-constrained platform like ours.
Instead, I suggest migrating to std::vector. To reduce fragmentation and overallocation, you could do a two pass approach: go over the buffer counting & and ; , then reserve(), then go over the buffer again parsing.

**Comment by earlephilhower** [comment]
Looks great from the tests, with one minor niggle.

The last check:
````
url: ''
args=1
arg(0): '' = ''
````
(I'm assuming "url" should be "string after 1st "?")

For, say `http://test.me/doit.cgi?` (the last test), shouldn't args==0?

**Comment by d-a-v** [comment]
@earlephilhower True. I made copy paste of some previous result. fixed in OP.

@devyte Recursion is only one level: the number of inner call is really 1 and does not depend on the request itself. For clarity I removed this call. Still not using `vector<>` because I realized that implication with the rest of the code is unknown (for example, allocation must be increased by one - see comments).

**Comment by d-a-v** [comment]
@ascillato @andrethomas I assume you have made tests with alexa ?
Were you able to talk to your ESPs like with the other PR ?

**Comment by ascillato** [comment]
@d-a-v 

With this PR Alexa bug stills there. Sorry. With the PR I proposed, Alexa was working.

I'm checking your code and it should work but I don't know why it doesn't. It needs something extra for the parameters?

Testing using Sonoff-Tasmota.

**Comment by ascillato** [comment]
@d-a-v 

* Testing https://github.com/esp8266/Arduino/pull/4236 with actual STAGE version works with Alexa.

* Testing https://github.com/esp8266/Arduino/pull/5222 with actual STAGE version works with Alexa.

So, as any of the 2 options solves the Alexa Bug, can be added to your PR any of those approaches ?

**Comment by d-a-v** [comment]
@ascillato Thanks for your two tests and your links in #5222.
Here I'm a fixer and I can't fix without understanding.
Without having invited alexa at home, but with reading detailed @OFreddy's [findings](https://github.com/arendst/Sonoff-Tasmota/issues/1639#issuecomment-359253011), I'll go for his solution.

**Comment by ascillato** [comment]
@d-a-v 

Hi
we, made several tests, and using the core from  https://github.com/d-a-v/arduino/tree/parserequest we could not make it work with Alexa
I don't know why in the parsing code it is being ignored the alexa request.

If I just change in the last actual core only the line 198 from _parsing.cpp_ to
`if(!isEncoded||(0==_currentArgCount)){`
Alexa works
I don't know what is happening with the rest of the parsing you have added that this line stop working.

**Comment by reloxx13** [comment]
latest switch hue on with alexa log

```
01:32:12 WIF: verbunden
method: PUT url: /api/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1/state search:
headerName: Host
headerValue: 192.168.178.73
headerName: Accept
headerValue: /
headerName: Content-type
headerValue: application/x-www-form-urlencoded
headerName: Content-Length

headerValue: 13
args: {"on": false}
args count: 1
args: {"on": false}
arg 0 key: {"on": false} value:
args count: 1
Plain: {"on": false}
Request: /api/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1/state
 Arguments: {"on": false}
01:32:16 HTP: Hue-API (/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1/state)
01:32:16 HTP: Hue POST-Argumente ()
01:32:16 HTP: Hue POST-Argumente ({"on": false})
01:32:20 CMD:
```

**Comment by reloxx13** [comment]
now alexa is not working cuz the json is detected as an arg and again its not going inside the if i mentioned before.

**Comment by d-a-v** [comment]
@devyte I'll open an issue for your proposal. This PR was itself a pain to fix (no alexa around, me not used to http request world, difficulties to test, lots of cases and no emulated environment (yet :) to speed tests up). It should be part of a general cleaning pass.

@ alexa users, please tell me this is working (= I was working with good fake requests with AdvancedWebserver example).

special thanks to @reloxx13 who made a PR (merged) in my branch to fix a nasty parsing bugs I was not seeing in my original commit (the bug was in my testing process, mainly, so we need that emulated enviroment fully working #1715).

**Comment by reloxx13** [comment]
just tested and works for me with alexa and web saves/posts

log:
```
New client
method: PUT url: /api/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1/state search:
headerName: Host
headerValue: 192.168.178.73
headerName: Accept
headerValue: */*
headerName: Content-type
headerValue: application/x-www-form-urlencoded
headerName: Content-Length
headerValue: 12
args:
args count: 0
args:
args count: 0

Request: /api/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1/state
Arguments:
final list of key/value pairs:
  key:'plain' value:'{"on": true}'
request handler not found
18:55:40 HTP: Hue-API (/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1/state)
18:55:40 HTP: Hue POST-Argumente ({"on": true})
18:55:40 SRC: Hue
18:55:40 RSL: RESULT = {"POWER":"ON"}
18:55:40 RSL: POWER = ON
```

**Comment by ascillato** [comment]
Hi,

@d-a-v @devyte @earlephilhower 

As now this PR solves the Bug for Parsing Alexa requests, please, merge this PR. Thanks.

**Comment by ascillato** [comment]
Hi,

I found that there is a memory leak using this PR.

If I use the Core at the commit https://github.com/esp8266/Arduino/commit/1b1b0a28a825cca187d4dcea79fe2cb8a7411059 the core works fine. No issues.

If I add this PR to that commit, In few minutes all RAM goes to zero and the device reboots.

(I use the commit https://github.com/esp8266/Arduino/commit/1b1b0a28a825cca187d4dcea79fe2cb8a7411059 because the next one https://github.com/esp8266/Arduino/commit/c8497da6766543c0e0c1dc130ab54c3d722ea017 also has memory leak)

**Comment by ascillato** [comment]
@d-a-v 

Very Nice work! Bug solved. All working. :+1: 

Please, merge this PR.

**Comment by Jason2866** [comment]
@d-a-v Great Job :-)  !!
Memory Leak is gone. No reboot. MQTT is stable tested with PUBSUBCLIENT and ARDUINOMQTT
IwIP 2hb and IwIP 1.4 tested. Both work good. WebFrontend works without errors. OTA Error solved.
AND finally ALEXA works reliable.  ALL bugs that i had are gone!!
Devices with Sonoff-Tasmota are fast and responsive :-)

Please do a Merge very very soon to Master to have a reference commit of a very well done stable Version.

T H X for your great work

**Comment by andrethomas** [comment]
Great work @d-a-v 

I get the same result as @Jason2866 

Everything seems to be working as it should.

Can we please get this PR merged so that we can continue to use this as a staged core for Tasmota development binaries.

Much appreciated, THX!

**Comment by devyte** [comment]
Closing in favor of #5252 .

**Pull request closed without merging**
