### PR TITLE
added support for WEMOS D1 mini LITE

### PR DESCRIPTION
**Pull request by dropmeaword**

### CODE REVIEW

**Comment by Lenbok** [comment]
Is this a duplicate of #3169 ? Perhaps review that PR?

**Comment by capedra** [comment]
@zyphos @igrr 

The updated code is wrong. The only way to make the Wemos D1 Mini Lite 1.0.0 is to set the **flash_mode** accordingly:
```
d1_mini_lite.build.flash_mode=dout
```
Attention: if you don't change the above line, the board will **NEVER** work.

**Comment by d-a-v** [comment]
d1 mini lite is now in master's board.txt (dout).

**Comment by d-a-v** [comment]
@capedra thanks for this useful information (to me, at that time). d1 mini lite is there. Closing.

**Pull request closed without merging**
