### PR TITLE
Add Digest Authentication to the Webserver

### PR DESCRIPTION
**Pull request by Lan-Hekary**
I implemented the Digest Authentication Method as Described in [RFC 2617](https://tools.ietf.org/html/rfc2617)
I'd like to hear your opinions and suggestions to optimize the code ..
also hoping that it will be accepted in the master library ..

### CODE REVIEW

**Comment by igrr** [comment]
Thanks for the PR, it looks very good in general. Could you please update it to keep indentation consistent with the surrounding code (spaces instead of tabs)?
Also please add an example sketch (or modify one of the existing ones) to demonstrate new functionality. Thanks.

**Comment by Lan-Hekary** [comment]
I will fix the indentation and upload it when I get home :D
concerning the example sketch I made the Default Authentication method the Digest Method , So Changing is required for the existing code .. 
if the user wishes to use the Basic Auth method He will Have to call the function with an arugment AUTH_BASIC

I'd like to edit the documentation concerning this use but I can't find it .. 
can you help me , point me how to do it and where ??
also I need to know how can I keep my Fork Up to date with the Master , I kinda Bodged through this Commit from online tutorial :(

**Comment by davisonja** [comment]
It should really default to match existing behaviour or everyone's existing
code will break!

**Comment by Lan-Hekary** [comment]
This Modification Does not interfere with the Code that user write 
it only affects how the Browser Handle the Auth method 
I will revert it to Use BASIC by Default , that's not a Problem :D
any other suggestions or help ?? @davisonja

**Comment by Lan-Hekary** [comment]
@igrr @davisonja 
this is the final Version space indentation and an example sketch,
also no changes required for the exciting code usage by the user as it Defaults to use BasicAuth unless otherwise specified 
added a parameters to change the Auth Realm and the Authentication Failure HTML content

**Comment by Lan-Hekary** [comment]
any news ?? this Commit is over 10 days ago :D

**Comment by Lan-Hekary** [comment]
@igrr I did what you asked added an Example and Indentation is correct ..
will this merge request be accepted soon ?? I really wish I could contribute to this great work ..

**Pull request closed without merging**
