### PR TITLE
PR for issue #1555: change BUILTIN_LED to LED_BUILTIN

### PR DESCRIPTION
**Pull request by tuxedo0801**
changed all occurrences of BUILTIN_LED to arduino like LED_BUILTIN.

I hope I missed nothing ...

### CODE REVIEW

**Comment by igrr** [comment]
I'd vote for keeping BUILTIN_LED defined in pins_arduino.h, alongside with LED_BUILTIN.

**Comment by tuxedo0801** [comment]
Having both would be OK for me. I will update the PR accordingly.

**Comment by tuxedo0801** [comment]
now both variants are included. ESP style and Arduino style

LED_BUILTIN
BUILTIN_LED

**Comment by igrr** [comment]
Squashed and merged in 573a0fb, thanks.

**Pull request closed without merging**
