### PR TITLE
LEAmDNS

### PR DESCRIPTION
**Pull request by LaborEtArs**
Created a new branch to solve commit conflicts with recent changes to ESP8266mDNSResponder.cpp by d-a-v.
Also removed millis() roll-over issues.

### CODE REVIEW

**Comment by d-a-v** [comment]
@LaborEtArs 
I locally merged your branch, but there is no way to make a simple / short PR on your branch (to my github knowledge).
The only conflict is `library.properties` and to solve it you just need to replace the file with your version.

To handle this from scratch, and because we can't do it from github (only from cmdline), you can try:

- clone the official repo on some new directory
  `git clone https://github.com/esp8266/Arduino.git`
- add your source
  `cd Arduino`
  `git remote add lea https://github.com/LaborEtArs/Arduino.git`
- create a (local) new branch with the same name as yours
  `git checkout -b LEAmDNS`
- This branch is even with current github versionof the core. Now merge it with your repository
  `git pull lea LEAmDNS`
- You have the conflict, now edit `libraries/ESP8266mDNS/library.properties`, remove anything which is not yours
- commit your changes
  `git add libraries/ESP8266mDNS/library.properties`
  `git commit`
- leave the commit message (which is `merge blah`), save it
- now you are even, push to your branch
  `git push lea LEAmDNS`

**Comment by LaborEtArs** [comment]
Did all, what d-a-v recommended, now the PR seems to be mergeable... Anything left to do???

**Comment by d-a-v** [comment]
> Anything left to do???

Yes, update `libraries/ESP8266mDNS/src/ESP8266mDNS.h` L42:
`libraries/ESP8266mDNS/src/ESP8266MDNS.h` ->
`libraries/ESP8266mDNS/src/ESP8266mDNS.h`

**Comment by d-a-v** [comment]
Here are your two examples formatted by astyle for CI:
https://gist.github.com/d-a-v/0b70725d46ac7314fc98e7b02538f678
You must replace yours by them for CI to pass.

**Comment by LaborEtArs** [comment]
Updated 'libraries/ESP8266mDNS/src/ESP8266mDNS.h' and replaced 'libraries/ESP8266mDNS/examples/LEAmDNS/mDNS_Clock/mDNS_Clock.ino' and
'libraries/ESP8266mDNS/examples/LEAmDNS/mDNS_ServiceMonitor/mDNS_ServiceMonitor.ino'
then called
**add libraries/ESP8266mDNS/src/ESP8266mDNS.h
add libraries/ESP8266mDNS/examples/LEAmDNS/mDNS_Clock/mDNS_Clock.ino
add libraries/ESP8266mDNS/examples/LEAmDNS/mDNS_ServiceMonitor/mDNS_ServiceMonitor.ino**
and
**git commit**
but got
_On branch LEAmDNS
nothing to commit, working tree clean_
the final
**git push lea LEAmDNS**
produced
_Everything up-to-date_
I really don't like to walk around like a blind one...

**Comment by d-a-v** [comment]
Your branch can be updated from github to synchronise with master. 
Then you would need to `git pull lea LEAmDNS`

I reckon this can be tricky with big PR like yours and a master branch always updating.
If you are stuck, I can try to pull from your repository and propose PR on it.

**Comment by devyte** [comment]
Closing in favor of #5384 .

**Comment by d-a-v** [comment]
closing in favour of #5442

**Pull request closed without merging**
