### PR TITLE
Fix boards.txt.py compatible with python3

### PR DESCRIPTION
**Pull request by wemos**
change print "" to print()

### CODE REVIEW

**Comment by d-a-v** [comment]
Thanks !

Could you please sanitize this pull request by saving this file somewhere and starting from a clean-up-to-date master branch, then bring this file back and create a new PR ? (or you may try and update your master branch and use `git rebase master` in this fixing branch)

`doc/faq/a05-board-generator.rst` also needs update by removing the "python 2" requirement.

**Comment by wemos** [comment]
I make new PR #4995 , is it correct?

**Comment by d-a-v** [comment]
As far as I can see, it is the same one. Your previous commits are visible in this PR and they should not. Your master branch may not be flat (`gitk` may show a tube map).

What I would try is:
```
git checkout master
git pull origin master
git checkout e4d9c279ef1991256793745242c177148ca58b2a # current HEAD
git checkout -b new_fix_board
# copy/update files
# git add/commit files
git push wemos new_fix_board
```

**Comment by wemos** [comment]
@d-a-v Thank you for your help.
I make new #4998 , I think it is correct now.

**Pull request closed without merging**
