### PR TITLE
Add HTTP_HEAD to HTTPMethod and parse it

### LINKED ISSUE #6412: 'HTTP_HEAD' isn't declared in HTTPMethod
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware: ESP-12
- Core Version:	adfc28d7d8a8c97ecfc8aed0a5fff66e4e61c3c5
- Development Env: Arduino IDE (1.8.9)
- Operating System: ArchLinux

### Settings in IDE

- Module:  NodeMCU 1.0
- Flash Mode: dio (I believe)
- Flash Size: 4MB
- lwip Variant: v2 Lower Memory
- Reset Method: nodemcu (RTS pin)
- Flash Frequency: 40Mhz
- CPU Frequency: 160MHz
- Upload Using:	SERIAL
- Upload Speed: 115200

### Problem Description
The [HTTP HEAD method](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) isn't part of the [HTTPMethod enum](https://github.com/esp8266/Arduino/blob/76ed52c1b2063e7390a20cab9d90dd1facb733c7/libraries/ESP8266WebServer/src/ESP8266WebServer.h#L33) in the [ESP8266WebServer library](https://github.com/esp8266/Arduino/tree/76ed52c1b2063e7390a20cab9d90dd1facb733c7/libraries/ESP8266WebServer).

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <Arduino.h>
#include <ESP8266WebServer.h>

void setup() {
    HTTPMethod get = HTTP_GET; // Good
    HTTPMethod head = HTTP_HEAD; // Doesn't exist
}

void loop() {

}

```

### Debug Messages

```/home/zakcodes/Arduino/sketch_aug11a/sketch_aug11a.ino: In function 'void setup()':
sketch_aug11a:5:23: error: 'HTTP_HEAD' was not declared in this scope
     HTTPMethod head = HTTP_HEAD;
                       ^
Using library ESP8266WebServer at version 1.0 in folder: /home/zakcodes/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WebServer 
Using library ESP8266WiFi at version 1.0 in folder: /home/zakcodes/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WiFi 
exit status 1
'HTTP_HEAD' was not declared in this scope
```

### PR DESCRIPTION
**Pull request by ZakCodes**
Adds `HTTP_HEAD` to the `HTTPMethod` enum and parses it from a `String` when reading a request.

Resolves #6412

### CODE REVIEW

**Comment by ZakCodes** [comment]
I've added all the changes from the merge request you referred me to.  

I've added a conversion to string for the HTTP status code 418 because it was part of that merge request, but I didn't know if you wanted it or if you thought that it's just a waste of memory, so I've made sure to do it in a separate commit. 

I don't have any strong opinion on this status code, but what if someone wants to use an ESP8266 to control a tea pot?

**Comment by ZakCodes** [comment]
No problem, it's been a pleasure!

**Comment by johnm545** [comment]
This is causing builds to fail with tzapu's WiFiManager for me:

```cpp
In file included from C:\Users\John\Documents\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/sys/stdio.h:6:0,

                 from C:\Users\John\Documents\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/stdio.h:63,

                 from C:\Users\John\Documents\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Arduino.h:32,

                 from sketch\build_with_webserver_mcve.ino.cpp:1:

C:\Users\John\Documents\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h:25:130: error: 'const char HTTP_HEAD []' redeclared as different kind of symbol

   #define PROGMEM __attribute__((section( "\".irom.text." __FILE__ "." __STRINGIZE(__LINE__) "."  __STRINGIZE(__COUNTER__) "\"")))

                                                                                                                                  ^

C:\Users\John\Documents\Arduino\libraries\WiFiManager/WiFiManager.h:25:24: note: in expansion of macro 'PROGMEM'

 const char HTTP_HEAD[] PROGMEM            = "<!DOCTYPE html><html lang=\"en\"><head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\"/><title>{v}</title>";

                        ^

In file included from C:\Users\John\Documents\Arduino\libraries\WiFiManager/WiFiManager.h:17:0,

                 from C:\Users\John\Documents\Arduino\build_with_webserver_mcve\build_with_webserver_mcve.ino:2:

C:\Users\John\Documents\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266WebServer\src/ESP8266WebServer.h:33:39: error: previous declaration of 'HTTPMethod HTTP_HEAD'

 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

                                       ^

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).
```

Trivial test sketch: 
```cpp
#include <ESP8266WiFi.h>
#include <WiFiManager.h>

void setup() {
  // put your setup code here, to run once:
  
}

void loop() {
  // put your main code here, to run repeatedly:

}
```

Reverting the commit or changing the name of the HTTP_HEAD in WiFiManager makes the errors go away

**Comment by johnm545** [comment]
The problem is WiFiManager's naming choice, but WiFiManager is quite widely used

**Comment by d-a-v** [comment]
@tzapu @tablatronix what do you suggest ?
we can rename this consistent global enum
you can rename your internal variable
other suggestions ?

**Comment by devyte** [comment]
Looks like a name clash. please open a new issue, fill in the required info, and we'll track.
Notes:
Possible solutions:
Move webserver enum to enum class
Add namespace to WifiManager
Change WifiManager var names

**Comment by tablatronix** [comment]
I will hotfix this, and try to add namespacing to development branch, time permitting.

**Comment by tablatronix** [comment]
I just pushed .015-beta
This issue does not exists in WM development branch FYI

**Pull request merged**
