### PR TITLE
Added support for querying host IP numbers with the new method

### PR DESCRIPTION
**Pull request by pilotniq**
Fix for issue #2584 

Introduces new method:

`IPAddress queryHost( const chat *host );`

Please review the consequences for service queries, I've made some changes to the parsePacket code.

### CODE REVIEW

**Comment by me-no-dev** [comment]
I actually have a reworked parser ready for wider testing that follows MDNS compression and extracts better the information from the answers. That includes names, texts and addresses from host or service searches.
Will post it soon as I expect most of the code to be portable to ESP32 also.
Maybe you will want to contribute to that if I have missed something.

**Comment by pilotniq** [comment]
me-no-dev: Sounds good. My commit also has a new query function, as the old one could only query for services. Have you redone the queries as well?

**Comment by me-no-dev** [comment]
here is the current status: https://gist.github.com/me-no-dev/e13b507a6e850af6cef733b1b35d9923
it's based on AsyncUDP but that is not an issue in this case

**Comment by earlephilhower** [comment]
Thanks for your PR, but MDNS has been completely rewritten with this release, so this PR can't apply anymore without massive rework.

I'll leave open for two weeks and come back after Feb 10 and see if there's interest from the original submitter.  If not, will close then.

**Pull request closed without merging**
