### PR TITLE
PHY status API for ethernet drivers

### LINKED ISSUE #8099: LwipIntfDev::connected() does not reflect connection
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:					esp82xx
- Core Version:			git master
- Development Env:		Arduino IDE
- Operating System:		any

### Settings in IDE

- Module:  			any
- Flash Mode:			any
- Flash Size: 		any
- Reset Method:		any
- Flash Frequency:	any
- CPU Frequency:		any
- Upload Using:		any
- Upload Speed:   any

### Problem Description

https://github.com/esp8266/Arduino/pull/6680#pullrequestreview-558672527

> `LwipIntfDev::connected()` always returns true once it has connected once and acquired an IP address. So this does not really reflect the fact that the connection is active like you have with the WiFi. Even if you unplug the cable, it still returns true. This prevents to re-route to WiFi when ethernet is down.
Can't we replace this by checking the socket status by calling getSn_SR() ?

@jbaudoux @infrafast

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

https://github.com/esp8266/Arduino/blob/master/libraries/lwIP_w5500/examples/TCPClient/TCPClient.ino

### PR DESCRIPTION
**Pull request by d-a-v**
Implementation of `::isLinked()` for ethernet drivers:
This function returns true when the ethernet chip is physically connected.

(*edited*) It currently works and has been tested with W5500 and ENC28J60, and it seems it is not implementable with W5100.
An additional `::isLinkDetectable()` tells when `::isLinked()` is not trivially implemented.

(*edited*)`::connected()` ~is software only and is left unmodified for backward compatibility~ is updated to check link status to [solve compatibility with WiFi API](https://github.com/esp8266/Arduino/pull/6680#pullrequestreview-558672527).

Closes #8099

### CODE REVIEW

**Comment by d-a-v** [comment]
@JAndrassy Do you know if Link/PHY status can be read by software for W5100 and ENC28j60 ?

**Comment by JAndrassy** [comment]
@d-a-v yes it is possible
https://github.com/JAndrassy/EthernetENC/blob/9428b5e970dbc9882ac2aeed94725a1dd87615b9/src/utility/Enc28J60Network.cpp#L629

PHY register 0x11 bit 10
1 = Link is up
0 = Link is down

**Comment by d-a-v** [comment]
@JAndrassy Thanks !
I successfully used your code on my testboard.

It seems W5100 can't deliver link status readable by software ?
The Arduino driver [does not provide it](https://github.com/arduino-libraries/Ethernet/blob/9e8a98cd745ee4b4e033819bcc38721fb15ab1b7/src/utility/w5100.cpp#L272-L293).
I can't seem to find the right register in the [datasheet](https://www.wiznet.io/product-item/w5100/).

**Comment by mcspr** [comment]
btw do we care about Ethernet compatibility?
https://www.arduino.cc/reference/en/libraries/ethernet/ethernet.linkstatus/
https://github.com/esp8266/Arduino/search?q=linkStatus%28%29

**Comment by d-a-v** [comment]
[Yes, we do !](https://github.com/esp8266/Arduino/blob/master/libraries/lwIP_Ethernet/src/EthernetCompat.h)

**Pull request merged**
