### PR TITLE
Implement Async NBNS (NetBIOS) name resolution for Windows

### PR DESCRIPTION
**Pull request by me-no-dev**
Source: http://www.xpablo.cz/?p=751#more-751

### CODE REVIEW

**Comment by igrr** [comment]
What's the license for this code? Can we add appropriate copyrights?

**Comment by me-no-dev** [comment]
There were none. I have not changed anything but to make it async, so all that was there is still there. Code came in a zip. Url is in the properties file

**Comment by igrr** [comment]
That's what I mean, let's get in touch with the author so that he can help adding this.

**Comment by me-no-dev** [comment]
Sure thing. You or me?

**Pull request merged**
