### PR TITLE
Case change and and 'none' reset option for Digistump Oak

### PR DESCRIPTION
**Pull request by pfeerick**
The logo is 'digiStump', but is always written in text form as 'Digistump'. 

The generator fixed an issue with the release version of 2.4.0 not having a resetMethod for the Digistump Oak, and hence not being able to be uploaded to without modifying the boards.txt file. However, the Oak doesn't support auto-reset via serial - it was primarily designed to be a cloud-programmed board. Hence the addition of another resetMacro macro.

### CODE REVIEW

**Comment by pfeerick** [comment]
Damn github, should've done the changes to the local repo and pushed it from there, instead of editing directly on the github page in the first instance.

**Comment by pfeerick** [comment]
I noticed some minor formatting corrections that I was going to do related to the Oak section of docs/boards.rst (title, fix link to serial adapter heading), but I'm not sure if the `boards.txt.py` generation is working properly or if boards.rst has been generated by it yet? As what should have been only a change to two lines has done a LOT of changes when running `--docgen` ?

**Comment by d-a-v** [comment]
You are right, ```boards.rst``` is still the original one and has not yet been generated. The generator is quite fresh and the only generated data we use so far is ```boards.txt```.
This explains the lot of changes.
So while you are at it, then yes please do the commit.

**Comment by pfeerick** [comment]
Just mentioning this PR here as the regen of boards.rst, if all is good, should close #4083 as well.

**Comment by pfeerick** [comment]
Just a few final bits! :-O

**Pull request merged**
