### PR TITLE
Soft-AP documentation update

### PR DESCRIPTION
**Pull request by aerlon**
In several places of the documentation one can read "the maximum number of stations that may be connected to ESP8266 soft-AP is five." or something along those lines. However, the [softAP method](https://github.com/esp8266/Arduino/blob/9634f79f45eead2e053e30460b973ea000a0a8f6/libraries/ESP8266WiFi/src/ESP8266WiFiAP.h#L39) has a `int max_connection = 4` argument which represents ["Max simultaneous connected clients"](https://github.com/esp8266/Arduino/blob/9634f79f45eead2e053e30460b973ea000a0a8f6/libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp#L86). It would thus seem that the maximum number of stations that may be connected to ESP8266 soft-AP is four by default. This PR brings the documentation in line with the source code.

While looking into this issue I noticed that the topic may not be quite as simple as it first seems. Although the softAP method claims the max number of clients is 4, I've read other [claims](https://github.com/esp8266/Arduino/issues/570#issuecomment-338116826) that the [max is actually 8](https://bbs.espressif.com/viewtopic.php?f=46&t=481&p=1832&hilit=max_connection#p1832). @D-A-V even seems to have been able to get [12 simultaneous connections working](https://github.com/esp8266/Arduino/issues/4460#issuecomment-370382586) (though I'm not sure if that test is applicable here), and there are [some claims](https://bbs.espressif.com/viewtopic.php?t=4472 ) that the main limiting factor is actually only available memory.

Sadly I do not have enough ESPs to try where the max limit is for myself, so it would be good if @D-A-V or someone else with knowledge on this topic could confirm whether the max actually is 4, 8, 12 or something else.

### CODE REVIEW

**Comment by d-a-v** [comment]
I was telling that I could run 12 tcp connections simultaneously (layer3, in STA mode, with a PC), not having 12 wlan clients simultaneously connected to the Soft-AP (layer2).
I currently have not that much esp to test with. If there is a limitation, it should come from the internal firmware.
If there are no other mention in the nonos-sdk documentation, then you at least found an official statement from espressif.
IMHO, that information should also be stated in the sources (with reference).

**Comment by aerlon** [comment]
OK. Thanks for the clarification. 

I agree, providing a reference is a good practice. The question is which reference… 

Looking at [the latest NonOS API reference](https://www.espressif.com/sites/default/files/documentation/2C-ESP8266_Non_OS_SDK_API_Reference__EN.pdf) one can find the following at page 143/166: `uint8 max_connection; // default 4, max 4`. Which would seem to go against a lot of the other sources I've found indicating a max of 8, including [the previous one from Espressif](https://bbs.espressif.com/viewtopic.php?f=46&t=481&p=1832&hilit=max_connection#p1832) . It is all very confusing.

**Comment by devyte** [comment]
I think max wifi clients is 8, limited by the sdk. Espressif document 2C api reference should explain it. I can't look up the specific section right now, though, still limited to my broken phone.

**Comment by devyte** [comment]
To clarify, the sdk max used to be 4, and it was increased to 8, but the max default of 4 was kept. Now, if you want more than 4, you have to set a higher max explicitly. At least that's how I remember it.

**Comment by aerlon** [comment]
OK. If Espressif document 2C api reference is the following: https://www.espressif.com/sites/default/files/documentation/2C-ESP8266_Non_OS_SDK_API_Reference__EN.pdf
I was unable to find any other information than the one at page 143 I mentioned above.

However, I've since discovered [an Espressif forum thread](https://bbs.espressif.com/viewtopic.php?t=1894) where an employee states "ESP8266 soft-AP can connected to 8 stations at most." . I'm guessing page 143 in the NonOS API reference has not been updated since they increased the max.

The PR has been updated to reflect that valid values for `max_connection` is 1 to 8, and a reference has been added.

**Comment by d-a-v** [comment]
Thanks !

While you are at it, please check this recent #5082 PR
(not really wanting to be picky :)

[before](https://github.com/esp8266/Arduino/blob/master/doc/esp8266wifi/soft-access-point-class.rst#softap)
[after](https://github.com/aerlon/Arduino/blob/ap_documentation_update/doc/esp8266wifi/soft-access-point-class.rst#softap)
[rendered(before)](https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/soft-access-point-class.html#softap)

**Comment by devyte** [comment]
Ok so espressif's doc needs to be updated :P 
There is mention in the sdk releases changelog that the max allowed is 8 stations.

**Pull request merged**
