### PR TITLE
Base64::encode : const correctness / String by reference passing

### PR DESCRIPTION
**Pull request by dirkmueller**
This is another instance in the core library where we pass in read-only
parameters as pass-by-value, where in the case of String() that
is inefficient as it involves copy-constructor/temp string creations.

### CODE REVIEW

**Comment by dirkmueller** [comment]
@earlephilhower Inoticed the same, but I failed so far to "use" the String buffer for this. Only trick I know is with std::move().

**Comment by earlephilhower** [comment]
I think you'd need to make `class base64` a friend to get access to the `String::wbuffer()` (aka writable buffer pointer) method (and String::reserve() the proper length first, of course).  Otherwise some sort of new `String::assumeBuffer()` or something would need to be added.  Either would engender more debate than this PR, so I'd worry about it later.

**Comment by earlephilhower** [comment]
@dirkmueller I realized you can actually do inline base64 encoding directly into the string w/o any add'l String accessor methods.  Just pass in the String and instead of writing bytes to the array, just += the chars as they're generated.  Easy-peasy, and 1/2 the RAM needed.  But that's another PR. :)

**Comment by devyte** [comment]
Don't forget to reserve() beforehand.

**Pull request merged**
