### PR TITLE
Completes #6048: let FunctionalInterrupt.h support only IRAM-safe scheduled ISRs

### PR DESCRIPTION
**Pull request by dok-net**
Makes for a much cleaner cores/esp8266/core_esp8266_wiring_digital.cpp:
- no special "functional" predicate
- no reverse "duplicate from functionalInterrupt.h keep in sync" copied-code dependency

### CODE REVIEW

**Comment by hreintke** [comment]
@dok-net @d-a-v @devyte 
disclaimer : I did nor read all the remarks from the last days as I was on a short break.

Doesn't solve https://github.com/esp8266/Arduino/pull/5922 the issue that std::function<void(void)> cannot be used in attachInterrupt  due to  not being in IRAM ?

**Comment by devyte** [comment]
it should. I've only taken a quick glance at the recent PRs, we're currently trying to get 2.5.1 out the door.

**Comment by dok-net** [comment]
@devyte @hreintke Maybe it's just me, I don't understand the point of using functional if all that's supported are static functions. Please run, commenting / uncommting the various cases, this MCVE:

`#include <Schedule.h>
#include <FunctionalInterrupt.h>

class Interrupt {
public:
	void ICACHE_RAM_ATTR isr_iram() {
		schedule_function([]() { Serial.println("isr_iram"); });
	}

	void ICACHE_FLASH_ATTR isr_flash() {
		schedule_function([]() { Serial.println("isr_flash"); });
	}

	static void ICACHE_RAM_ATTR isr_static(void* self) {
		if (self) static_cast<Interrupt*>(self)->isr_flash();
	}
};

Interrupt intr;
bool d6State = false;

void ICACHE_RAM_ATTR isr_single_iram() {
	intr.isr_iram();
}

void ICACHE_RAM_ATTR isr_single_flash() {
	intr.isr_flash();
}

void ICACHE_RAM_ATTR isr_single_with_functional() {
	auto fn = [](Interrupt& self) { self.isr_flash(); };
	fn(intr);
}

void setup() {
	Serial.begin(9600);
	delay(1000);
	pinMode(D5, INPUT);
	pinMode(D6, OUTPUT);
	attachInterrupt(D5, isr_single_flash, CHANGE); // hides bad use of ICACHE_FLASH_ATTR function
	//attachInterrupt(D5, isr_single_with_functional, CHANGE); // hides bad use of lambda and ICACHE_FLASH_ATTR function
	//attachInterrupt(D5, []() { isr_single_iram(); }, CHANGE); // Doesn't compile if include FunctionalInterrupt.h, otherwise: ISR not in IRAM!
	//attachInterrupt(D5, []() { intr.isr_iram(); }, CHANGE); // Doesn't compile if include FunctionalInterrupt.h, otherwise: ISR not in IRAM!
	//std::function<void()> fn = isr_single_flash;
	//attachInterrupt(D5, fn, CHANGE); // hides bad use of std::function wrapping ICACHE_FLASH_ATTR function
	//detachInterrupt(D5); // uncomment for testing #6049

	schedule_function([]() { Serial.println("Hello"); });
}

void loop()
{
	digitalWrite(D6, d6State);
	d6State ^= true;
}`

**Comment by dok-net** [comment]
@devyte @hreintke Maybe it's just me, I don't understand the point of using functional if all that's supported are static functions. Please run, commenting / uncommenting the various cases, this MCVE:

`#include <Schedule.h>
#include <FunctionalInterrupt.h>

class Interrupt {
public:
	void ICACHE_RAM_ATTR isr_iram() {
		schedule_function([]() { Serial.println("isr_iram"); });
	}

	void ICACHE_FLASH_ATTR isr_flash() {
		schedule_function([]() { Serial.println("isr_flash"); });
	}

	static void ICACHE_RAM_ATTR isr_static(void* self) {
		if (self) static_cast<Interrupt*>(self)->isr_flash();
	}
};

Interrupt intr;
bool d6State = false;

void ICACHE_RAM_ATTR isr_single_iram() {
	intr.isr_iram();
}

void ICACHE_RAM_ATTR isr_single_flash() {
	intr.isr_flash();
}

void ICACHE_RAM_ATTR isr_single_with_functional() {
	auto fn = [](Interrupt & self) { self.isr_flash(); };
	fn(intr);
}

void setup() {
	Serial.begin(9600);
	delay(1000);
	pinMode(D5, INPUT);
	pinMode(D6, OUTPUT);
	attachInterrupt(D5, isr_single_flash, CHANGE); // hides bad use of ICACHE_FLASH_ATTR function
	//attachInterrupt(D5, isr_single_with_functional, CHANGE); // hides bad use of lambda and ICACHE_FLASH_ATTR function
	//attachInterrupt(D5, []() { isr_single_iram(); }, CHANGE); // Doesn't compile if include FunctionalInterrupt.h, otherwise: ISR not in IRAM!
	//attachInterrupt(D5, []() { intr.isr_iram(); }, CHANGE); // Doesn't compile if include FunctionalInterrupt.h, otherwise: ISR not in IRAM!
	//std::function<void()> fn = isr_single_flash;
	//attachInterrupt(D5, fn, CHANGE); // hides bad use of std::function wrapping ICACHE_FLASH_ATTR function
	//detachInterrupt(D5); // uncomment for testing #6049

	schedule_function([]() { Serial.println("Hello"); });
}

void loop()
{
	digitalWrite(D6, d6State);
	d6State ^= true;
}
`

**Comment by dok-net** [comment]
@devyte @hreintke Maybe it's just me, I don't understand the point of using functional if all that's supported are static functions. Please run, commenting / uncommenting the various cases, the attached MCVE.
[AttachInterruptArg.ino.txt](https://github.com/esp8266/Arduino/files/3162494/AttachInterruptArg.ino.txt)

**Comment by d-a-v** [comment]
> I don't understand the point of using functional if all that's supported are static functions

I agree.

You have lots of running PRs. Are they all related ? If so can you group them in one single PR ?
To be honest I'm quite lost :]

**Comment by hreintke** [comment]
I tried to get std::function::target running with rtti option set to verify myself but I only got crashes.

If I have a construct like 
```
class InterruptTest
{
public:

	InterruptTest()
	{

		Serial.begin(115200);
		attachInterrupt(D5,std::bind(&InterruptTest::isr_iram,this),FALLING);
	}


	void ICACHE_RAM_ATTR isr_iram()
	{
		schedule_function([]() { Serial.println("isr_iram"); });
	}
};
```
Would that be a valid use (together with #5922 ?)

**Comment by dok-net** [comment]
This PR is more readable now (turn on diff settings: hide whitespace changes).
It is best reviewed as diff against https://github.com/dok-net/Arduino/tree/bugfix/attachInterrupt , or after PR #6048 was merged.

**Comment by dok-net** [comment]
Development of this branch stopped.
Cause: implementation based on std::function is more advanced, previous concerns involving IRAM-proofness have been addressed. Please go on with review/merge of #6047

**Pull request closed without merging**
