### PR TITLE
nonos-sdk: update to latest version 2.2.x branch, commitlog added in tree

### PR DESCRIPTION
**Pull request by d-a-v**
Optional and only available for generic esp8266 board.

### CODE REVIEW

**Comment by torntrousers** [comment]
Sounds interesting - do you know does this include the ESP-Now Broadcast fix from 3.0? 

https://github.com/espressif/ESP8266_NONOS_SDK/issues/8

**Comment by d-a-v** [comment]
About espnow, there is a mention in the current testing sdk's commitlog (the commitlog is added in this PR):
```
$ zgrep -i now NONOSDK22*/commitlog*gz
NONOSDK22x/commitlog-from-221.txt.gz:    Merge branch 'feature/add_broad_support_for_espnow' into 'release/v2.2.x'
NONOSDK22x/commitlog-from-221.txt.gz:    feat(espnow): Add broadcast packets support for espnow
```

So I guess you're good to test this right now from master with generic esp8266 board for the sdk selection menu to appear.

**Comment by torntrousers** [comment]
Cool, will try tonight

**Comment by torntrousers** [comment]
Still doesn't seem to work with ESP-Now broadcasts, running the sketch from https://github.com/esp8266/Arduino/issues/6174 on two ESP's don't receive each other anyway.

**Comment by devyte** [comment]
@torntrousers you may want to rrquest at Espressif's repo a backport of the esp now fix to their 2.2.x branch.

**Comment by torntrousers** [comment]
As it worked for you I tried with master now that this is merged and it works for me too. Great! 
(don't know why it didn't work yesterday, I was trying with the d-a-v:sdk222y branch, maybe I'd messed up the install or something)

**Comment by d-a-v** [comment]
You me tell [them](https://github.com/espressif/ESP8266_NONOS_SDK/issues/248) !

**Pull request merged**
