### PR TITLE
WiFiClientSecure half-duplex contract.

### PR DESCRIPTION
**Pull request by diegopx**
The internal axTLS library is half duplex, but WiFiClientSecure acts as if it was full duplex. This results in subtle bugs due to erroneous memory access. This branch fixes these bugs and establishes the half-duplex contract in the WiFiClientSecure interface.

### CODE REVIEW

**Comment by thirsch** [comment]
+1

Also fixes the call to ssl_client_new and passes the hostname in the correct way. You can't connect to a host with multiple certificates using TLS extension SNI otherwise.

**Comment by MumblesNZ** [comment]
Thanks Diegopx, I was having issues with getting kicked periodically from my MQTT connection (using pubsubclient), and this + your pubsubclient changes seemed to have fixed it.

**Comment by vshymanskyy** [comment]
@igrr could you please take a look at this?
It should fix the major issue we experience using Blynk with SSL.
Thank you!

**Comment by igrr** [comment]
@vshymanskyy could you add a reference to the issue you are facing?

**Comment by vshymanskyy** [comment]
@igrr The issue is well explained here: https://github.com/esp8266/Arduino/issues/3002
We're facing the same behavior as Blynk protocol is full-duplex like MQTT

**Comment by tripish** [comment]
@igrr Do you have any sense of when this might be resolved? I'm encountering the same issue. I'd like to pull in the changes in the interim, but the associated axtls binaries are pretty old compared and I'm not sure I want to dive down the rabbit hole to check the changes and re-compile if it might be resolved soon.

**Comment by vshymanskyy** [comment]
@tripish @igrr https://github.com/esp8266/Arduino/pull/3019 helps a lot. in fact, I couldn't get it to crash in my scenario again.
It would be great to solve the problem for the upcoming release...

**Comment by igrr** [comment]
Closing in favor of #4024

**Pull request closed without merging**
