### PR TITLE
md to rst

### LINKED ISSUE #3689: .md -> .rst in "new issue" pattern
> if you have a stack dump decode it:
>https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

>for better debug messages:
>https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

But actual instructions in `rst` 
[https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst](https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst)
[https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst](https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst)

### PR DESCRIPTION
**Pull request by bscheshir**
actual instructions in rst

fixed #3689

### CODE REVIEW

**Comment by devyte** [comment]
@igrr this fixes the links to the docs. Do we want that, or do we want to migrate the docs to markdown, or do we want both?

**Comment by igrr** [comment]
@devyte Well the docs have been migrated from .md to .rst recently to be able to use readthedocs, so we just want to fix the remaining broken links.

@bscheshir Thank you for the fix. Do you think that pointing to HTML docs will be nicer/more useful? E.g. http://arduino-esp8266.readthedocs.io/en/latest/Troubleshooting/debugging.html.
If yes, would you mind amending your commit?

**Comment by bscheshir** [comment]
@igrr http://arduino-esp8266.readthedocs.io/en/latest/Troubleshooting/debugging.html is automatic build from last tag? I am right?

but old link 
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md and new link
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst is `master` branch, not is last tag

**Comment by igrr** [comment]
"latest" on readthedocs is automatically built from master on each commit. To get docs for tagged version (e.g. v2.4.0-rc1), replace "latest" with the tag name.

**Comment by bscheshir** [comment]
So... I think is `arduino-esp8266.readthedocs.io` have a good design, but `https://github.com/esp8266/Arduino` is a same host with repo, I think more people trust github. 

I vote for github :smiley_cat:

**Pull request merged**
