### PR TITLE
ESP8266WiFi extended functions

### PR DESCRIPTION
**Pull request by Links2004**
ESP8266WiFi extended functions

begin changes
allow setting BSSID/MAC and Channel of an AP for faster connection (#261)
now checks if ssid and passphrase to big
selecting Wifi mode in better way (fix for #28)

ESP8266WiFiMulti uses the new functions to auto select best AP even in a multi AP WiFi network (more the one AP has same SSID)

add new functions to get current Connected AP:
uint8_t * BSSID(void);
int32_t Channel(void);

add new functions to get infos from scanned networks:
uint8_t * BSSID(uint8_t networkItem);
int32_t Channel(uint8_t networkItem);
bool isHidden(uint8_t networkItem);
bool getNetworkInfo(uint8_t networkItem, const char** ssid, uint8_t * encryptionType, int32_t * RSSI, uint8_t ** BSSID, int32_t * channel, bool * isHidden);

### CODE REVIEW

**Comment by kgolding** [comment]
Have just cloned and build from source 1.6.5, loaded the WiFiScan example and I get the following error when I try to compile:

WiFiScan.ino: In function 'void loop()':
WiFiScan:38: error: 'class ESP8266WiFiClass' has no member named 'BSSID'
'class ESP8266WiFiClass' has no member named 'BSSID'

**Comment by stozk** [comment]
Same here, can't use the WiFi.BSSID(i) atm.

**Comment by Links2004** [comment]
can you please check if
https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.h#L214
and
https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.cpp#L347
are in you locale files.

**Comment by igrr** [comment]
Also check if you have the board manager package installed. You need to uninstall it if you have because it overrides any cores bundled with the app.

**Comment by kgolding** [comment]
My local ESP8266WiFI.cpp & .h files match those in Links2004 links.

I've removed the board url from the preferences, and I've deleted all my settings from ~/arduino15, but I am now getting a different error:

```
Arduino: 1.6.5 (Linux), Board: "Olimex MOD-WIFI-ESP8266(-DEV), 80 MHz, 115200"

WiFiScan.ino: In function 'void loop()':
WiFiScan:38: error: call of overloaded 'print(uint8_t*)' is ambiguous
WiFiScan.ino:38:33: note: candidates are:
In file included from /home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Stream.h:26:0,
                 from /home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/HardwareSerial.h:32,
                 from /home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Arduino.h:211,
                 from /home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/WiFiClient.h:24,
                 from /home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.h:32,
                 from WiFiScan.ino:6:
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:68:16: note: size_t Print::print(const String&) <near match>
         size_t print(const String &);
                ^
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:68:16: note:   no known conversion for argument 1 from 'uint8_t* {aka unsigned char*}' to 'const String&'
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:69:16: note: size_t Print::print(const char*) <near match>
         size_t print(const char[]);
                ^
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:69:16: note:   no known conversion for argument 1 from 'uint8_t* {aka unsigned char*}' to 'const char*'
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:70:16: note: size_t Print::print(char) <near match>
         size_t print(char);
                ^
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:70:16: note:   no known conversion for argument 1 from 'uint8_t* {aka unsigned char*}' to 'char'
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:71:16: note: size_t Print::print(unsigned char, int) <near match>
         size_t print(unsigned char, int = DEC);
                ^
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:71:16: note:   no known conversion for argument 1 from 'uint8_t* {aka unsigned char*}' to 'unsigned char'
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:72:16: note: size_t Print::print(int, int) <near match>
         size_t print(int, int = DEC);
                ^
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:72:16: note:   no known conversion for argument 1 from 'uint8_t* {aka unsigned char*}' to 'int'
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:73:16: note: size_t Print::print(unsigned int, int) <near match>
         size_t print(unsigned int, int = DEC);
                ^
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:73:16: note:   no known conversion for argument 1 from 'uint8_t* {aka unsigned char*}' to 'unsigned int'
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:74:16: note: size_t Print::print(long int, int) <near match>
         size_t print(long, int = DEC);
                ^
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:74:16: note:   no known conversion for argument 1 from 'uint8_t* {aka unsigned char*}' to 'long int'
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:75:16: note: size_t Print::print(long unsigned int, int) <near match>
         size_t print(unsigned long, int = DEC);
                ^
/home/kgolding/bin/arduino-1.6.5/hardware/esp8266com/esp8266/cores/esp8266/Print.h:75:16: note:   no known conversion for argument 1 from 'uint8_t* {aka unsigned char*}' to 'long unsigned int'
call of overloaded 'print(uint8_t*)' is ambiguous

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
```

**Comment by igrr** [comment]
Let me try some telepathy... did you replace ```Serial.print(WiFi.RSSI(i));``` with ```Serial.print(WiFi.BSSID(i));``` in your sketch? This is not valid code...

**Comment by kgolding** [comment]
igrr yes! Sorry!

**Comment by Links2004** [comment]
have add some functions to get the MAC / BSSID as string.
https://github.com/Links2004/Arduino/commit/877aa5aad7d5b5af7fad6db23c71d672e8a4d775

**Comment by kgolding** [comment]
For those like I who want to convert the WiFi.BSSID() result to a string, I've created the following function (inspired by @Links2004 functions):

```
String bssidToString(uint8_t *bssid) {
  char mac[18] = {0};
  sprintf(mac,"%02X:%02X:%02X:%02X:%02X:%02X", bssid[0],  bssid[1],  bssid[2], bssid[3], bssid[4], bssid[5]);
  return String(mac);
}
```

This can be called using:
```
Serial.print(bssidToString(WiFi.BSSID(i)));
```

**Comment by keegho** [comment]
@kgolding great function. Best answer. Thanks

**Pull request merged**
