### PR TITLE
Removed "Upload Using:" from the menu since it is now misleading

### PR DESCRIPTION
**Pull request by krzychb**
Ref: https://github.com/esp8266/Arduino/issues/1702
Another RP as previous failed I am not clear why.
Good luck :smile:

### CODE REVIEW

**Comment by igrr** [comment]
Don't worry about failing CI checks. I'll take care of that.
By the way, if you rename a file you should also update the menu here: https://github.com/esp8266/Arduino/blob/master/doc/reference_items.yml#L11
This one is used for HTML docs generation.

**Comment by krzychb** [comment]
Thanks @igrr!
I will issue supplementary PR to cover update for HTML docs.
Krzysztof

**Comment by igrr** [comment]
You can simply push more commits here without creating another PR.

**Comment by igrr** [comment]
Okay, i think CI build might have been broken by the changes to boards.txt.

**Comment by krzychb** [comment]
@igrr,
This is fun discovering all internal of platorm package deployment :+1: 
Krzysztof

**Pull request merged**
