### PR TITLE
Allow users to inherit and override CertStore

### PR DESCRIPTION
**Pull request by paulocsanz**
Fixes: #7826

This seems the minimal change that is enough to avoid guard headers hacks and allow users to have a more customized CertStore.

### CODE REVIEW

**Comment by paulocsanz** [comment]
I don't get it, what happened to the CI? Did I break something? Was this just a timeout? How to re-run?

**Comment by paulocsanz** [comment]
I've been thinking if it's not better to make a CertStoreBase with a virtual `installCertStore`, make CertStore inherit from and basically not modify it. And where CertStore is passed we can pass a CertStoreBase.

What are the thoughts of the community?

I can modify my PR accordingly.

**Comment by earlephilhower** [comment]
> I've been thinking if it's not better to make a CertStoreBase with a virtual `installCertStore`, make CertStore inherit from and basically not modify it. And where CertStore is passed we can pass a CertStoreBase.

That seems like a reasonable thing to do and would avoid dragging unneeded class variables into subclasses.  But, I'm sure you are trying to get some other way to hold the certstore (i.e. a PROGMEM array), so if you can get that in it would really be nice.

**Comment by paulocsanz** [comment]
Perfect, I've implemented it.

Pardon my lack of c++ knowledge, but should CertStoreBase have a virtual destructor? It was erroring when I put it, removing it fixed. But it seems that without it if someone with a CertStoreBase pointer tries to destroy it, it will cause problems. Although the code never does that, since it only borrows the CertStoreBase.

But Idk about c++ best practices surrounding virtual destructors.

I know CertStore should be long-lived and probably never destroyed, but just to make sure it won't cause problems one day.

**Review by earlephilhower — APPROVED** [review]
Looks good.  Did you want to add in your other CertStore object?

**Comment by paulocsanz** [comment]
As I said in the original issue I don't think it's the best move stabilizing another CertStore alternative, with its own python script. I can provide the alternative if it's deemed that since so many people depend on the hacks and save certs to PROGMEM in source code.

But I'm not realy confortable doing it right now, but I can indeed provide it in a future PR.

**Comment by maakbaas** [comment]
@paulocsanz: Thanks for adding this! It seems that this change was at least partly inspired by my hack, which indeed came about due to the lack of virtual methods.  I have updated my code with the new inheritance mechanism in this commit: https://github.com/maakbaas/esp8266-iot-framework/commit/8a752f8443a8bb770ce8165442981d1362a64422

**Pull request merged**
