### PR TITLE
fix possible free of null in String

### PR DESCRIPTION
**Pull request by Links2004**

### CODE REVIEW

**Comment by igrr** [comment]
The free() function deallocates the memory allocation pointed to by ptr. If ptr is a NULL pointer, no
     operation is performed.

**Comment by Links2004** [comment]
it will generate an error message when ```setDebugOutput``` is active.

**Comment by pgollor** [comment]
Sorry for the question. But why we are using malloc and free and not new and delete. Malloc is for c and new is the better way in CPP to allocate memory.
Or am i wrong?

**Comment by Links2004** [comment]
and ```new``` and ```delete``` are implemented with ```malloc``` and ```free``` ;)
https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/cores/esp8266/abi.cpp#L28

**Comment by pgollor** [comment]
thanks @Links2004 :)

**Comment by mangelajo** [comment]
+1, let's avoid unnecessary error messages in debug if possible.

**Pull request merged**
