### PR TITLE
Add  support for my new board eduino wifi

### PR DESCRIPTION
**Pull request by schirmilabs**
I have added support for my new board eduino wifi.
https://schirmilabs.de/?page_id=165

### CODE REVIEW

**Comment by jandrassy** [comment]
because esp8266 Arduino boards package still can't be used as referenced package.
https://github.com/esp8266/Arduino/issues/5769

**Comment by d-a-v** [comment]
@jandrassy Can you give more explanations ? (I reread #5769 and #5770 ) and how is it related to this PR ?

@schirmilabs 
Is your board available for selling ?

I see that we forgot to commit this `eagle.flash.2m64.ld` file, thanks for noticing !

We could update boards.txt.py to add the possibility to update some user-defined local definitions and get personalized menus.

**Comment by schirmilabs** [comment]
@d-a-v 
At the moment I am working on the assembly manual. If this if finished I will publish the project on github. Are you interested in buying a kit  ?

**Comment by d-a-v** [comment]
For a start, I was thinking of the community interest for having such a board in the menu.
Thanks for your proposal :)

**Comment by devyte** [comment]
@schirmilabs will you be fixing this?

**Comment by schirmilabs** [comment]
Hi,
I have fixed it, but got an error in
Mac OSX can build sketches

What ist the problem ?

**Comment by earlephilhower** [comment]
The MAC VM froze.  I restarted and the run just completed fine.

**Comment by schirmilabs** [comment]
Thanks for your support. I have created an instructable for it: https://www.instructables.com/id/Eduino-WiFi/

**Pull request merged**
