### PR TITLE
support new board (invent one)

### PR DESCRIPTION
**Pull request by inventvictor**
Please Add support for the Invent One

Information of the product can be found here : [htps://inventone.ng.](url)
More information on the board can be found here : [https://blog.inventone.ng](url)

Thank you!

### CODE REVIEW

**Comment by inventvictor** [comment]
Also please help me change the LED_BUILTIN in ./tools/variants/inventone/pins_arduino.h to 2 instead of 16.

Can you please do that for me?

**Comment by d-a-v** [comment]
> Also please help me change the LED_BUILTIN in ./tools/variants/inventone/pins_arduino.h to 2 instead of 16.


You can do it yourself, just commit the update to your own repository, it will be updated here.

Also something is wrong:
- you must delete (and commit the deletion) of all `.orig` files.
- your `tools/sdk/ld/eagleflash.1.*` files are all wrong, remove them too.

Did you use `./tools/boards.txt.py --allgen` to generate these files ?

**Comment by inventvictor** [comment]
Yes I used 
`./tools/boards.txt.py --allgen`

I should manually delete the specified files right?

**Comment by d-a-v** [comment]
> I should manually delete the specified files right?

With `git rm`, yes

What is your python version ?
All the `*.0.*` or `*.1.*` files/names should not be generated.

**Comment by inventvictor** [comment]
My version of Python is 3.6.6

**Comment by inventvictor** [comment]
I have committed the changes.
Can you please help me merge this.

Thanks in advance.

**Comment by d-a-v** [comment]
I just tried with python 3.6 and I got the same bug.
Use python 2.7 instead for now until fixed.
with linux: `$ python2 ./tools/boards.txt.py --allgen`

**Comment by inventvictor** [comment]
But I have done that before and the necessary files were generated.

Do I have to start the process again using python 2?

**Comment by inventvictor** [comment]
Just ran : `$ python2 ./tools/boards.txt.py --allgen`
Gave me : Everything up-to-date

Please, what else do I have to do?

**Comment by d-a-v** [comment]
> So instead of pushing to a branch on the forked repo, I should push to master directly?

No, you need to push to your `inventvictor:newboard` branch.

> Please assist me to do this!!

actually I am.

You need to try, on your repo: `git diff master`

If you see anything other than your new board in `boards.txt` in diff, then something is wrong.
I tried your `boards.txt.py` with python2 and it works, so you should get the same results.

**Comment by inventvictor** [comment]
Thank you for your help. I really appreciate it.

I have created a new branch and created a nue pull request ([https://github.com/esp8266/Arduino/pull/5286](url))

I used Python2 to generate the necessary files, I got the exact response you expected me to get and I believe everything should be fine now.

Please help merge this.
Thank you in advance.

Best, 
Victor.

**Pull request closed without merging**
