### PR TITLE
Fix ESP8266NetBIOS to compile with lwip V2

### PR DESCRIPTION
**Pull request by luc-github**

### CODE REVIEW

**Comment by devyte** [comment]
@d-a-v this looks correct to me, but could you please give it a look?

**Comment by d-a-v** [comment]
It WorksForMe in both version.

I have a proposal:
```<ip_addr.h>``` defines ```ip_addr``` in v1.4 and ```ip_addr_t``` in both lwip. 
so why not use it.
```
--- a/libraries/ESP8266NetBIOS/ESP8266NetBIOS.h
+++ b/libraries/ESP8266NetBIOS/ESP8266NetBIOS.h
@@ -3,7 +3,8 @@
 #define __ESPNBNS_h__
 
 extern "C" {
-#include "lwip/init.h" // LWIP_VERSION_
+#include <lwip/init.h> // LWIP_VERSION_
+#include <lwip/ip_addr.h>
 }
 #include <ESP8266WiFi.h>
 
@@ -18,12 +19,6 @@ extern "C" {
 
 struct udp_pcb;
 struct pbuf;
-#if LWIP_VERSION_MAJOR == 1 
-struct ip_addr;
-#else
-struct ip4_addr;
-typedef ip4_addr_t ip_addr_t;
-#endif
 
 class ESP8266NetBIOS
 {
```

And since the ```.cpp``` is also updated, for the WallWextra guys, I propose this too:
```
--- a/libraries/ESP8266NetBIOS/ESP8266NetBIOS.cpp
+++ b/libraries/ESP8266NetBIOS/ESP8266NetBIOS.cpp
@@ -146,7 +146,7 @@ bool ESP8266NetBIOS::begin(const char *name)
     }
 
     // presuneme jmeno zarizeni se soucasnou upravou na UPPER case
-    for (int i = 0; i < n; ++i) {
+    for (size_t i = 0; i < n; ++i) {
         _name[i] = toupper(name[i]);
     }
     _name[n] = '\0';
@@ -180,6 +180,9 @@ void ESP8266NetBIOS::_recv(udp_pcb *upcb, pbuf *pb, ip_addr_t *addr, uint16_t po
 void ESP8266NetBIOS::_recv(udp_pcb *upcb, pbuf *pb, const ip_addr_t *addr, uint16_t port)
 #endif
 {
+    (void)upcb;
+    (void)addr;
+    (void)port;
     while(pb != NULL) {
         uint8_t * data = (uint8_t*)((pb)->payload);
         size_t len = pb->len;
```

**Comment by Pablo2048** [comment]
ok, so I can translate all comments to english :-) ...

**Comment by devyte** [comment]
@luc-github can you please update the PR with the suggestions?

**Pull request merged**
