### PR TITLE
Improve the compatibility of the doc between Github and RTD...

### PR DESCRIPTION
**Pull request by lrmoreno007**
Added the installation of the nbsphinx package that ensure the compatibility of the documentation between Github and RTD.

The admin in ReadTheDocs must ensure that:
- In advanced setting, set requirements file: `doc/requirements.txt`   <---- Use this exactly
- In advanced setting, ensure Python interpreter are: `CPython 2.x` or `CPython 3.x`

Now we must always use GitHub links and now the links directly work in ReadtheDocs. ~~Progressively we must change the links of the `:doc:` and `:ref` Sphinx native types that exist in the documentation (but first this PR must be approved).~~

Special thanks to: @mgeier

Read more... https://github.com/esp8266/Arduino/issues/4409

### CODE REVIEW

**Comment by lrmoreno007** [comment]
Cambié todos los enlaces con estilo Sphinx.

**Comment by d-a-v** [comment]
Out of curiosity How are you viewing the result in readthedoc.io ?

> In advanced setting, set requeriments file: `doc/requeriments.txt` <---- Use this exactly

Can you double-check the spelling ?

Note that I'm not questioning the validity of this PR.

**Comment by lrmoreno007** [comment]
Excuse me, must be `doc/requirements.txt` 

I see the results in my repo that is a translation to Spanish of this one.
http://esp8266-arduino-spanish.readthedocs.io/es/latest/index.html

**Comment by devyte** [comment]
@lrmoreno007 this sounds pretty cool. Let me know when you're done, and I'll merge.

**Comment by lrmoreno007** [comment]
It's ready to merge if you want.

**Pull request merged**
