### PR TITLE
try to fix http parsing

### PR DESCRIPTION
**Pull request by d-a-v**
for #5261 testing

### CODE REVIEW

**Comment by ascillato** [comment]
This PR works great! Parsing has been solved! Great job! :+1: 

Thanks.

**Comment by ascillato** [comment]
with last changes, webserver parsing don't work. sorry

**Comment by d-a-v** [comment]
Last changes reverted, see https://github.com/esp8266/Arduino/issues/5261#issuecomment-432158653

**Comment by ascillato** [comment]
@d-a-v 

Testing the actual core with the PR #5262, webserver parsing start to work again.

**Pull request merged**
