### PR TITLE
i2c-slave support

### PR DESCRIPTION
**Pull request by bjoham**
Got a request to "push" this into the master branch. Perhaps I am doing that now...

The slave support has been working for over three months for my setup with an ESP8266 HUZZAH module connected through an NPN-transistor level shifter to my heat pump. Others have not been that lucky, it seems...

* The implementation is based on interrupts
* Because of interrupt latencies, the maximum clock speed (so far) is around 15 kHz
  - Setting a low clock is not supported through the Arduino API
* The implementation is a direct "port" of the HW description of the Atmega 328 MCU
  - No code optimizations are done
* It supports clock stretching 
  - Some/Most Arduino implementations reset the HW which in effect ignores this feature
  - I have published a fix to the Arduino boards GIT and tested it on my HW initially, but has later improved the callbacks so it has no effect in my current setup

### CODE REVIEW

**Comment by jofleck** [comment]
Any news here?

**Comment by haarislabs** [comment]
Hey 	bjoham  ,

I have downloaded your esp8266_Arduino repository for slave support but when I compile it the Arduino IDE shows me this error

```
C:\Users\HAARIS~1\AppData\Local\Temp\arduino_build_675126/slave_sender.ino.elf section `.text' will not fit in region `iram1_0_seg'

collect2.exe: error: ld returned 1 exit status

Error compiling for board Generic ESP8266 Module.
```
Thanks

**Comment by bjoham** [comment]
What module are you using? It seems to be too little memory.
My module is a Huzzah from Adafruit.
/B

haarislabs <notifications@github.com> skrev: (16 mars 2018 12:14:13 CET)
>Hey 	bjoham  ,
>
>I have downloaded your esp8266_Arduino repository for slave support but
>when I compile it the Arduino IDE shows me this error
>
>```
>C:\Users\HAARIS~1\AppData\Local\Temp\arduino_build_675126/slave_sender.ino.elf
>section `.text' will not fit in region `iram1_0_seg'
>
>collect2.exe: error: ld returned 1 exit status
>
>Error compiling for board Generic ESP8266 Module.
>```
>Thanks 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/esp8266/Arduino/pull/3237#issuecomment-373682912

-- 
Skickat från min Android-enhet med K-9 Mail. Ursäkta min fåordighet.

**Comment by haarislabs** [comment]
I have Esp8266 12e

http://www.kloppenborg.net/images/blog/esp8266/esp8266-esp12e-specs.pdf

**Comment by haarislabs** [comment]
Hey bjoham,
I selected the Adafruit Huzzah 8266 board to see if it compiles without any error or not but it gives me the following error

```
C:\...\Temp\arduino_build_675126/slave_sender.ino.elf section `.text' will not fit in region `iram1_0_seg'

collect2.exe: error: ld returned 1 exit status

Using library Wire at version 1.0 in folder: ..\esp8266\hardware\esp8266\2.4.1\libraries\Wire 
exit status 1
Error compiling for board Adafruit HUZZAH ESP8266.
```
Thanks for the reply

**Comment by bjoham** [comment]
Hmm, something gets too large for the ram memory, it seems.

In two weeks I might have some time for this. Meanwhile, you could try 
to uncomment sections of the code to see what parts make it fail.

If I am not mistaken, the attributes of the interrupt routines may 
affect memory usage. I have some vague memory of having problems unless 
I marked the routines in a particular way.

Sorry for not being more helpful at the moment.

/B

**Comment by haarislabs** [comment]
Hi Bjorn,
I didn't get any time on experimenting it, but I'm definitely on it from today. I'll do as you told me to do meanwhile can you share the IDE version on which your library was tested and developed for.

**Comment by devyte** [comment]
Closing in favor of #5226 .

**Pull request closed without merging**
