### PR TITLE
Add Mercury 1.0 to boards

### PR DESCRIPTION
**Pull request by raliotech**
Mercury is a new Board introduced by Ralio Technologies.

Based on ESP8266
Support onboard 2x brushed dc motor driver (1A per channel)
Support onboard 4x direct servo (3 pin connections
Support onboard 1x direct Ultrasonic sensor (4 pin) connection
Support onboard 2x direct Infra Red sensor (3 pin) connection
VCC pin support up to 12V
Onboard 5V and 3v3 pins
Mercury_1 0_RalioTech

### CODE REVIEW

**Comment by raliotech** [comment]
Hello @mcspr 
Can you guide through the next steps to merge this into main line? Thank you.

Please correct me if I am wrong, this board will be available in next version release #3.1.3 correct?

**Comment by mcspr** [comment]
That is it, pretty much. Boards.rst had to be updated, but you were faster.

> Please correct me if I am wrong, this board will be available in next version release 3.1.3 correct?

Right. For now, in the queue. Hopefully to be merged this or the next week

**Comment by raliotech** [comment]
Hi @mcspr 
Is there a way I can contact you personally, over email or something? I need some help creating these kind of packages for my company. It would be great to get some help in this matter. Thank you.

**Comment by mcspr** [comment]
> Is there a way I can contact you personally, over email or something? I need some help creating these kind of packages for my company. It would be great to get some help in this matter. Thank you.

Email should be on the profile page -> https://github.com/mcspr

**Pull request merged**
