### PR TITLE
Add boot loader compatible speed of 74880 to serial

### PR DESCRIPTION
**Pull request by Chris--A**
This would be handy for those of us who wish to see the boot loader information in the IDE.

### CODE REVIEW

**Comment by probonopd** [comment]
I guess now that we use the Board Manager to install ESP8266 support to the official arduino.cc IDE builds, this patch probably would need to go to https://github.com/arduino/Arduino in order to be useful.

**Comment by Chris--A** [comment]
Yeah, I can create a merge from this.

**Comment by Chris--A** [comment]
I have created a new PR for it here: https://github.com/arduino/Arduino/pull/3389

**Comment by Chris--A** [comment]
@probonopd 
This is now merged into the Arduino IDE. It'll be available in 1.6.6 or in the hourly builds (give it  a few hours :wink:)

**Comment by probonopd** [comment]
Wow, I am really thankful that this has been accepted into the Arduino IDE. It shows that arduino.cc/Genuino really is willing to add support for 3rd party hardware platforms, something I welcome very much.

**Pull request merged**
