### PR TITLE
Added heltec wifi kit 8

### PR DESCRIPTION
**Pull request by 9a4gl**
This one goes together with https://github.com/platformio/platform-espressif8266/pull/67

### CODE REVIEW

**Comment by d-a-v** [comment]
As this would be certainly useful for platformio, this PR lacks consistency in the core repo, as this is a variant with no matching board.
Would you provide more information on this ?

**Comment by d-a-v** [comment]
@ivankravets @9a4gl Is this core issue still relevant ?

**Comment by 9a4gl** [comment]
> @ivankravets @9a4gl Is this core issue still relevant ?

I have no idea what core has and should be. I just provided what was missing to be able to select that board. It was almost 1 year ago, in meanwhile I do not use that board anymore.

**Comment by ivankravets** [comment]
We have this board in our registry and it uses ["variant": "d1_mini"](https://github.com/platformio/platform-espressif8266/blob/develop/boards/heltec_wifi_kit_8.json#L10).

If this board is not compatible with `d1_mini` variant, the new variant should be provided.

**Pull request closed without merging**
