### PR TITLE
Add docs for Adafruit Feather HUZZAH ESP8266

### PR DESCRIPTION
**Pull request by nrobinson2000**
Adafruit Feather HUZZAH ESP8266 (ESP-12S)
-----------------------------------------

The Adafruit Feather HUZZAH ESP8266 is an Arduino-compatible Wi-Fi development board powered by Ai-Thinker's ESP-12S, clocked at 80 MHz at 3.3V logic. A SiLabs CP2104 USB-Serial chip is included so that you can upload code at 921600 baud for fast development time. It also has auto-reset so no noodling with pins and reset button pressings. A 3.7V Lithium polymer battery connector is included, making it ideal for portable projects. The Adafruit Feather HUZZAH ESP8266 will automatically recharge a connected battery when USB power is available.

Product page: https://www.adafruit.com/product/2821

### CODE REVIEW

**Comment by nrobinson2000** [comment]
Is there any reason why this hasn’t been merged yet?

**Comment by igrr** [comment]
Can we please keep it easy on "high-quality", "blistering", and so on? Otherwise LGTM, good addition.

**Comment by nrobinson2000** [comment]
I adapted this text from the product page, and Adafruit tends to use that kind of diction when describing its own products. I’m open to any modifications.

**Comment by d-a-v** [comment]
@nrobinson. Your yesterday's text is now in tools/boards.txt.py, try
```
./tools/boards.txt.py --doc
```
@igrr in the generator PR I only pushed boards.txt, not the rest so It can be double checked.
For instance with this Huzzah PR, what needs now to be done is:
```
./tools/boards.txt.py --docgen
```
and (double check then) commit the newly generated ```doc/boards.rst```.

If there is any modification to make, it should be done in ```./tools/boards.txt.py``` first.
Then both could be commited together I guess.

**Comment by d-a-v** [comment]
@nrobinson2000 your changes are merged ([link](https://github.com/esp8266/Arduino/blob/master/doc/boards.rst#adafruit-feather-huzzah-esp8266)).
Blistering is still there, and the generator is open for fixes.

**Pull request closed without merging**
