### PR TITLE
Update SPISlave_SafeMaster.ino

### PR DESCRIPTION
**Pull request by zharmand**
Modified some comments. ESP work as master in this example, so the device connected to it is a SPI slave.

### CODE REVIEW

**Comment by jandrassy** [comment]
wrong. 
the example is code for the master Arduino if ESP8266 is slave. the problem is that the esp8266 SS pin io 15 must by LOW at boot, but HIGH for esp8266 as SPI slave.

**Comment by zharmand** [comment]
en...  So ESP works as slave in this example. Is it right? If so , the line 106 at this file maybe need be modified as sending message to master? This is the place mislead me :

void setup() {
  Serial.begin(115200);
  SPI.begin();
  esp.begin();
  delay(1000);
  send("Hello Slave!");       // line 106, changed to: send("Hello Master!");
}

**Comment by jandrassy** [comment]
esp is the slave but the example runs in master Arduino.

**Comment by JiriBilek** [comment]
Compile and load https://github.com/esp8266/Arduino/blob/master/libraries/SPISlave/examples/SPISlave_SafeMaster/SPISlave_SafeMaster.ino to Arduino.
Connect it to ESP8266 and compile and load to ESP8266 https://github.com/esp8266/Arduino/blob/master/libraries/SPISlave/examples/SPISlave_Test/SPISlave_Test.ino
That's all :)

**Comment by zharmand** [comment]
> 
> 
> esp8266 is the slave but the example runs in master Arduino.

I've got it. Thank you!

**Comment by zharmand** [comment]
> 
> 
> Compile and load https://github.com/esp8266/Arduino/blob/master/libraries/SPISlave/examples/SPISlave_SafeMaster/SPISlave_SafeMaster.ino to Arduino.
> Connect it to ESP8266 and compile and load to ESP8266 https://github.com/esp8266/Arduino/blob/master/libraries/SPISlave/examples/SPISlave_Test/SPISlave_Test.ino
> That's all :)

Thank you!

**Pull request closed without merging**
