### PR TITLE
open source lwip2

### PR DESCRIPTION
**Pull request by d-a-v**
PLEASE check #3362 out instead

----------------------------------------------

* builder downloads original sources
* precompiled version included
* optionally selectable in arduino IDE menus
* legacy lwip selected by default

### CODE REVIEW

**Comment by igrr** [comment]
Thanks for the PR! I haven't yet had time to review and test it, however I have one question: why do we want to keep old lwIP version around? I.e. why did you choose to add it side by side with the old one instead of replacing?

**Comment by d-a-v** [comment]
My humble opinion states that it is early for total and definitive lwip replacement :)
Further testing is needed because so many things rely on lwip (I alone did not cover all libraries using udp/tcp/...).

The current PR sets current-lwip-v1.4 as the default version. What could be done is to set v2 as the default version, leaving v1.4 still available just in case, at least for a little while.

**Comment by d-a-v** [comment]
Also, for lwip-v2 to compile, a great deal of lwip-v1.4-include-files.h are needed (because of blobary-structures bindings).

**Comment by d-a-v** [comment]
now works with #3001 (sntp was missing)

**Comment by devyte** [comment]
hi, what's the status of this?

**Comment by d-a-v** [comment]
Hi,

@igrr (and I) prefer [waiting](https://github.com/esp8266/Arduino/pull/3001#issuecomment-309630622) for release 2.4.

I would like to mention here that I made a new pull request (#3362) for open source lwIP. Its code is updated but above all the integration is different: it uses submodule. Discussion is needed before I close here.

**Comment by d-a-v** [comment]
closing in favour of #3783

**Pull request closed without merging**
