### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Testato**
added optional development branch .json link

### CODE REVIEW

**Comment by Imroy** [comment]
Starting a sentence with "Is there..." sounds like a question. I think you meant "There is...".

**Comment by Testato** [comment]
Thanks, changed.

**Comment by igrr** [comment]
Just to let you know, I'm doing a rewrite of documentation so it could be stored outside of Github for the released versions: https://github.com/esp8266/Arduino/tree/doc-update
The changes include staging link as well.

**Comment by igrr** [comment]
Added relevant links to readme, thanks.

**Pull request closed without merging**
