### PR TITLE
mDNS: restriction to a single interface

### PR DESCRIPTION
**Pull request by d-a-v**
Default interface is STA (or AP if available and STA is unavailable).
An interface can also be specified in `::begin()` by its IP address.
MDNS will not cross interfaces (there is currently no notion of "bridged interfaces")

Multiple instances should be working, this is not tested in this commit.

### CODE REVIEW

**Comment by d-a-v** [comment]
@LaborEtArs @hreintke 

Should fix #5711

**Comment by Lan-Hekary** [comment]
The Issue #5915 is resolved by this PR 
Also .. this kinda of Eliminate the Solution in this PR #5894
but sadly .. the original issue in #5866 is Back ..
esp8266.local .. works only in WIFI_AP_STA mode or WIFI_STA mode ... But NOT in WIFI_AP mode ..

**Comment by ramiws** [comment]
> Default interface is STA (or AP if available and STA is unavailable).
> An interface can also be specified in `::begin()` by its IP address.
> MDNS will not cross interfaces (there is currently no notion of "bridged interfaces")
> 
> Multiple instances should be working, this is not tested in this commit.

 Multiple instances are not working... so we end up with no way for AP and STA working at the same time.

**Comment by d-a-v** [comment]
@ramiws check #7213

**Pull request merged**
