### PR TITLE
platform.txt: instruct GCC to perform more aggressive optimization

### PR DESCRIPTION
**Pull request by jjsuwa-sys3175**
* add `-free -fipa-pta` to GCC options (generates a bit smaller binary)

* cosmetics

see https://github.com/arendst/Tasmota/pull/9749 and https://github.com/arendst/Tasmota/commit/e7cff928eef1f875819430f98e2b896b16b05b9b.

### CODE REVIEW

**Review by d-a-v — APPROVED** [review]
LGTM

**Comment by d-a-v** [comment]
gcc describes `-fipa-pta` option as
>        -fipa-pta
>           Perform interprocedural pointer analysis and interprocedural modification and
>           reference analysis.  This option can cause excessive memory and compile-time
>           usage on large compilation units.  It is not enabled by default at any
>           optimization level.

(as @earlephilhower pointed it)

IHere's the numbers with arduino-cli and FSBrowser on my host:
Without:
```
Executable segment sizes:
ICACHE : 16384           - flash instruction cache 
IROM   : 327952          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 29388   / 49152 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1300  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 2068  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 27584 )         - zeroed variables      (global, static) in RAM/HEAP 
Sketch uses 360708 bytes (34%) of program storage space. Maximum is 1044464 bytes.
Global variables use 30952 bytes (37%) of dynamic memory, leaving 50968 bytes for local variables. Maximum is 81920 bytes.
real    0m51.596s
user    1m44.004s
sys     0m9.164s
```
With:
```
Executable segment sizes:
ICACHE : 16384           - flash instruction cache 
IROM   : 327920          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 29384   / 49152 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1300  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 2068  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 27584 )         - zeroed variables      (global, static) in RAM/HEAP 
Sketch uses 360672 bytes (34%) of program storage space. Maximum is 1044464 bytes.
Global variables use 30952 bytes (37%) of dynamic memory, leaving 50968 bytes for local variables. Maximum is 81920 bytes.
real    0m50.575s
user    1m43.626s
sys     0m9.216s
```
What are the benefits when compiling Tasmota @jjsuwa-sys3175 @Jason2866 ?

**Comment by jjsuwa-sys3175** [comment]
> What are the benefits when compiling Tasmota @jjsuwa-sys3175 @Jason2866 ?

generally improving compiled output, of course not limited to Tasmota.
(arendst/Tasmota@e7cff92 reported that it saved a few tens of bytes)
```
-IROM   : 327952          - code in flash         (default or ICACHE_FLASH_ATTR) 
-IRAM   : 29388   / 49152 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
+IROM   : 327920          - code in flash         (default or ICACHE_FLASH_ATTR) 
+IRAM   : 29384   / 49152 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
```
it seems IROM/IRAM savings to me, don't it?

**Comment by earlephilhower** [comment]
32 bytes over an entire 320K app is not a worthwhile optimization IMHO, especially if the compiler might need lots more memory or run slower as mentioned by the man pages.  Not everyone is building on a top-spec box.

**Comment by jjsuwa-sys3175** [comment]
from GCC manpage:
> This option can cause excessive memory and compile-time usage on large compilation units.

just exaggerated expression :) on my 10-years-old laptop PC, there is almost no difference. so to speak, both are slow likewise. and of course, most arduino users don't write so "large" (as GCC is called) sketches.

**Comment by earlephilhower** [comment]
> i guess that smallness regarding the executable binaries is virtue, especially in embedded systems.

I tried an example that I thought might show some better results, BearSSL_Validation.

On the one hand, this has a lot of smaller functions both inside the .A and the WiFi core, so gives more chance for savings.  On the other hand, it uses virtuals (both c++ and emulated C) which means that inter-procedure analysis can't be done since you don't know at build-time what code will be called.

Results are as follows:

## master
````
IROM | 364600
IRAM | 27392
DATA | 1356
RODATA | 3844
BSS | 25640
````
##With this patch
````
IROM | 364488
IRAM | 27396
DATA | 1356
RODATA | 3832
BSS | 25640
````
112-4 byte savings (IRAM 4 bytes bigger)
##Rebuilding BearSSL .a with same settings + this patch
````
IROM | 364424
IRAM | 27396
DATA | 1356
RODATA | 3832
BSS | 25640
````
176-4 byte savings (IRAM again is 4 bytes larger w/the patch).

I'm running a 1st gen Xeon E5 system and I didn't notice any time difference in builds, FWIW.

So, @jjsuwa-sys3175 , I'll approve this and add it to BearSSL's build.  We'll update the versionj when Newlib 4.0 comes in #7708.

**Review by earlephilhower — APPROVED** [review]

**Comment by jjsuwa-sys3175** [comment]
> 176-4 byte savings

nice saveings, despite without any code modification :)

> (IRAM again is 4 bytes larger w/the patch).

RODATA; 3844 -> 3832 :)

**Comment by valeros** [comment]
Hi @jjsuwa-sys3175 @earlephilhower  ! Sorry to bring it back, but is there any reason why these flags weren't added to the PlatformIO build script?

**Comment by earlephilhower** [comment]
@valeros I think it was just an oversight.  Can you open an issue on it to track for 3.0.1?  Closed PRs don't get much visibility.

**Pull request merged**
