### PR TITLE
Adding custom buffer_length using I2C_BUFFER_LENGTH

### PR DESCRIPTION
**Pull request by Maelstrom96**
New PR that expands on https://github.com/esp8266/Arduino/pull/8388.

Changed it so it's the same setting name (`I2C_BUFFER_LENGTH`) on both ESP8266 and ESP32 Wire library.

### CODE REVIEW

**Review by d-a-v — APPROVED** [review]
Approving.
As mentioned in the other closed PR, rx/txBufferIndex and rx/txBufferLength should be made into 16 or 32 bits. I guess this will be for another PR.

**Comment by d-a-v** [comment]
If you are running with linux or wsl2, there's the `tests/restyle.sh` script that will do the reformatting for you.

**Comment by Maelstrom96** [comment]
The style should match what it's expecting now - Also merged changes from master.

**Comment by Maelstrom96** [comment]
Missing anything in order for this to get merged?

**Pull request merged**
