### PR TITLE
Update core_esp8266_wiring_analog.c

### PR DESCRIPTION
**Pull request by Testato**
analogRead bugfix discussed here:
https://github.com/esp8266/Arduino/issues/338

### CODE REVIEW

**Comment by me-no-dev** [comment]
Maybe here is the place to actually use analogReference and make it switch between vdd and tout.
And even if it does nothing, analogReference should stay for compatibility, and good point on the missing arguments!

**Comment by me-no-dev** [comment]
Also to point out, system_get_vdd33 does return a good clean analog reading of the TOUT pin. The fact that you needed to change it needs resolving, because changing it here will break it for me, so needs to e made to work properly in a different way.

**Comment by Testato** [comment]
@me-no-dev  but, like i described befoure the TOUT can be used for only one think, VDD mesaurement OR analogRead. The way for choose this is changing and uploading the init bin file whit the right value on it (33 for analogread and 255 for VddRead).
But this core actually do not support this function.
So if on the ESPboard is uploaded from factory the init bin file whit the AnalogRead function active, we cannot use system_get_vdd33. 

My pullrequest is only for analogRead problem, and it work. Only after the init bin file uploading function added to this core we can have a good readVdd function.

For the analogReference also is there two way that we can choose, whitout the argument it is unusefull, so what you prefer ? I prefer have an error during compilation instead of a good compilation but no clear/working analogReference function.

**Comment by Testato** [comment]
@me-no-dev 
you write: "system_get_vdd33 does return a good clean analog reading of the TOUT pin"

This is a common error, the official SDK documentation is clear, the system_get_vdd33 does NOT return the analog read on TOUT. 
system_get_vdd33 must return the value on power pin 3 and 4, and in this case the TOUT pin 17 must be floating
I posted the official API explanation of system_get_vdd33 and system_adc_read

**Comment by Links2004** [comment]
will this not work for the init bin problem?
https://github.com/esp8266/Arduino/commit/1803f3052afed566c2698110aa5b447e628bc924#diff-3776add87f5c7f96ac02b7fbfef5305aR204

**Comment by Testato** [comment]
This is good, so igrr start to work on probkem :-)
If you look at 107th byte you have what i writed many more. This byte is at 33, so the Tout pin will be used ONLY for analog read.
We need another PHY setting whit 255, and Tout pin floating, for the vdd supply read.

But for now the init bin file is not uploaded, so we must wait fir this to work

**Comment by igrr** [comment]
With the change in 1803f30 it is not necessary to upload the init bin file. Init data is created in code and passed directly to PHY init function. What you have in flash no longer matters.

**Comment by Testato** [comment]
ok this is very good.
So for the analogread vs vddread how we can pass the 33/255 value to vdd33_const (107th byte of PHY init function ?)

**Pull request merged**
