### PR TITLE
platform.txt - to work as referred package

### PR DESCRIPTION
**Pull request by jandrassy**
{build.core.path} used instead of {runtime.platform.path} to work as
referred package for Arduino 3rd-party-Hardware-specification chapter
["Referencing another core, variant or tool"](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification#referencing-another-core-variant-or-tool)

solving https://github.com/esp8266/Arduino/issues/5769

note: the keys removed at release are unchanged. referring the package in dev setup doesn't work

comment: This will allow end users to define preferred sets of boards settings ([example](https://github.com/jandrassy/my_boards)) and manufacturers of esp8266 boards could create 'satellite' board packages using core and tools of this main esp8266 package.

### CODE REVIEW

**Comment by jandrassy** [comment]
after https://github.com/esp8266/Arduino/commit/9790e1cb7cfa01ac74056fb835e6282af123aba0 it is unclear which lines will stay in platform.txt after release

**Comment by d-a-v** [comment]
I fixed conflicts by hand. You need to check whether it still works as referred package.
You will also need to `git submodule update --init`

**Comment by jandrassy** [comment]
I left `{runtime.platform.path}` in the lines that are removed at release. the `runtime.tools.*` work with `{build.core.path}` too, but the `tools.*` don't.
one of the `runtime.tools.*`, the `signing.py` stayed in release in 2.5.0, so I changed the path for it to `{build.core.path}` 
it is unclear know, I think, which of the `runtime.tools.*` will stay for release, so we can simply use `{build.core.path}` in all `runtime.tools.*`
I will see if I can test it by making a fake release installation. Before I tested it on 2.5.0 release.

**Comment by jandrassy** [comment]
some entries (`tools.^`) don't work in dev 'mode' with `{build.core.path}/../..`, but need it after installation to work as referred package. most prominent problematic entry is
```
tools.esptool.upload.pattern="{cmd}" "{runtime.platform.path}/tools/upload.py" "{runtime.platform.path}/tools/pyserial" "{runtime.platform.path}/tools/esptool/esptool.py" --chip esp8266 --port "{serial.port}" --baud "{upload.speed}" "{upload.verbose}" {upload.erase_cmd} --end  --chip esp8266 --port "{serial.port}" --baud "{upload.speed}" "{upload.verbose}" write_flash 0x0 "{build.path}/{build.project_name}.bin" --end
```
I don't know what to do with it? It looks like it is not a problem of the changes, but I missed something as I tested it before. It looks like I must close this for know.

**Comment by d-a-v** [comment]
Serial upload with windows was broken, and has just been fixed (#5796).
Maybe you can retry with your changes.

**Comment by jandrassy** [comment]
> Serial upload with windows was broken, and has just been fixed (#5796).
> Maybe you can retry with your changes.
I am on Linux. Things worked in git version only not as referred package.

**Comment by devyte** [comment]
@jandrassy please make your proposal in a PR, or update #5770. We can discuss further there.

**Pull request closed without merging**
