### PR TITLE
add support for TXT records in query responses

### PR DESCRIPTION
**Pull request by mblythe86**
Needed this functionality for a project I'm working on, figured I'd contribute it back.

Not sure whether all of the txt record accessor functions are necessary...I'll let you folks be the judge.

### CODE REVIEW

**Comment by igrr** [comment]
@me-no-dev if you can spare a bit of time to take a look at this, that would be great!

**Comment by philbowles** [comment]
Perfect Timing, this is EXACTLY what I need for my latest: to allow my IOT H/W to autoconfigure. However, I think you may have a bug in there...

So - I'm a bit of a newbie with github and how it works, so be kind...anyway I grabbed your .h and .cpp files and replaced the standard implemetation and recompiled after adding #define MDNS_DEBUG RX

I have a NODE-RED bonjour announcement on "_toiiot._tcp" it has two TXT records, "basename":"lapique","version":"1.0" which are seen by bonjour browser etc they are there!

I tried using the snippet from your example which iterates over the TXT by index,  but no joy. It appears that the txt String pointers are null. 

OTOH "by keyword" works fine. So I'm verry happy and shall continue with that method, as its what I wanted anyway, and it works for me, but I thought youd like to know. Many thanks for this, it has saved me days of probable late nights and swearing!

The failing code:

```

    Serial.print("\nConnected to ");
    Serial.print(WiFi.gatewayIP());
    Serial.print(" as ");
    Serial.println(WiFi.localIP());
//
// find mqtt host
    int n=MDNS.queryService("toiiot", "tcp");
    if(n==1){ //all ok
      Serial.print("Chez ToiioT Controller: ");
      Serial.println(MDNS.hostname(0));
      Serial.println(MDNS.IP(0));
      Serial.println(MDNS.port(0));
      // now get basename etc:
      Serial.print("USING MBLYTHE86 'fork' of mDNS");

      int num = MDNS.numTxt(0);
      Serial.print("  nTXT=");
      Serial.println(num);
      Serial.println("by keyword works");
      Serial.println(MDNS.txt(0,"basename"));
      Serial.println(MDNS.txt(0,"version"));
      Serial.println("by index doesn't");
      Serial.println(MDNS.txt(0,0));
      Serial.println(MDNS.txt(0,1));
      Serial.println("String ptrs  are null");
      Serial.printf(" 0: %s ?\n",MDNS.txt(0,0).c_str());
      Serial.printf(" 1: %s ?\n",MDNS.txt(0,1).c_str());
     int i=0;
     
        for(int j=0; j < num; j++){
          Serial.printf("%d ",j);
          Serial.println(MDNS.txt(i,j));
          }
        Serial.println("  ENDTXT");
```      

And the ouput:

.....MDNS listening
 
Reading answers RX: REQ, ID:0, Q:0, A:5, NS:0, ADD:0
 7 _toiiot
found matching service: toiiot
 4 _tcp
 5 local
type: 000c rdlength: 40
PTR 40 %Chez ToiioT controller on raspberrypi⸮
type: 0010 rdlength: 29
 16:62 61 73 65 6e 61 6d 65 3d 6c 61 70 69 71 75 65 
basename=lapique
 11:76 65 72 73 69 6f 6e 3d 31 2e 30 
version=1.0
type: 0021 rdlength: 20
SRV 11 72 61 73 70 62 65 72 72 79 70 69 
raspberrypi
type: 001c rdlength: 16
Ignoring unsupported type 8d
type: 0001 rdlength: 4
All answers parsed, adding to _answers list..
Chez ToiioT Controller: raspberrypi
192.168.1.4
1880
USING MBLYTHE86 'fork' of mDNS  nTXT=2
by keyword works
lapique
1.0
by index doesn't


String ptrs  are null
 0: <null> ?
 1: <null> ?
0 
1 
  ENDTXT

**Comment by mblythe86** [comment]
Oops! I forgot to "return" in the default case of one of my functions.  I'll fix that and update the pull request soon-ish.

**Comment by mblythe86** [comment]
I'm still having problems when I use this library with my changes...based on some debugging print statements I've added, I have a memory leak somewhere.  I'll need to chase it down.

**Comment by mblythe86** [comment]
ok, should be good now!

**Comment by beegee-tokyo** [comment]
Hope this gets merged soon. I need this functionality as well.

**Comment by horihiro** [comment]
When will be this feature released?

I hope to use this soon.

**Comment by horihiro** [comment]
I hope that this PR will be merged in [2.4.2](https://github.com/esp8266/Arduino/milestone/13) ...

**Comment by devyte** [comment]
@mblythe86 could you please resolve the conflicts?

**Comment by devyte** [comment]
Closing in favor of #5384 .

**Pull request closed without merging**
