### PR TITLE
lwIP-v2 ready to use

### PR DESCRIPTION
**Pull request by d-a-v**
boards.txt comes from #3722
lwIP sources are cloned from their origin, currently v2.0.3stable

### CODE REVIEW

**Comment by devyte** [comment]
I'm now very confused with all the lwips flying around. Is there any way to extract the version info from the lib? Something like a #define, or version string, or git commit, or whatever, that can get printed out? I don't trust what I'm building or linking against anymore.

**Comment by davisonja** [comment]
Worst case md5 is simple

**Comment by d-a-v** [comment]
```
#ifndef LWIP_HASH_STR
#define LWIP_HASH_STR "esp1.4"
#endif
printf("lwIP-%d.%d.%d(%s)",
        LWIP_VERSION_MAJOR, 
        LWIP_VERSION_MINOR,
        LWIP_VERSION_REVISION,
        LWIP_HASH_STR);
```

```LWIP_HASH_STR``` is not defined with lwip1.4

With lwip2, it says: ```lwIP-2.0.3(92f23d6(tag:STABLE-2_0_3_RELEASE))```.
The hash number is the lwip commit ref, with the tag if there's one.

The two previous PR are now closed.

**Comment by d-a-v** [comment]
@devyte @davisonja ```LWIP_VERSION_MAJOR``` is accessible in sketch with ```#include "lwip/init.h"```.
It was already the case with lwip1.4. What do you think should be further done about that ?
@igrr @devyte @davisonja are you OK with the included ```boards.txt``` ?
I have only tested Generic/nodemcu(ESP01), wemos D1R1, D1-mini and D1-mini-lite(with esp8285).

**Comment by igrr** [comment]
boards.txt looks good, but i'll check with nodemcu. Will report back.

**Comment by devyte** [comment]
Be aware that the ESPAsync libs don't seem to build with lwip2.
@me-no-dev at first glance, the changes needed seem minimal, but I didn't go through them in detail.

**Comment by d-a-v** [comment]
@me-no-dev changes probably will be similar as #3129.

**Comment by me-no-dev** [comment]
on it :)

**Comment by devyte** [comment]
@me-no-dev ESPAsyncTCP builds now. Will you also update ESPAsyncUDP? That would allow me to build my application and start testing :)

**Comment by devyte** [comment]
ESP8266LLMNR lib doesn't seem to build due to differences in UdpContext signatures

**Comment by reaper7** [comment]
@devyte - ESPAsyncUDP also updated, works for me with LWIPv2

**Pull request merged**
