### PR TITLE
Allow setting alternate TX for UART 0, so GPIO1 is available as SPI_CS1

### PR DESCRIPTION
**Pull request by KaloNK**
Second attempt after fixing my local branch mess

### CODE REVIEW

**Comment by igrr** [comment]
Copying my comment from the other pull request:

Could you please change the bool alternate_tx parameter to an explicit pin number? As it is, it's pretty hard to tell which one is 'alternate'. 
My suggestion would be to introduce HardwareSerial::pins(int tx, int rx) which would swap/remap pins as necessary.

**Comment by KaloNK** [comment]
Updated as suggested

**Comment by hallard** [comment]
Hi guys,
this fix seems very interesting for my project, may I have more information on question going to my head. What I understood so far was :
- UART0 (TXD0/RX0) use GPIO1/GPIO3 and can be swapped to GPIO15/GPIO13 (but you swap RX and TX and not only one of them)
- UART1 (TXD1/GPIO2) has only TX out

Now, if all off this is correct, now it seems that we can affect UART0 TX to another pin which is GPIO2 but of course, if we do that, we can't use UART1 TXD1 because it's also GPIO2, correct ?

Now my most interesting one, looking the changes, it seems may be, we can just also disable UART0 TX (or affect it's pin func to "nothing"), which means that I can use GPIO1 as I/O and GPIO2 as TXD1 and GPIO3 as UART0 RX. Since on UART0 for my projects, I don't need TX it will be really a good news because I will get new I/O I'm missing.

Do you think it's doable ?

**Comment by KaloNK** [comment]
Hi,
 you can do this even now without this patch - just set the mode for UART 0 to SERIAL_RX_ONLY on init

**Comment by igrr** [comment]
Thanks!
Would be wonderful if you could add these new methods to reference.md.

**Pull request merged**
