### PR TITLE
remove autogenerated eagle.app.v6.common.ld and git-ignore it

### PR DESCRIPTION
**Pull request by d-a-v**

### CODE REVIEW

**Comment by igrr** [comment]
Let me guess: LD script is not auto-generated when building with platformio?

**Comment by d-a-v** [comment]
well... yes.
@ivankravets could you help with this ?
ref: #4582

**Comment by igrr** [comment]
Paging @ivankravets, please help us with platformio build script!

**Comment by ivankravets** [comment]
@igrr sorry for the delay, I'm on a business trip to the USA now. I'll update build script soon to generate common LD script on the fly.

**Comment by ivankravets** [comment]
@d-a-v could you resolve conflicts or create new PR? All should work now.

**Comment by d-a-v** [comment]
@ivankravets thanks. I puffed this PR.

**Pull request merged**
