### PR TITLE
Update to GCC 10.3 and toolchain rebuild

### LINKED ISSUE #8069: Compilation speed of ESP8266 core 3.0.0
#### Platform

- Hardware:					[ESP-12]
- Core Version:			[3.0.0]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[other]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Higher Bandwidth]
- Reset Method:		[ck]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[160MHz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] 

### Problem Description

I compared the compilation speed
3.0.0 (gcc-xtensa v10.2) - first compilation 10 minutes, second compilation 10 minutes
2.7.4 (gcc-xtensa v4.8) - first compilation 5 minutes, second compilation less than 1 minute

### PR DESCRIPTION
**Pull request by earlephilhower**
Fixes #8069

GCC 10.3 has a patch to stop escaping the initial : in Windows paths which
is causing Arduino and other tools to fail dependency checks and rebuild
everything on every compile.

### CODE REVIEW

**Review by d-a-v — APPROVED** [review]
#8069 is fixed with this PR.
I only tried the windows version through the alpha release installer which includes this PR.
First compilation of `FSBrowser.ino` took 2m12s. Second one took 27s.

**Review by d-a-v — APPROVED** [review]
Linux builds seem to be OK too

**Comment by earlephilhower** [comment]
Thanks for the checks!

**Comment by sh-user** [comment]
@d-a-v I installed the board from the link
version 0.0.2: git: 3.0.0-97-g11e1175c https://dav.github.io/esp8266/Arduino/package_esp8266com_index.json
After installation I see gcc 10.2
C:\Users\Alex1\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.0.0-newlib4.0.0-gnu23-48f7b08\xtensa-lx106-elf\include\c++\10.2.0\

**Comment by d-a-v** [comment]
@sh-user
You should see gcc-10.3
Snapshot and alpha release are not officially supported by arduino and I sometimes see the same issue as you see, or some other times a `java.nullpointer.exception`. 
In this case, what works is to remove `esp8266\` in `C:\Users\name\AppData\Local\Arduino15\Packages\` before installing 0.0.1 or 0.0.2 again.
BTW, a new updated gcc-10.3 version has just landed in alpha release v0.0.2 that I'm about to try with windows.

**Comment by sh-user** [comment]
I deleted the folder `C:\Users\Alex1\AppData\Local\Arduino15\` and reinstalled the Arduino IDE 1.8.13 again

[first-compilation-3.0.0-98-g4f00f3c9.txt](https://github.com/esp8266/Arduino/files/6605162/first-compilation-3.0.0-98-g4f00f3c9.txt)
[second-compilation-3.0.0-98-g4f00f3c9.txt](https://github.com/esp8266/Arduino/files/6605163/second-compilation-3.0.0-98-g4f00f3c9.txt)

**Comment by d-a-v** [comment]
According to your logs @sh-user you installed the version 3.0.0, not 0.0.2 nor 0.0.1
(`3.0.0-newlib4.0.0-gnu23-48f7b08` should be `3.0.3-gcc10.3-9bcba0b`)

**Comment by sh-user** [comment]
@d-a-v sorry, this is my mistake, installed version 3.0.0 instead of 0.0.2, everything works, second compilation 50 seconds!

**Comment by d-a-v** [comment]
Don't forget @sh-user that versions 0.0.1 and 0.0.2 can only receive manual updates.
No notification will come through the arduino IDE for 0.0.1 & 0.0.2, nor the official release channel for 3.0.1 when it is out.

**Pull request merged**
