### PR TITLE
ArduinoOTA library change

### PR DESCRIPTION
**Pull request by NullMedia**
Modified callbacks to allow lambda with capture list.

### CODE REVIEW

**Comment by igrr** [comment]
Thanks for the pull request! Could you please squash and rebase all the changes?

**Comment by NullMedia** [comment]
Oh heck... I'd love to... Um, can I do that on the website? (New to this!)

**Comment by igrr** [comment]
I think you have to use git client to do this, command line or GUI.

**Comment by igrr** [comment]
Also please check the errors in examples:
https://travis-ci.org/esp8266/Arduino/builds/129147394#L770

**Comment by NullMedia** [comment]
Ok, working on it!

**Comment by NullMedia** [comment]
Ok, did I do it right? (sorry!)

**Comment by igrr** [comment]
Not exactly, see [this explanation](http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit) :) If you don't feel like using the command line client, don't bother, I'll squash that myself.
Could you do one more thing please — move definitions of `THandlerFunction` and other callback function types into the body of ArduinoOTAClass? `THandlerFunction` is a pretty common name and it would be good not to put it into global namespace. Thanks.

**Comment by NullMedia** [comment]
Made changes, and think I've merged them now... any further attempts at rebasing just lead to errors... (error: could not apply xxxx). Unfortunately never used git before, learning lots today! Thanks.

**Pull request merged**
