### PR TITLE
Fix the issue #3612 , Updating the SPIFFS to f5e26c4

### PR DESCRIPTION
**Pull request by Lan-Hekary**
the same suggested modification in this pull request https://github.com/igrr/mkspiffs/pull/27

further info in this issue  https://github.com/pellepl/spiffs/issues/165 and the commit https://github.com/pellepl/spiffs/commit/f5e26c4e933189593a71c6b82cda381a7b21e41c

also don't forget to update the mkspiffs release 
I guess this can only be done by you 😃

### CODE REVIEW

**Comment by igrr** [comment]
Thanks for the PR!

To make it easier to follow SPIFFS updates in the future, would you mind adding SPIFFS commit ID to your commit description (e.g. "SPIFFS: update to f5e26c4")?

I will then update this branch by adding new mkspiffs release.

**Comment by Lan-Hekary** [comment]
Done I will Update this PR description too

**Comment by me-no-dev** [comment]
@igrr are you postponing this to be in sync with mkspiffs?

**Comment by igrr** [comment]
Yes, I still need to update package links for mkspiffs, and revert the SPIFFS config option which caused compatibility issues with 2.3.0.

**Comment by Lan-Hekary** [comment]
about SPIFFS config options .. what are the options that are causing the compatibility issues ??

**Comment by igrr** [comment]
According to @me-no-dev it is https://github.com/igrr/mkspiffs/blob/master/spiffs/spiffs_config.h#L202, but it would be nice to test that (i.e. prepare FS with older version, try to read it with the new one).

**Comment by Lan-Hekary** [comment]
OK I got that .. I will test it now 
I am using PlatformIO so it's easy to change between 2.30 and 2.4.0 cores in a line :D 
should I make a pull request if I verified it of leave that to you guys ?

**Comment by me-no-dev** [comment]
I would vote for a separate PR just so it outlines the change, but whatever the boss says :)

**Comment by igrr** [comment]
Well, I didn't mean adding these extra changes to this PR. It can go in as is. Just would make sense to merge all changes (roughly) at the same time, to prevent someone from grabbing non-compatible versions of mkspiffs and arduino-esp8266.

**Comment by Lan-Hekary** [comment]
I tested the changes .. it seems OK and the compatibility  is maintained across the different versions and I tested with various files some of them well above 25k and it's Perfectly OK ..

I will make another pull request in the mkspiffs with the this change ..
but I won't be able to do another PR here because I edited the master branch in my fork 
( I know I should've made a new branch ... I won't make this mistake again :D )

actually I've been meaning to ask .. Do you have a Guide on how to make a proper PRs and mastering git commands ??? sometimes I have difficulties with git in how to manage the remote fork I am making modifications to ..

**Comment by Lan-Hekary** [comment]
@me-no-dev , actually this change is directly related to the issue mentioned in the PR's title
but I will do whatever the boss says :D

**Pull request merged**
