### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by Makuna**
Removed member variables that are not required outside a member call lifetime

### CODE REVIEW

**Comment by Makuna** [comment]
sigh.  I missed the destructor.  New one coming shortly.

**Comment by devyte** [comment]
Just push to your branch and this should get updated. No need for a new PR.

**Comment by Makuna** [comment]
I did push to my branch, but the PRs are not updating.  Even this closed PR is not updated.  what am I missing?

**Comment by devyte** [comment]
Did you make a branch in this repo or in your forked repo?

**Pull request closed without merging**
