### PR TITLE
NACK last byte when read

### PR DESCRIPTION
**Pull request by bbx10**
The TCS34725 RGB color sensor works reliably with this change. See #535 for details.

### CODE REVIEW

**Comment by me-no-dev** [comment]
have you tested this with other i2C devices?

**Comment by bbx10** [comment]
Yes, a [9DOF IMU](http://adafru.it/1714) board which was not working now works with this change and the clock stretch increase (#553). This change might help with the other IMU board (#526).

I will test 4 other i2c devices with this change and #553 tomorrow. 

I am using the following for the i2c protocol reference: 
http://www.nxp.com/documents/user_manual/UM10204.pdf.

Section 3.1.6 talks about 5 conditions for generating NACK. The last one says
> 5. A master-receiver must signal the end of the transfer to the slave transmitter.

This is why the Uno/AVR generates NACK after the last byte read.

**Comment by igrr** [comment]
We used to have this correct long long time ago :)
https://github.com/esp8266/Arduino/blob/7e40b9f11e9035af57248d3d19af50deadeea14c/hardware/esp8266com/esp8266/cores/esp8266/i2c.cpp#L164

I will also test a few more devices myself with this change and #553.

**Comment by bbx10** [comment]
> We used to have this correct long long time ago :)

Thanks, this helps assure me this is a good change. The change affects every i2c read so it has the potential for massive breakage. :(

The 9DOF IMU ran for 3 hours and was still reporting correct values. The i2c chips on board are the L3GD20H and LSM303.

The following other i2c devices work. Only a few minutes testing done per device.
BMP180, HTU21DF, ISL29125, TSL2591, TCS34725

All but the TCS34725 worked even without this change. All testing was done with #553 as well as this change.

**Comment by igrr** [comment]
I have tested this change with MPR121, HMC6352, and one I2C EEPROM (forgot the part name).
All seem to be work fine.

**Pull request merged**
