### PR TITLE
Schematic pin reordering fix

### PR DESCRIPTION
**Pull request by h4rm0n1c**
Reorders Schematic Pins GPIO 4 and 5 so they reflect the module pinout.

This brings the schematics in line with the module pinouts depicted
elsewhere in the documentation.

### CODE REVIEW

**Comment by h4rm0n1c** [comment]
Created in response to
https://github.com/esp8266/Arduino/issues/1587

**Comment by hallard** [comment]
@h4rm0n1c 
thanks for this fix, may be having eagle cad .sch files in the repo also may help other to improve/change and have starting point of quick schematic drawing, just my 2 cents ;-)

**Comment by duncan-a** [comment]
Eagle Components would be very useful if someone has created them...

Rhat brings the total to 4 cents :)

**Comment by h4rm0n1c** [comment]
Most of the libraries I've found have this issue.

However, this is esp8266modules.lbr that I am using for my projects, I only use ESP-12 modules so that's the only part I can verify as being good.

I have used this to make boards, so it's a known good library.

I have modified it to place the GPIOS in the correct order, I also think this is better than newer versions of the library that don't have the off-center solder pads for easy hand soldering.

[esp8266modules.zip](https://github.com/esp8266/Arduino/files/124147/esp8266modules.zip)

**Pull request merged**
