### PR TITLE
fix parseArgument #2

### PR DESCRIPTION
**Pull request by d-a-v**
#5230's twin brother using functors on @devyte's proposal
less available flash (-164B), more available ram (+28B)

### CODE REVIEW

**Comment by ascillato** [comment]
Hi,

Tested the latest commit for esp8266 arduino core (https://github.com/esp8266/Arduino/commit/d742df84e53667b8456e94f70d1f21264b73aecb) and works fine.
So, then I add this PR to that (in my test devices) and also past all the tests.

Now this can be merged without issues.

Please, do ASAP in order to solve the following issues and also Alexa queries.

* Solves issues (Arduino): https://github.com/esp8266/Arduino/issues/4235, https://github.com/esp8266/Arduino/issues/2611
* Solves issues (Sonoff-Tasmota): https://github.com/arendst/Sonoff-Tasmota/issues/1639, https://github.com/arendst/Sonoff-Tasmota/issues/1434
* Solves rebased (Arduino) PRs: https://github.com/esp8266/Arduino/pull/4151, https://github.com/esp8266/Arduino/pull/4236, https://github.com/esp8266/Arduino/pull/4573, https://github.com/esp8266/Arduino/pull/5230
* Solves 4 items in 2.5.0 milestone: https://github.com/esp8266/Arduino/milestone/8

Please, take this PR into account in order to solve all these issues. Thanks.

@reloxx13, @holgerlembke, @jasonharper, @OFreddy, @Monarch73, @arendst, @andrethomas, @Jason2866, @d-a-v, @devyte, @earlephilhower

**Comment by ascillato** [comment]
Thanks a lot to everyone helping with this great software. :+1:

**Comment by Jason2866** [comment]
Tested this commit, working very well with Tasmota, Happy that already merged to master :-)
Now we have actual stable base for Tasmota with all features working used by Tasmota!  

Great Thanks @d-a-v  and all  the other developers doing a great Job!

**Comment by andrethomas** [comment]
Thanks a lot guys, much appreciated!

Compiled staged binaries for Tasmota this morning so now its on to more bug hunting ;)

**Comment by dragondaud** [comment]
This commit breaks form processing in [my project](https://github.com/dragondaud/myClock) and I had to freeze at commit 2eb5b5600a3631cdfb9ddd1150505d82e38f3406 in order to continue functioning. Specifically, in my WebServer.ino, when submitting a POST request none of the expected keys are found in server.hasArg(). Reverting to above mentioned commit restores previous functionality.

**Comment by reloxx13** [comment]
@dragondaud 
https://github.com/esp8266/Arduino/issues/5261

**Comment by dragondaud** [comment]
OK, made a local pull of  5262 and that fixes my problem, hope it gets merged soon.

**Pull request merged**
