### PR TITLE
Uploading files missing mskspiffs

### PR DESCRIPTION
**Pull request by Protoneer**
mkspiffs is needed to make the FS tool work.

### CODE REVIEW

**Comment by igrr** [comment]
Uh, but mkspiffs is installed with the boards manager package, isn't it?

**Comment by Protoneer** [comment]
Mmmm... it might be a Windows path issue. My windows 10 arduino ide is
coming back with "SPIFFS Error: mkspiffs not found!"

Will try it again on my win7 machine next week...

**Comment by Protoneer** [comment]
Tried it again on a Windows 7 machine and gives me the same issue. Even Uninstalled the Arduino IDE and ESPboard definitions with the same result. Where should mskspiffs be located?

I manually copied the exe to my Arduino folder and it seemed to pick it up.(Did not test the complete process yet, as I did not have a board to upload it to yet.)

**Comment by hallard** [comment]
@Protoneer 
I have same issue, would you mind identify what exact folder/subfolder you call your "Arduino Folder" ?

Thank you for your help

**Comment by luc-github** [comment]
On my windows 7 with Arduino IDE 1.6.5 and staging version 1.6.5-1106-g8253b82 which contain mkspiffs.exe, here are the path:
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\tools\mkspiffs\0.1.1\mkspiffs.exe

as mentioned in documentation need to add esp8266fs.jar, here the path:
C:\Users\user\Documents\Arduino\tools\ESP8266FS\tool\esp8266fs.jar

after need to create a data folder in a sketch directory to put all files for upload and use the tool

Hope it help

**Comment by hallard** [comment]
@luc-github 

Ok got it, I'm working with current build but I build IDE from scratch so I did not used the package URL from Arduino IDE. This mean I do not have esp8266 package in Arduino15.
For information I tried
```
ArduinoSketchBookFolder\\hardware\esp8266\esp8266\tools\mkspiffs\mkspiffs.exe
```
and
```
ArduinoSketchBookFolder\\hardware\esp8266\tools\mkspiffs\mkspiffs.exe
```
these two does not work, but your path helped, I've put the .exe file into my build folder
```
D:\arduino-esp8266\build\windows\work\hardware\esp8266com\esp8266\tools\mkspiffs.exe
```
and this one works ;-)

thanks for your help

**Comment by hallard** [comment]
Guys,
Just to let you know that each rebuild delete the file from 
`D:\arduino-esp8266\build\windows\work\hardware\esp8266com\esp8266\tools`
whick makes sense, but I need to download back tool each time. Would it be possible to include the mkispiffs.exe into the build and put it with others tools like esptool.exe and espota.py ?
thanks

**Pull request closed without merging**
