### PR TITLE
SNTP: backport espressif sntp api for lwip2

### LINKED ISSUE #7092: After Stage merge #6993 I lost sntp functionality
Using Tasmota on Arduino core stage after merge #6993 I lost sntp functionality and compilation fails with Undefined References to the once documented SNTP API calls by espressif:

- sntp_get_real_time
- sntp_get_current_timestamp
- sntp_set_timezone

I guess some functionality has been dropped...

For sntp_get_real_time I'll make a workaround saving 1k code space anyway. The others still break compilation

### PR DESCRIPTION
**Pull request by d-a-v**
@arendst Can you try it ?

fixes #7092

### CODE REVIEW

**Comment by arendst** [comment]
Thx.

Solves my issue indeed.

**Comment by Jason2866** [comment]
Any idea why the code size for Tasmota increases from core v.2.6.1 to feature stage from
568k to 576k ?

**Comment by d-a-v** [comment]
@Jason2866 More details are needed. Did you try 2.6.3 ? Can you open a new issue to track these regressions ?

**Comment by Jason2866** [comment]
@d-a-v  will do if have more tested and info collected.
So far i have tested Tasmota does work until commit https://github.com/esp8266/Arduino/commit/e752e96e9fd63436b689aa3e6cb3010f27b55aae
Is this info enough? If yes i open a issue.

**Comment by Jason2866** [comment]
@d-a-v  opened issue #7103. Found the PR which generates the problems

**Pull request merged**
