### PR TITLE
Copy the existing flash mode over the one set in an OTA update image.

### PR DESCRIPTION
**Pull request by teejaydub**
Suggest fix for #4876: tolerate different flash modes in OTA update images and convert them to match what the module is currently using.

Allows the flash mode to be ignored during OTA, so the same binary image can be used for both modules that support QIO and those that require DIO.

### CODE REVIEW

**Comment by devyte** [comment]
I'm ok with this.
@igrr any thoughts on this one?

**Comment by teejaydub** [comment]
Thanks, guys, I appreciate it!

**Comment by robertpoll** [comment]
Hi. This change has caused some issues for us so just wanted to discuss. We buy modules from AI-Thinker with a simple loader firmware that we've written loaded by them when they manufacture the modules. Once they are assembled into our product the loader firmware gets a certificate, stores in SPIFFS and then does an OTA update to load the real firmware. The problem is that AI-Thinker is insisting that the firmware they load is DOUT, but our final firmware is QIO. Obviously this change means our final firmware runs DOUT. 

I think the change is a good one but was wondering whether an override option would be a sensible addition for people in our position (which I would assume would affect quite a few people)?

**Comment by teejaydub** [comment]
Good to know - two clearly valuable use cases that need opposite behavior. So, it could be on a compile-time switch.

Although it seems like the underlying bug might be that AI-Thinker is incorrectly labeling your firmware as DOUT when it's QIO, right? But you still need a stopgap solution for any existing modules in inventory.

**Pull request merged**
