### PR TITLE
Add functional callbacks to ticker

### PR DESCRIPTION
**Pull request by hreintke**
This PR adds functional callbacks to the Ticker class.
It is fully backward compatible.

I only did limited testing. 
I you agree to the way of implementing I will test all options to finalize.

### CODE REVIEW

**Comment by devyte** [comment]
@hreintke this PR looks sort of messed up. Could you please update it, or close it and make a new one?

**Comment by hreintke** [comment]
OK, will do.

I'll keep this one open until I PR the new version.
Do you want this functional callback as single feature or should I also include the "scheduled_function" in one go.

**Comment by igrr** [comment]
I think that callback_t can be implicitly converted into std:: function<void(void)>. Maybe you could also remove the existing callback_t overload?

**Comment by hreintke** [comment]
OK will be included

**Comment by devyte** [comment]
@hreintke is this PR still valid, or is it superseded by #4209 ?

**Comment by hreintke** [comment]
@devyte This PR is indeed superseded by #4209.
I had (have) trouble getting rebase to work, that is why I made a new PR.

**Comment by devyte** [comment]
Thanks!

**Pull request closed without merging**
