### PR TITLE
ESP8266WiFi examples - 'traditional' WiFiWebClient example

### PR DESCRIPTION
**Pull request by JAndrassy**
some commits last year modified the WiFiClient example to a non HTTP example.

The (WiFi)WebClient example started in Arduino Ethernet library and most Arduino networking libraries have some modification of it. I modified the version from WiFiNINA library for ESP8266WiFi and used my favourite test address, the Arduino ASCII logo because it is readable on Serial Monitor.

### CODE REVIEW

**Comment by d-a-v** [comment]
If you are using linux or WSL, you can run the script `tests/restyle.sh` which will solve the CI 'style check' issue.
Also, like in all other examples, you can use this for SSID and PSK:
```
#ifndef STASSID
#define STASSID "your-ssid"
#define STAPSK  "your-password"
#endif

const char* ssid = STASSID;
const char* pass = STAPSK;
```

**Comment by jandrassy** [comment]
@d-a-v, I changed the ssid and pass definition and run the restyle (it changed only spaces in the header comment)

**Comment by jandrassy** [comment]
and the HTTPSRequest example?

**Comment by earlephilhower** [comment]
Good point!  Probably worth reworking to a TLS web service and not HTTP.  Or using the HTTP requester with a HTTPS client, but I *think* we already have one of those.

**Pull request closed without merging**
