### PR TITLE
Add Uri with support for regexUri and globUri

### PR DESCRIPTION
**Pull request by Bmooij**
Add support for regex uri and glob uri.
This pull request is a combination of:
https://github.com/esp8266/Arduino/pull/5214
https://github.com/esp8266/Arduino/pull/5467

There is an issue when importing `<regex>`

### CODE REVIEW

**Comment by Bmooij** [comment]
BTW it is not tested on a real device, because I don't own an esp8266

**Comment by d-a-v** [comment]
@Bmooij How did you test it if not on real esp8266 ?
Do you know you can test that kind of code on your dev computer using emulation on host (`cd tests/host/; make`) ?

**Comment by Bmooij** [comment]
I tested a similar implement on my [esp32](https://github.com/Bmooij/arduino-esp32/commit/72613b5f6d896b72964344b24382c1b6fd36c9c1)

**Comment by devyte** [comment]
@Bmooij there seem to be some warnings (unused params)

**Comment by devyte** [comment]
Fixes #2019

**Comment by Bmooij** [comment]
There is an issue when using the regex lib for esp8266
See: https://github.com/esp8266/Arduino/issues/6952

**Comment by Bmooij** [comment]
I replaced the `<regex>` lib, with `<regex.h>` because it crashes and it has limitations. See https://github.com/esp8266/Arduino/issues/6198#issuecomment-509847266

I tested it with an esp8266

**Pull request merged**
