### PR TITLE
add magic byte check for Update class

### PR DESCRIPTION
**Pull request by Links2004**
Note: only check of first 0xE9 possible.

### CODE REVIEW

**Comment by igrr** [comment]
Is this going to break the case when `_command == U_SPIFFS`?

**Comment by Links2004** [comment]
good point will change.

**Comment by Links2004** [comment]
has the SPIFFS also a magic byte at the start?

**Comment by igrr** [comment]
It has, but i think hard-coding this into Updater.cpp is not really good. It might be better to move that logic into some "Verifier" (i.e. MD5Verifier, SketchVerifier, SPIFFSVerifier, etc.)

**Comment by igrr** [comment]
For SPIFFS the magic is not located at the start of the image:
https://github.com/esp8266/Arduino/blob/342c4ae6fb847bfc787f80b89a2bb888d942dc32/cores/esp8266/spiffs/spiffs_nucleus.h#L201

**Comment by Links2004** [comment]
a verify at the beginning is limited to the first byte, (peek problem).
I solved it for network but make it for Stream class is no good idea since it then brake every lib that uses Streams.

for the sketch a verify at the end is possible since we not have override the working one there,
for the SPIFFS this is not possible.

**Comment by igrr** [comment]
Ok, then I think for SPIFFS we will just use MD5 verification at the end of update.

**Comment by Links2004** [comment]
will do some refactoring, start test for flash first byte,
end test the flash size test like i do in the http update.
moved to two new functions

**Comment by Links2004** [comment]
updated

**Comment by igrr** [comment]
LGTM

**Pull request merged**
