### PR TITLE
WString: make to be safer init state, in order to tolerate (potential) stray dtor calls

### PR DESCRIPTION
**Pull request by jjsuwa**
derived from #7553

### CODE REVIEW

**Review by earlephilhower — CHANGES_REQUESTED** [review]
I don't see how this affects the c'tor/d'tor one way or the other.  It just seems to change the name and inverting the logic for SSO flags.

If that flag itself is not set somewhere before being used in a d'tor, you have to assume it's random.  So, still the 50% chance of trying to `free` something that wasn't allocated.

**Comment by TD-er** [comment]
> potential... (negligible in fact)

Steps to reproduce it...

- Create a struct with several String objects in it.
- Make sure you're running out of memory ;)
- Create such a struct directly by adding it to a std::list using `emplace_back`, preferrably with some constructor values of the struct which will cause a memory allocation fail in one of the first members making sure the latter String members are not properly constructed.
- Try to erase the item from the list. => crash
- Edit your "negligible" statement here ;)

**Comment by earlephilhower** [comment]
@TD-er can you give an MCVE for that, one that fails for you?

Seems straightforward enough (and you can do a `void *unused = malloc(47000);` at the beginning to eat up most RAM and then keep adding strings until there is a failure.  But, again, I think the issue is as likely to be in the `std::list` (which wants to throw an exception on OOM but can't in normal operating mode on the 8266) as in `String`.

**Comment by jjsuwa** [comment]
> Make sure you're running out of memory ;)

post-OOM behavior... virtually impossible to keep heap integrity, should dump so to debug serial and `panic()` if possible.

**Comment by TD-er** [comment]
> > Make sure you're running out of memory ;)
> 
> post-OOM behavior... virtually impossible to keep heap integrity, should dump so to debug serial and `panic()` if possible.

Well I do always check large object allocations whether they return nullptr.
As my sketch is quite often running into almost out of memory situations, it is nice to have those be handled a bit more gracefully than a crash.
But this also means whatever member exists in a class must be able to be destructed regardless whether the class was fully constructed.

**Comment by TD-er** [comment]
> @TD-er can you give an MCVE for that, one that fails for you?
> 
> Seems straightforward enough (and you can do a `void *unused = malloc(47000);` at the beginning to eat up most RAM and then keep adding strings until there is a failure. But, again, I think the issue is as likely to be in the `std::list` (which wants to throw an exception on OOM but can't in normal operating mode on the 8266) as in `String`.

I will try to find some time for it this weekend.

**Comment by jjsuwa** [comment]
> As my sketch is quite often running into almost out of memory situations, it is nice to have those be handled a bit more gracefully than a crash.

post-OOM condition is typical corner-case and thus `malloc()` without nullptr check are so ubiquitous despite of bad manners.
but in your work, is not...

the main interest: is this PR sufficient to resolve your problem?

**Comment by earlephilhower** [comment]
On further inspection, I'm *really* not seeing anything this changes and I'm not seeing how String() could free an invalid pointer and cause a crash like @TD-er is thinking.

My reasoning:

All `String` constructors call `String::init()`:
https://github.com/esp8266/Arduino/blob/a460cb793574dd4b055ef4c409ebc57d6394888f/cores/esp8266/WString.cpp#L131-L135

If the constructor is called with a `nullptr` `this`, that will immediately crash as it is writing values to `NULL`.

So, the only way it doesn't crash is with a valid `this` pointer.  It sets the `isSSO` flag and makes a 0-len string in the structure.

Now on destruction (which cannot ever happen if the c'tor `this` was `nullptr`) we do:
https://github.com/esp8266/Arduino/blob/a460cb793574dd4b055ef4c409ebc57d6394888f/cores/esp8266/WString.cpp#L123-L125
https://github.com/esp8266/Arduino/blob/a460cb793574dd4b055ef4c409ebc57d6394888f/cores/esp8266/WString.cpp#L137-L141

So, we check the `isSSO` flag and potentially free a heap pointer and then do the same as the c'tor (i.e. set some flags which, in this case, are ignored).

So, this PR doesn't change anything or affect the behavior in any way.  And, as far as I can see, the existing behavior is safe and sane.

If memory gets corrupted elsewhere, or the String `this` is corrupted by other code, well yeah it could crash but that's not `String`'s fault or problem and there's nothing we can do about it.

**Comment by jjsuwa** [comment]
thanks for the discussion, this PR is melt back into #7553 and closed.

**Pull request closed without merging**
