### PR TITLE
Add WeMos D1 Mini Pro to supported boards

### PR DESCRIPTION
**Pull request by mcauser**

### CODE REVIEW

**Comment by d-a-v** [comment]
@beicnet boards.txt will be generated by a script #3722. boards.txt in current master is already generated (but to be fixed). d1-mini-pro is already in the generator (not in master) so you can check if it is OK for you. The generator itself is to be merged after 2.4.0.
There are not your other changes (boards.md, filesystems.md, package.json). 
Also about your espduino PR #3098 you just closed, these changes can be integrated in the script, if you are ready to test them.

**Comment by beicnet** [comment]
@d-a-v Okay, the reason why I wanted that, it's because I don't wanna edit boards.txt file every time when new version is released or when I install a new Arduino session onto another computer (already using on 5 different computer), also I closed my PR #3098 because how I see, no one cares for it. Basically the ESPDuino board is useless at this time, because you can't change the board version from default v1 to v2... :(

**Comment by d-a-v** [comment]
@beicnet I understand and I agree. In the meantime, instead of editing it you can just directly download it (link is in #3722 OP, I try to keep it updated on changes). I just pushed your relevant changes for ESPduino.
Please report back if D1-mini-Pro and ESPduinoV1+2 are OK with you.

**Comment by devyte** [comment]
@beicnet you can also use esp8266 generic module and select 15M spiffs.
@d-a-v I finally got my two d1 pro boards (only took 4 months), so I'll be doing some testing as well.

**Comment by beicnet** [comment]
@d-a-v Thank you so much for that!!! So, basically from now "ESPDuino and D1 Mini Pro" will be included in the boards.txt file?

Another thing, @SmartArduino did a same PR as I did, see #2740 almost a year ago!

Yes, I have a bunch of Wifi modules, also have D1 Mini Pro and ESPDuino too...

And this is my ESPDuino listing from my current boards.txt and it's just working fine!

```
espduino.name=ESPDuino (ESP-13 Module)

espduino.upload.tool=esptool
espduino.upload.speed=115200

espduino.menu.ResetMethod.ck=ESPduino-V1
espduino.menu.ResetMethod.ck.upload.resetmethod=nodemcu
espduino.menu.ResetMethod.ESPduino=ESPduino-V2
espduino.menu.ResetMethod.ESPduino.upload.resetmethod=nodemcu

espduino.upload.maximum_size=1044464
espduino.upload.maximum_data_size=81920
espduino.upload.wait_for_upload_port=true
espduino.serial.disableDTR=true
espduino.serial.disableRTS=true

espduino.build.mcu=esp8266
espduino.build.f_cpu=80000000L
espduino.build.board=ESP8266_ESP13
espduino.build.core=esp8266
espduino.build.variant=espduino
espduino.build.flash_mode=dio
espduino.build.flash_size=4M
espduino.build.flash_freq=40
espduino.build.debug_port=
espduino.build.debug_level=

espduino.menu.CpuFrequency.80=80 MHz
espduino.menu.CpuFrequency.80.build.f_cpu=80000000L
espduino.menu.CpuFrequency.160=160 MHz
espduino.menu.CpuFrequency.160.build.f_cpu=160000000L

espduino.menu.UploadTool.esptool=Serial
espduino.menu.UploadTool.esptool.upload.tool=esptool
espduino.menu.UploadTool.esptool.upload.verbose=-vv
espduino.menu.UploadTool.espota=OTA
espduino.menu.UploadTool.espota.upload.tool=espota

espduino.menu.UploadSpeed.115200=115200
espduino.menu.UploadSpeed.115200.upload.speed=115200
espduino.menu.UploadSpeed.9600=9600
espduino.menu.UploadSpeed.9600.upload.speed=9600
espduino.menu.UploadSpeed.57600=57600
espduino.menu.UploadSpeed.57600.upload.speed=57600
espduino.menu.UploadSpeed.256000.windows=256000
espduino.menu.UploadSpeed.256000.upload.speed=256000
espduino.menu.UploadSpeed.230400.linux=230400
espduino.menu.UploadSpeed.230400.macosx=230400
espduino.menu.UploadSpeed.230400.macosx=230400
espduino.menu.UploadSpeed.230400.upload.speed=230400
espduino.menu.UploadSpeed.460800.linux=460800
espduino.menu.UploadSpeed.460800.macosx=460800
espduino.menu.UploadSpeed.460800.upload.speed=460800
espduino.menu.UploadSpeed.512000.windows=512000
espduino.menu.UploadSpeed.512000.upload.speed=512000
espduino.menu.UploadSpeed.921600=921600
espduino.menu.UploadSpeed.921600.upload.speed=921600

espduino.menu.FlashSize.4M3M=4M (3M SPIFFS)
espduino.menu.FlashSize.4M3M.build.flash_size=4M
espduino.menu.FlashSize.4M3M.build.flash_ld=eagle.flash.4m.ld
espduino.menu.FlashSize.4M3M.build.spiffs_start=0x100000
espduino.menu.FlashSize.4M3M.build.spiffs_end=0x3FB000
espduino.menu.FlashSize.4M3M.build.spiffs_blocksize=8192
espduino.menu.FlashSize.4M3M.build.spiffs_pagesize=256

espduino.menu.FlashSize.4M1M=4M (1M SPIFFS)
espduino.menu.FlashSize.4M1M.build.flash_size=4M
espduino.menu.FlashSize.4M1M.build.flash_ld=eagle.flash.4m1m.ld
espduino.menu.FlashSize.4M1M.build.spiffs_start=0x300000
espduino.menu.FlashSize.4M1M.build.spiffs_end=0x3FB000
espduino.menu.FlashSize.4M1M.build.spiffs_blocksize=8192
espduino.menu.FlashSize.4M1M.build.spiffs_pagesize=256
```

**Comment by d-a-v** [comment]
> @d-a-v Thank you so much for that!!! So, basically from now "ESPDuino and D1 Mini Pro" will be included in the boards.txt file?

The generator will wait for 2.4.0 released (so in 2.4.x or in 2.5).
In the meantime, and for 2.4.0, there will probably be an update because there are mistakes in current board.txt. So yes, I guess both the boards will be present in 2.4.0.

Do you have both ESPduino-V1 and ESPDuino-V2 so you can check V1 too, because:
> (edited above) I find it strange the resetmethod.ck=nodemcu for the V1 (it was ck, was it wrong?), but I applied it anyway so it can be tested.

**Comment by beicnet** [comment]
Thank you @d-a-v and I don't have v1 of ESPDuino, only v2, but the boards.txt code what I posted above is from the [Official](https://github.com/SmartArduino/SZDOITWiKi/wiki/How-to-Use) GitHub page for ESPDuino (it was their fix) and I can use my device with that entry.

**Comment by beicnet** [comment]
Dear @devyte Yes, I know that, but you know, it's easier to find your device in the "device list menu"! ;)

**Comment by mcauser** [comment]
What about the changes to:
`doc/boards.md`
`doc/filesystem.md`

**Comment by d-a-v** [comment]
@mcauser Please reopen for these changes

**Comment by devyte** [comment]
Please strip out all other changes and leave only the two md files.

**Comment by beicnet** [comment]
@mcauser Can you maybe add a few option for the SPIFFS to choose from?

```
16M (10M SPIFFS)
16M (14M SPIFFS)
16M (15M SPIFFS)
```

**Comment by d-a-v** [comment]
@beicnet this is not specific to d1 mini pro, please use #3722 to keep track of your request

**Comment by beicnet** [comment]
@d-a-v Okay! :wink:

**Comment by igrr** [comment]
conflict in boards.txt needs to be resolved, otherwise LGTM.

**Comment by d-a-v** [comment]
@igrr sorry for the ping I clicked on the wrong button :confused:

**Comment by d-a-v** [comment]
Closing here. D1 mini pro is there, though not reported to be fully tested / working.
discussion in #2581.

**Pull request closed without merging**
