### PR TITLE
Bug-fix release EspSoftwareSerial 6.5.3

### PR DESCRIPTION
**Pull request by dok-net**
Pending approval by 3rd party bug reporter

### CODE REVIEW

**Comment by dok-net** [comment]
@earlephilhower Done and ready for merge now. Thanks!

**Comment by dok-net** [comment]
@earlephilhower This 6.5.1 release fixes #6920, which on it's own is worth merging.
Unfortunately, I am giving up for the moment on a sporadic crash/reset that I see under test - HW sends continuously to EspSoftwareSerial/examples/repeater sketch - but I am unable to locate a cause for in due time. I am open for suggestions - it happens on different boards:

```
Effective data rate: 8140bps, 0cps seq. errors (0.00%) (0 parity errors)
Effective data rate: 8150bps, 0cps seq. errors (0.00%) (0 parity errors)
Effective data rate: 8160bps, 0cps seq. errors (0.00%) (0 parity errors)
�!L�<1�1DRepeater example for EspSoftwareSerial
Effective data rate: 8150bps, 0cps seq. errors (0.00%) (0 parity errors)
Effective data rate: 8160bps, 0cps seq. errors (0.00%) (0 parity errors)
Effective data rate: 8160bps, 0cps seq. errors (0.00%) (0 parity errors)
```
Not much to go by on USB logging.

I wonder if IRAM is exhausted :-( ?
```
Executable segment sizes
IROM   *: 237712          - code in flash         (default or ICACHE_FLASH_ATTR)
IRAM   *: 28860   \ 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...)
DATA   *: 1252  )         - initialized variables (global, static) in RAM\HEAP
RODATA *: 848   ) \ 81920 - constants             (global, static) in RAM\HEAP
Program size: 268,672 bytes (used 26% of a 1,044,464 byte maximum) (29.49 secs)
BSS    *: 25520 )         - zeroed variables      (global, static) in RAM\HEAP
Minimum Memory Usage: 27620 bytes (34% of a 81920 byte maximum)
```

**Comment by earlephilhower** [comment]
OK, @dok-net, will wait for you to give all clear.

IRAM is statically allocated.  It either has enough space, and you get successful link, or it doesn't and you don't get an .ELF out, so it's not that.

Are you getting anything on the HW serial port for the resets?  WDT is one place the -32 and the 8266 are very different.

Don't sweat the Win build failures.  Looks like the early access Win VMs started pooping the bed.  I'll look at it tonight, and if I can't figure out then I'll pull the Win build for now.  Just worry about your own SWSerial stuff.

**Comment by dok-net** [comment]
First findings running for a few hours overnight: Reprogrammed with erasing complete flash memory, no crashing. This means the WiFi isn't set up at all.

Now adding
```c++
    WiFi.mode(WIFI_STA);
    WiFi.begin("...", "...");

    // Wait for connection
    while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print(".");
    }
    Serial.println("");
    Serial.print("IP address: ");
    Serial.println(WiFi.localIP());
```
at the end of `setup()` (and the requisite includes to the top of the file).
BOOM:
```
Effective data rate: 8190bps, 0cps seq. errors (0.00%) (46278 parity errors)
Effective data rate: 8190bps, 0cps seq. errors (0.00%) (47496 parity errors)
�!L�<1�1DRepeater example for EspSoftwareSerial
.......
IP address: 192.168....
Effective data rate: 3750bps, 2cps seq. errors (0.58%) (1534 parity errors)
Effective data rate: 8170bps, 0cps seq. errors (0.00%) (3110 parity errors)
```
@earlephilhower This is on USB serial, same as I said before - isn't that the HW serial port that you are referring to, I have no other? This means there is no diagnostics at all.

Anyway, in my mind this means there is no acute reason to believe this is caused by EspSoftwareSerial, specifically there is no regression, and it should be released now to close the linked issue.

**Comment by dirkmueller** [comment]
@earlephilhower could you please review and merge? I am a bit impatient with this, sorry 🙂

**Comment by dok-net** [comment]
@dirkmueller In case you're a user of the fairly new parity/9bit feature, while searching for a cause of the resets I found and fixed a loss-of-sync bug - the parity reported drifted permanently from the actual data if there was an overflow. This occurred during delays >= 400ms at 19200bps, for instance :-)

**Comment by dok-net** [comment]
I didn't expect any of the changes to fix this, because I do not think it's anything in EspSoftwareSerial:
```
Effective data rate: 8170bps, 0cps seq. errors (0.00%) (0 parity errors) Uptime: 267230ms
Effective data rate: 8180bps, 0cps seq. errors (0.00%) (0 parity errors) Uptime: 270161ms
Effective data rate: 8170bps, 0cps seq. errors (0.00%) (0 parity errors) Uptime: 273098ms
�!L�<1�1GRepeater example for EspSoftwareSerial
..
IP address: 192......
Effective data rate: 8270bps, 5cps seq. errors (0.67%) (20 parity errors) Uptime: 3195ms
Effective data rate: 8190bps, 0cps seq. errors (0.00%) (0 parity errors) Uptime: 6125ms
```

**Pull request merged**
