### PR TITLE
fixed support for psk

### PR DESCRIPTION
**Pull request by devyte**
fixed in WiFiSTA, added support for psk to WiFiMulti, added count accessor, minor code cleanups

### CODE REVIEW

**Comment by devyte** [comment]
Fixes #2247 .

**Comment by igrr** [comment]
Changes look good. Just a question: have you tested that connection using psk actually works?

**Comment by devyte** [comment]
@igrr no, and I don't have a setup for testing it either, so I need verification from someone else.
On the plus side, the relevant code shouldn't affect non-psk behavior, so in theory we could merge without affecting anything else.

**Comment by devyte** [comment]
It's been over a week. Given that the fix shouldn't affect current behavior, that this has been looked at by @igrr, and in the interest of moving forward, I'm merging. If there is still a problem, I'll handle it in a separate issue.

**Pull request merged**
