### PR TITLE
WiFiClient: clean up ClientContext before connecting

### PR DESCRIPTION
**Pull request by igrr**
Fixes https://github.com/esp8266/Arduino/issues/4497

### CODE REVIEW

**Comment by igrr** [comment]
WIP because i want to add a test case for this.

**Comment by Eszartek** [comment]
I think the references to "client" should be "_client"

**Comment by devyte** [comment]
@igrr will you be adding to this pr?

**Comment by d-a-v** [comment]
I think we can merge here

**Comment by d-a-v** [comment]
@igrr is #4549's way of testing looks like what you intended to do ?

**Comment by igrr** [comment]
@d-a-v, pretty much, yes :) I got stuck yak shaving trying to remove the need for `global`s in the script and I think I ended up writing a new test framework. Let's merge your test :)

**Comment by devyte** [comment]
@igrr is this pr ready for merging, or is additional work needed?

**Comment by igrr** [comment]
Should be good to merge along with @d-a-v 's tests in #4549!

**Pull request merged**
