### PR TITLE
ArduinoOTA: don't crash on unrecognized packets

### PR DESCRIPTION
**Pull request by yoursunny**

### CODE REVIEW

**Comment by devyte** [comment]
Nice job figuring this out!

**Comment by lrmoreno007** [comment]
@Juppit Yes, that solve the problem.

And an observation, in the function readStringUntil, now value is an integer but later it is compared with two char ('\ 0' and end).

From my little knowledge, I think this is better to leave it as it was.

**Comment by yoursunny** [comment]
> With the for loop index is now incremented double

Oops, I didn’t notice that. I’m not used to `while` loops.
I wish there’s a way to have automated tests...

> in the function readStringUntil, now value is an integer but later it is compared with two char ('\ 0' and end).

I believe these are fine. `char` is implicitly convertable to `int` without losing precision, and they are compared as `int`.

**Comment by devyte** [comment]
I missed that as well. If someone makes a PR, I'll look at it and merge it asap.

**Pull request merged**
