### PR TITLE
EspSoftwareSerial 6.8.5: fixes parity for TX with odd word size modes

### PR DESCRIPTION
**Pull request by dok-net**

### CODE REVIEW

**Comment by earlephilhower** [comment]
@dok-net is this good for 2.7.2 or is it high risk?

**Comment by dok-net** [comment]
Having had another day, I've updated the examples to hint at parity errors from SW serial, too.
To your question, yes, it's safe and should absolutely be in ASAP.

**Comment by d-a-v** [comment]
Updated to master.
@dok-net is there another planned change today ?

**Comment by dok-net** [comment]
@d-a-v: just fixing issues as they are becoming available, no further ones known today. 🙂

**Pull request merged**
