### PR TITLE
udp: fix again pbuf management

### LINKED ISSUE #7124: OTA broken after commit #7036
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:					nodemcu
- Core Version:			e6decacd0a03a61f00068264b024e7
- Development Env:		Makefile
- Operating System:		Linux

### Settings in IDE

- Module:  			Generic ESP8266 Module
- Flash Mode:			qio
- Flash Size: 		        4M
- lwip Variant:                 v2 Lower Memoru
- Reset Method:		nodemcu
- Flash Frequency:	       40Mhz
- CPU Frequency:		80Mhz
- Upload Using:		OTA
- Upload Speed:              115200

### Problem Description

@d-a-v @devyte After commit #7036 OTA no longer works, it just hangs. I traced it back to this specific commit.

### PR DESCRIPTION
**Pull request by d-a-v**
This follows #7036 where udp pbuf chain handling is made hairy because of interleaved information fragment introduced with IPv6.

@szekelyisz Could you please test this change ?
fixes #7124

### CODE REVIEW

**Comment by MarkyAD** [comment]
Confirming this does indeed fix #7124

**Comment by szekelyisz** [comment]
Reassembly on IPv4 still works, no problem. Something's up though.

I'm sending 4 UDP packets with 1024 bytes payload each in quick succession. The first one is delivered immediately, but the remaining 3 are buffered by LwIP. How those are delivered depends on the commit.

* Vanilla 2.6.2: all packets are correctly delivered to the application.
* #7036: packets in the buffer are dropped.
* This PR: three packets are delivered, the first one contains all three of them interleaved with some garbage data, the second one contains the last two, again interleaved with some garbage, and the last one contains the last packet. I'm suspecting the garbage is the address info pbuf.

I can take a look tomorrow. Not tested IPv6 yet.

**Comment by d-a-v** [comment]
> This PR: three packets are delivered, the first one contains all three of them interleaved with some garbage data, the second one contains the last two, again interleaved with some garbage, and the last one contains the last packet. I'm suspecting the garbage is the address info pbuf.

I think (and while I'm writing it becomes clear) it is because of 
```
    size_t getSize() const
    {
        if (!_rx_buf)
            return 0;

        return _rx_buf->tot_len - _rx_buf_offset;
    }
```

The info pbuf (the garbage)  should not be accessible but it is because of `getSize()` (which should only report size before next info pbuf) and your fix (use of pbuf_contiguous()).
So an update of this PR is needed in order to cache this value for the current packet.

> I can take a look tomorrow. Not tested IPv6 yet.

This is not needed. The code needed for IPv6 is also used for IPv4 and is the info pbuf management.

**Comment by d-a-v** [comment]
@szekelyisz Can you please retry with latest commit ?

**Comment by szekelyisz** [comment]
> @szekelyisz Can you please retry with latest commit ?

Reassembly still works and smaller packets are also delivered correctly.

**Comment by d-a-v** [comment]
Thanks for testing !

**Pull request merged**
