### PR TITLE
Update to SdFat 2.0.0

### LINKED ISSUE #7772: ESP8266SdFat Performance vs Upstream SdFat
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [X] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:				Wemos D1 mini (ESP-12)
- Core Version:			2.7.4 - 2843a5a
- Development Env:		Arduino IDE
- Operating System:		Windows

### Settings in IDE

- Module:  			Generic ESP8266 Module
- Flash Mode:			dio
- Flash Size: 		       4MB
- lwip Variant:                 v2 Lower Memory
- Reset Method:	      nodemcu
- Flash Frequency:	     40Mhz
- CPU Frequency:	     160MHz
- Upload Using:	     SERIAL
- Upload Speed:           921600

### Problem Description

SPI SD card usage utilizing SD or SDFS is much slower than expected.  Testing utilizing the ESP8266SdFat->bench example sketch is showing write speeds of ~130 KB/s and read speeds of ~650 KB/s.  Attempts to utilize ```ENABLE_EXTENDED_TRANSFER_CLASS``` and ```SdFatEx``` in the bench example fail to compile.  Analysis with a logic analyzer show many pauses in SPI transactions while writing data.  While troubleshooting, I decided to replace ESP8266SdFat with the upstream version which now supports ESP8266 and ESP32.  Testing with the upstream SdFat->bench example showed write speeds of ~1.6MB/s and read speeds of 3.2MB/s, much faster than the current version included in ESP8266SdFat.  This does seem to break the SD/SDFS wrappers due to changes in SdFat.  Usage of ```ENABLE_DEDICATED_SPI``` in SdFat didn't cause any noticeable increase of performance which may warrant further analysis.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch
[2.7.4 ESP8266SdFat bench.ino](https://github.com/earlephilhower/ESP8266SdFat/blob/b240d2231a117bbd89b79902eb54cae948ee2f42/examples/bench/bench.ino)
[Upstream SdFat bench.ino](https://github.com/greiman/SdFat/blob/master/examples/bench/bench.ino)

### PR DESCRIPTION
**Pull request by earlephilhower**
Fixes #7772 

@forkineye can you give this a try and report back?  I'm getting ~1.5MB/s w/my setup (limited SPI speed due to wiring/card) which is somewhat above what I saw before.

### CODE REVIEW

**Comment by forkineye** [comment]
@earlephilhower I'll pull this down today and test it, thank you

**Comment by forkineye** [comment]
The bench example failed to compile with SD_FAT_TYPE set to the default of 0, claiming that "file" of type "File".  Setting to SD_FAT_TYPE to 3 was successful and showed substantial increases to compared to the current master branch.  I am however experiencing issues when attempt to write or delete files from my application. I need to troubleshoot further to make sure it's not my code, but I've included the top of the stack dump below.  It does work however in 2.7.4 and the current master, it's just slow.

### Bench tests
master branch - 130KB/s write; 650KB/s read
sdfat20 branch - 1700KB/s writel 3170KB/s read

### bench.ino error
```
#if SD_FAT_TYPE == 0
SdFat sd;
File file;
#elif SD_FAT_TYPE == 1
SdFat32 sd;
File32 file;
#elif SD_FAT_TYPE == 2
SdExFat sd;
ExFile file;
#elif SD_FAT_TYPE == 3
SdFs sd;
FsFile file;
#else  // SD_FAT_TYPE
#error Invalid SD_FAT_TYPE
#endif  // SD_FAT_TYPE
```
```
Bench:177:13: error: 'class fs::File' has no member named 'open'
  177 |   if (!file.open("bench.dat", O_RDWR | O_CREAT | O_TRUNC)) {
      |             ^~~~
Bench:202:17: error: 'class fs::File' has no member named 'preAllocate'
  202 |       if (!file.preAllocate(FILE_SIZE)) {
      |                 ^~~~~~~~~~~
Bench:220:28: error: 'class fs::File' has no member named 'curPosition'; did you mean 'position'?
  220 |         skipLatency = file.curPosition() < 512;
      |                            ^~~~~~~~~~~
      |                            position
Bench:230:10: error: 'class fs::File' has no member named 'sync'
  230 |     file.sync();
      |          ^~~~
Bench:232:14: error: 'class fs::File' has no member named 'fileSize'
  232 |     s = file.fileSize();
      |              ^~~~~~~~
Bench:243:10: error: 'class fs::File' has no member named 'rewind'
  243 |     file.rewind();
      |          ^~~~~~
Bench:273:14: error: 'class fs::File' has no member named 'fileSize'
  273 |     s = file.fileSize();
      |              ^~~~~~~~
```

### Stack dump from [my code](https://github.com/forkineye/ESPixelStick/tree/unify)
```
Deleting File: '/bench.dat'

User exception (panic/abort/assert)
Panic core_esp8266_main.cpp:136 __yield

0x4022e8ee: raise_exception at core_esp8266_postmortem.cpp line ?
0x401005d6: millis at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\cores\esp8266/core_esp8266_wiring.cpp line 188
0x4022e95b: __panic_func at ?? line ?
0x4022e151: yield at ?? line ?
0x40227e40: sdfat::SysCall::curTimeMS() at c:\users\sporadic\documents\arduino\hardware\esp8266com\esp8266\libraries\esp8266sdfat\src\common/syscall.h line 82
:  (inlined by) sdfat::SdSpiCard::isTimedOut(unsigned short, unsigned short) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266SdFat\src\SdCard/SdSpiCard.cpp line 461
0x40227f81: sdfat::SdSpiCard::waitNotBusy(unsigned short) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266SdFat\src\SdCard/SdSpiCard.cpp line 693
0x40227fcc: sdfat::SdSpiCard::spiSend(unsigned char) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266SdFat\src\SdCard/SdSpiCard.h line 327
:  (inlined by) sdfat::SdSpiCard::cardCommand(unsigned char, unsigned int) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266SdFat\src\SdCard/SdSpiCard.cpp line 369
0x4022826d: sdfat::SdSpiCard::readStart(unsigned int) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266SdFat\src\SdCard/SdSpiCard.cpp line 581
0x4022852b: sdfat::SdSpiCard::readSectors(unsigned int, unsigned char*, unsigned int) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266SdFat\src\SdCard/SdSpiCard.cpp line 611
0x402279cc: sdfat::FatCache::read(unsigned int, unsigned char) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266SdFat\src\FatLib/FatPartition.cpp line 43
0x40227a4a: sdfat::FatPartition::fatGet(unsigned int, unsigned int*) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266SdFat\src\FatLib/FatPartition.cpp line 252
:  (inlined by) sdfat::FatPartition::fatGet(unsigned int, unsigned int*) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266SdFat\src\FatLib/FatPartition.cpp line 228
0x40227bc7: sdfat::FatPartition::freeChain(unsigned int) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266SdFat\src\FatLib/FatPartition.cpp line 376
0x402262f8: sdfat::FatFile::open(sdfat::FatFile*, char const*, unsigned char) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266SdFat\src\FatLib/FatFile.cpp line 473
0x40226cb1: sdfat::FatFile::remove() at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266SdFat\src\FatLib/FatFileLFN.cpp line 583 (discriminator 1)
0x4022ce4d: String::changeBuffer(unsigned int) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\cores\esp8266/WString.cpp line 167
0x4022f62e: uart_write at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\cores\esp8266/uart.cpp line 509
0x40224834: sdfs::SDFSImpl::remove(char const*) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\libraries\SDFS\src/SDFS.h line 130 (discriminator 4)
0x40231e3c: fs::FS::remove(char const*) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\cores\esp8266/FS.cpp line 404
0x4022ba06: fs::FS::remove(String const&) at C:\Users\sporadic\Documents\Arduino\hardware\esp8266com\esp8266\cores\esp8266/FS.cpp line 408
0x402169e8: c_FPPDiscovery::DeleteFseqFile(String&) at c:\tmp\build\sketch\src\service/FPPDiscovery.cpp line 1177
```

**Comment by earlephilhower** [comment]
Thanks for the update!

> The bench example failed to compile with SD_FAT_TYPE set to the default of 0, claiming that "file" of type "File". Setting to SD_FAT_TYPE to 3 was successful and showed substantial increases to compared to the current master branch.

This is expected because only the private definition of `File` used in the SDFat example that works/is needed for the normal Arduino `File` is that one.  There are some ugly name overlap issues still in the other methods they use.  So Type 0, 1, and 3 aren't used in the 8266 core.

> I am however experiencing issues when attempt to write or delete files from my application. I need to troubleshoot further to make sure it's not my code, but I've included the top of the stack dump below. It does work however in 2.7.4 and the current master, it's just slow.

If you can get an MCVE to reproduce it that would be great!   Looking at the trace it *looks* like a `yield()` was called from inside an ISR callback.  If that's the case, it's illegal on the ESP8266.  My guess is that the new SPI object the author wrote has a yield() in it or is trying to `delay()` inside an ISR...either or which is a no-no.

What's weird is that I'm not seeing it on my (limited) testing w/the FSBrowser and LittleFS_SpeedTest.  Both of which do seem to be much snappier than before for me, as well.

> ### Stack dump from [my code](https://github.com/forkineye/ESPixelStick/tree/unify)
> 
> ```
> Deleting File: '/bench.dat'
> 
> User exception (panic/abort/assert)
> Panic core_esp8266_main.cpp:136 __yield

https://github.com/esp8266/Arduino/blob/f3521da173e7995f3d7e4a657fed5ab081de2ff6/cores/esp8266/core_esp8266_main.cpp#L130-L138

**Comment by earlephilhower** [comment]
As a test, can you try applying this 1-line change to the SDFat library replacing yield() with delay(0) which, IIRC, is IRQ safe?

````
earle@server:~/Arduino/hardware/esp8266com/esp8266/libraries/ESP8266SdFat/src/common$ git diff
diff --git a/src/common/SysCall.h b/src/common/SysCall.h
index 34b9ca6..c565e58 100644
--- a/src/common/SysCall.h
+++ b/src/common/SysCall.h
@@ -92,7 +92,7 @@ inline void SysCall::yield() {
 #elif defined(ARDUINO)
 inline void SysCall::yield() {
   // Use the external Arduino yield() function.
-  ::yield();
+  ::delay(0);
 }
 #else  // defined(PLATFORM_ID)
 inline void SysCall::yield() {}
````

**Comment by forkineye** [comment]
> As a test, can you try applying this 1-line change to the SDFat library replacing yield() with delay(0) which, IIRC, is IRQ safe?
> 
> ```
> earle@server:~/Arduino/hardware/esp8266com/esp8266/libraries/ESP8266SdFat/src/common$ git diff
> diff --git a/src/common/SysCall.h b/src/common/SysCall.h
> index 34b9ca6..c565e58 100644
> --- a/src/common/SysCall.h
> +++ b/src/common/SysCall.h
> @@ -92,7 +92,7 @@ inline void SysCall::yield() {
>  #elif defined(ARDUINO)
>  inline void SysCall::yield() {
>    // Use the external Arduino yield() function.
> -  ::yield();
> +  ::delay(0);
>  }
>  #else  // defined(PLATFORM_ID)
>  inline void SysCall::yield() {}
> ```

That seems to have fixed it, thanks!

**Pull request merged**
