### PR TITLE
Available yield

### PR DESCRIPTION
**Pull request by Makuna**
https://github.com/esp8266/Arduino/issues/540

NOTE:  There is bleed over in the changes from a previous pull request, don't know how to clean that out other than revert it on my branch; BUT I DO NOT WANT TO REVERT THOSE CHANGES if they get merged in.

### CODE REVIEW

**Comment by igrr** [comment]
Since there isn't a way to handle this yield issue in one single place, i would propose to reduce the amount of code duplication by refactoring this as follows.

- Introduce a global function, e.g. `maybe_yield()`:
```C++
void maybe_yield() {
  if (micros() - esp_micros_at_task_start() > 10000) {
    yield();
  }
}
```
- Update `available` methods to use it instead of `esp_micros_at_task_start` (which was a quick and dirty hack on my side):

```C++
bool isAvailable = ... ; // depending on the class
if (!isAvailable) {
  maybe_yield();
  isAvailable = ...; // perhaps update isAvailable, depending on the class?
}
return isAvailable;
```

**Comment by igrr** [comment]
Also i would like to merge your fixes in 4d3ef20. Would you mind if I rebase that change directly right now and then we go with a clean pull related to isAvailable?

**Comment by Makuna** [comment]
Go ahead and take the other, I will refactor this stuff and put out a new pull

**Comment by Makuna** [comment]
Note that https://github.com/esp8266/Arduino/pull/534 already contains the changes you want, just merge that.

**Comment by Links2004** [comment]
will the ```yield``` brake the code if i call it for example in the Ticker or the IO interrupt handler?

**Comment by igrr** [comment]
That's right, yield is non-reentrant, so calling it from Ticker or GPIO interrupt will cause an exception.
Doing `while(!Serial.available()){}` from an interrupt is not good either, but i think it would be good not to yield on the first invocation of available(). That was the rationale behind the existing code — so that you could call available() at least once from system context.

**Comment by Links2004** [comment]
yes ```while(!Serial.available()){}``` is a bad idea,
but a simple ```int i = Serial.available();``` need to work otherwise we get more problems again.

**Comment by igrr** [comment]
My suggestion here is to only yield if available() was called more than once with zero result.
This way we can still read all available data from both sketch and system contexts, and handle the case of `while(!available());` loop.

**Comment by Makuna** [comment]
this is replaced by https://github.com/esp8266/Arduino/pull/551

**Pull request closed without merging**
