### PR TITLE
Xmc flash 2

### PR DESCRIPTION
**Pull request by ChocolateFrogsNuts**
Remove the unnecessary  XMC chip support from eboot and verify the flash contents after copying new firmware.

Testing shows there should be no issue with the XMC chips in eboot because the flash access speed is always 20MHz, however verifying the content written will help identify any issues if they do occur.
The additional code is minimal, and as it only reads, the verify is very quick.

### CODE REVIEW

**Comment by Tech-TX** [comment]
That works with both failing cases for me (OTA upload and ESP.restart() at 160MHz),
https://github.com/esp8266/Arduino/issues/7307
https://github.com/esp8266/Arduino/issues/7267

I've already merged https://github.com/esp8266/Arduino/pull/7277 into my local fork, so I'm not sure if #7267 is needed in addition to this PR.

**Comment by devyte** [comment]
@Tech-TX #7277 was a rollback of the first implementation. This should be the fixed final solution.

**Comment by devyte** [comment]
The verify is supposed to cover the case when the flash write seems to succeed, i. e. no error, but in truth it didn't take at hw level due to whatever reason.

**Comment by ChocolateFrogsNuts** [comment]
@earlephilhower the check is relatively cheap (in terms of code size and execution time) and if we do have problems with OTA updates to XMC chips will make it easy to identify if it is a problem with writing to the chip.
Theoretically we could store ACTION_COPY_FAILED in the RTC and have that cause printing the error and a while(true){}
That way if an OTA update copy failed, the chip would halt, then you could connect to the USB and press reset to get the reason dumped to monitor. If the eboot command is moved to a non-volatile location, it would even work over power cycles (although you would need to clear that the eboot command as part of a USB update).

**Pull request merged**
