### PR TITLE
Update to SDK 1.5 (#1102)

### PR DESCRIPTION
**Pull request by igrr**
- update libraries
- update loop task priority
- update phy init data

### CODE REVIEW

**Comment by bakercp** [comment]
+1 :)

**Comment by asetyde** [comment]
Big work ! Thx

**Comment by Juppit** [comment]
Once again, as usual with you, not a little problem. Tested with my default app.

**Comment by igrr** [comment]
I was not able to get WPA2-Enterprise to work, but merging this anyway.

**Comment by nemeier** [comment]
Thx, looking forward to play around with mesh, great work

**Pull request merged**
