### PR TITLE
Want to add board WiFiduino

### PR DESCRIPTION
**Pull request by i3water**
Thanks,

I want to add an arduino uno like board [WiFiduino](https://wifiduino.com/esp8266/)

### CODE REVIEW

**Comment by i3water** [comment]
how about this site https://wifiduino.com/esp8266 ？

**Comment by d-a-v** [comment]
Yes, then you need to:
* update the website link
* generate and commit documentation (--docgen)
* push updates to your repo

**Comment by d-a-v** [comment]
It seems you modified some files by hand. The only editable ones are boards.txt.py and variant/*. The others are generated by the script, then Travis-CI double checks by regenerating and diffing them.
You need to regenerate all the other files with boards.txt.py's ```--*gen``` options and commit/push them as-is.

**Comment by i3water** [comment]
Yes, I modified boards.text, doc/boards.rst, package/package_esp8266com_index.template.json by hand. I tried `tools/boards.text.py --docgen` `--boardsgen` `--packagegen` , there nothing replaced but just open boards.text.py, let me check is there something wrong with my setting.

**Comment by i3water** [comment]
i had regenerate the boards doc and package, but unfortunatly them all check failed.Is there something wrong with my regenerate or commit?

**Comment by i3water** [comment]
:(
Sadly, I don't know what to do with CI check fail.
hope to receive your reply.

Thanks.

**Pull request merged**
