### PR TITLE
Bug-fix release 6.12.1

### PR DESCRIPTION
**Pull request by dok-net**
A documentation error was reported by a user.
Loss of RX data due to dropped bit-patterns that masked the stop-bit fixed.

### CODE REVIEW

**Comment by earlephilhower** [comment]
@dok-net is this good to go now?

**Comment by Pablo2048** [comment]
> @dok-net is this good to go now?

So far so good, but I can not test every combination - please give me one more day to let the test running at least 24 hours...

**Comment by Pablo2048** [comment]
Ok guys - so far so good. My testing os MDB-VMC 9 bit protocol seems to be all ok. So LGTM. Thank you.

**Comment by dok-net** [comment]
@earlephilhower There could be feedback incoming from another person's issue. I would be satisfied if you could merge by the end of the weekend, on your own schedule. If anything new arises before then, I'll let you know here. Thanks!

**Comment by dok-net** [comment]
@earlephilhower Ready to go :-)

**Pull request merged**
