### PR TITLE
LEAmDNS Fixes 1.1

### PR DESCRIPTION
**Pull request by LaborEtArs**
Third try...
- Better separation of ESP wifi thread code from user thread code
- Added a flag for 'update()'-less use (disabled by default)
- The too fast updates for service queries are fixed
- Switched fully to PolledTimeout; LEATimeFlag not needed anymore (BTW: a const 'expired()' method would be helpful)
- The device should stay visible now even after the first TTL timeout
- Improved service querying (queries five times now)
- Fixed default TTLs (bug introduced in Fixes 1.0)

### CODE REVIEW

**Comment by devyte** [comment]
@LaborEtArs there seems to be something missing here, the build is failing due to a compile error related to a timeflag.

**Comment by LaborEtArs** [comment]
All references to LEATimeFlag should have been removed (teanslated to PolledTimeout)... will have a look into the sources again

**Comment by LaborEtArs** [comment]
Sorry, can’t find a reference to LEATimeFlag in the sources anymore, which file is causing the build problems?

**Comment by d-a-v** [comment]
`Checks Have Failed` > `details` > click on one red result > scroll down

```
/home/travis/build/esp8266/Arduino/libraries/ESP8266mDNS/examples/LEAmDNS/mDNS_Clock/mDNS_Clock.ino:320:10: error: 'clsMDNSTimeFlag' does not name a type
   static clsMDNSTimeFlag timeFlag(UPDATE_CYCLE);
          ^
/home/travis/build/esp8266/Arduino/libraries/ESP8266mDNS/examples/LEAmDNS/mDNS_Clock/mDNS_Clock.ino:321:7: error: 'timeFlag' was not declared in this scope
   if (timeFlag.flagged()/*ulNextTimeUpdate < millis()*/) {
       ^
```

**Comment by LaborEtArs** [comment]
The examples... arghhh

**Pull request merged**
