### PR TITLE
#2111 Added a hook to user_init in core_esp8266_main.c to be able to do ver…

### PR DESCRIPTION
**Pull request by tuxedo0801**
…y early things, like disabling wifi

see: 
- https://github.com/esp8266/Arduino/issues/2111#issuecomment-224251391
- https://github.com/esp8266/Arduino/issues/2133

### CODE REVIEW

**Comment by tuxedo0801** [comment]
No idea why this fails in ci check... works great on my 2.2.0 installation here.

**Comment by igrr** [comment]
You call `early_init` but it's not defined anywhere, right? So linker legitimately complains. It works in your installation because you actually have `early_init` function in your sketch, I suppose. Now try opening and compiling one of the examples...

**Comment by tuxedo0801** [comment]
indeed, but `early_init` should be optional and not mandatory :-(

How can this be done? (sorry, I'm more an java than an c expert)

**Comment by tuxedo0801** [comment]
This should be easy for an C expert I guess?!

I understand why this error happens on travis-ci, and I understand why it works in my sketch.

But I have no idea how I can the compiler that there "might" be a function called "early_init".

In my lib I use function-pointers to have this kind of feature. But I have to give the function pointer first to my lib so that it can execute the function.

**Comment by d-a-v** [comment]
@tuxedo0801 (two years after)

> But I have no idea how I can tell the compiler that there "might" be a function called "early_init".

We can do that with the "weak " gcc extension in function declaration.
#5395 took care of it.

**Pull request closed without merging**
