### PR TITLE
Docs: add an entry about compiler warnings

### PR DESCRIPTION
**Pull request by mcspr**
per https://github.com/esp8266/Arduino/issues/8421 and https://github.com/esp8266/Arduino/issues/8475
after checking HW, suggest to check SW as well at least by enabling compiler warnings
(and also note of the IDE weirdest defaults causing issues we expected to stay solved)

### CODE REVIEW

**Review by d-a-v — APPROVED** [review]
This was missing.

**Comment by earlephilhower** [comment]
Don't we *always* generate a warning/error on this case, even with `None`?  If not, I think we can fix it instead of documenting it, by changing the `platform.txt` options...

**Comment by mcspr** [comment]
only 3 out of 4 options produce error:
https://github.com/esp8266/Arduino/blob/15e7d35d6e7c430915a5a86d854ae855d10a8da5/platform.txt#L24-L28

'None' never does, `-w` overrides any `-W` flags since they apply all at once and not like 'disable all warnings *but* still enable this one', order does not matter. Removing `-w` from 'None' kind of defeats the purpose of the option, and there is 'Default' for that.

We do still need to mention the warnings, which even in 'Default' will give some useful advice. Specifically with C++, shouldn't we mention that it is undefined behaviour when trying to code like that?

btw low-level routines that really do not return may still be coded like this
```cpp
int func() {
  __builtin_unreachable();
}
```

**Comment by earlephilhower** [comment]
Argh, you are correct.  Even trying to explicitly enable a warning like `-w -Wreturn-type -Werror=return-type` doesn't work.

It seems the only way to make this automatically catch is to not use `-w` and specifically list all ~100 `-Wno-XXX` in an `@option` file.  While doable, that's more involved than I have time for this AM...

**Review by earlephilhower — APPROVED** [review]

**Pull request merged**
