### PR TITLE
Allow compressed flash updates

### PR DESCRIPTION
**Pull request by earlephilhower**
As part of the compressed OTA image work, we will need to be able to
build the bootloader using -O2 to minimize code size for the
decompressor.

It was as -O0 which does no code optimization whatsoever because there
was a bit of quasi-assembly that was optimized out with any other
setting.  Building uzlib with -O0 is probably a bad thing and will wind
up much larger than with -O2.

Rewrite the jump-to-app code in pure ASM to avoid the optimization
issue.

Add -Wall and clean up warnings it generates.

Remove call to esptool-ck and generation of unused eboot.bin application
image since it is not used by the Arduino core.

### CODE REVIEW

**Comment by earlephilhower** [comment]
Boot sector w/compression code fits in 0xb98 thanks to @d-a-v's changes!  Still needs to be really hooked into it (check for GZIP header and if it's present then do the decompress, OTW just do it normally)
````
00000000 l    d  .comment       00000000 .comment
00000000 l    d  .debug_abbrev  00000000 .debug_abbrev
00000000 l    d  .debug_aranges 00000000 .debug_aranges
00000000 l    d  .debug_frame   00000000 .debug_frame
00000000 l    d  .debug_info    00000000 .debug_info
00000000 l    d  .debug_line    00000000 .debug_line
00000000 l    d  .debug_loc     00000000 .debug_loc
00000000 l    d  .debug_ranges  00000000 .debug_ranges
00000000 l    d  .debug_str     00000000 .debug_str
00000000 l    df *ABS*  00000000 adler32.c
00000000 l    df *ABS*  00000000 crc32.c
00000000 l    df *ABS*  00000000 eboot.c
00000000 l    df *ABS*  00000000 eboot_command.c
00000000 l    df *ABS*  00000000 tinfgzip.c
00000000 l    df *ABS*  00000000 tinflate.c
00000000 l    d  .xtensa.info   00000000 .xtensa.info
00000110 g       *ABS*  00000000 _memmap_cacheattr_wb_base
00000110 g       *ABS*  00000000 _memmap_cacheattr_wt_base
00000220 g       *ABS*  00000000 _memmap_cacheattr_bp_base
22222112 g       *ABS*  00000000 _memmap_cacheattr_wb_allvalid
22222112 g       *ABS*  00000000 _memmap_cacheattr_wt_allvalid
2222211f g       *ABS*  00000000 _memmap_cacheattr_wba_trapnull
2222211f g       *ABS*  00000000 _memmap_cacheattr_wbna_trapnull
2222211f g       *ABS*  00000000 _memmap_cacheattr_wb_trapnull
2222211f g       *ABS*  00000000 _memmap_cacheattr_wt_trapnull
22222222 g       *ABS*  00000000 _memmap_cacheattr_bp_allvalid
2222222f g       *ABS*  00000000 _memmap_cacheattr_bp_trapnull
3ff00000 g       *ABS*  00000000 _dport0_data_end
3ff00000 g       *ABS*  00000000 _dport0_data_start
3ff00000 g       *ABS*  00000000 _dport0_literal_end
3ff00000 g       *ABS*  00000000 _dport0_literal_start
3ff00000 g       *ABS*  00000000 _dport0_rodata_end
3ff00000 g       *ABS*  00000000 _dport0_rodata_start
3ffe8000 g     O .data  0000001e length_bits
3ffe8000 l    d  .data  00000000 .data
3ffe8020 g     O .data  00000013 clcidx
3ffe8034 g     O .data  0000003c length_base
3ffe8070 g     O .data  0000001e dist_bits
3ffe8090 g     O .data  0000003c dist_base
3ffe80d0 g       *ABS*  00000000 _heap_start
400024cc g       *ABS*  00000000 ets_printf
40002be8 g       *ABS*  00000000 ets_putc
40002fa0 g       *ABS*  00000000 ets_wdt_enable
400030f0 g       *ABS*  00000000 ets_wdt_disable
40004a00 g       *ABS*  00000000 SPIEraseSector
40004a4c g       *ABS*  00000000 SPIWrite
40004b1c g       *ABS*  00000000 SPIRead
4000dc88 g       *ABS*  00000000 __divsi3
4000e268 g       *ABS*  00000000 __umodsi3
4010f000 g       *ABS*  00000000 _text_start
4010f000 g       .text  00000000 _stext
4010f000 l    d  .text  00000000 .text
4010f088 g     F .text  00000067 print_version
4010f0f0 g     F .text  000000ad load_app_from_flash_raw
4010f1a0 g     F .text  00000091 copy_raw
4010f234 g     F .text  000000fa main
4010f330 g     F .text  00000041 crc_update
4010f374 g     F .text  00000052 eboot_command_read
4010f3c8 g     F .text  00000014 eboot_command_clear
4010f3dc l     F .text  0000013f tinf_decode_trees
4010f51c g     F .text  00000265 uzlib_uncompress
4010f784 g     F .text  000000b9 uzlib_uncompress_chksum
4010f840 g     F .text  00000034 uzlib_crc32
4010f874 g     F .text  00000107 uzlib_adler32
4010f97c l     F .text  0000007b tinf_build_tree
4010f9f8 l     F .text  00000041 tinf_read_bits
4010fa3c l     F .text  00000050 tinf_decode_symbol
4010fa8c g     F .text  00000013 uzlib_uncompress_init
4010faa0 g     F .text  000000a0 uzlib_gzip_parse_header
4010fb40 g       *ABS*  00000000 _data_end
4010fb40 g       *ABS*  00000000 _data_start
4010fb40 g       *ABS*  00000000 _rodata_start
4010fb40 g       *ABS*  00000000 _text_end
4010fb40 g       .text  00000000 _etext
4010fb4c l     O .text  00000040 tinf_crc32tab
4010fb8c g       *ABS*  00000000 _bss_table_start
4010fb8c g       *ABS*  00000000 __XT_EXCEPTION_DESCS__
4010fb8c g       *ABS*  00000000 __XT_EXCEPTION_DESCS_END__
4010fb8c g       *ABS*  00000000 __XT_EXCEPTION_TABLE__
4010fb94 g       *ABS*  00000000 _bss_table_end
4010fb94 g       *ABS*  00000000 _rodata_end
4010fb98 g       *ABS*  00000000 _bss_end
4010fb98 g       *ABS*  00000000 _bss_start
4010fb98 g       *ABS*  00000000 _lit4_end
4010fb98 g       *ABS*  00000000 _lit4_start
40240000 g       *ABS*  00000000 _irom0_text_end
40240000 g       *ABS*  00000000 _irom0_text_start
eboot.elf:     file format elf32-little
fffff00f g       *ABS*  00000000 _memmap_cacheattr_unused_mask
fffff11f g       *ABS*  00000000 _memmap_cacheattr_wb_strict
fffff11f g       *ABS*  00000000 _memmap_cacheattr_wt_strict
fffff22f g       *ABS*  00000000 _memmap_cacheattr_bp_strict
SYMBOL TABLE:

````

**Comment by earlephilhower** [comment]
Ah, poop.  The uzlib repo has filenames that can't be created on Windows (the tests dir as ones with ":" in them).  Probably have to rename them to something less painful for Windows...

**Comment by earlephilhower** [comment]
0x6d0 bytes used w/o any checksumming:

````
earle@server:~/Arduino/hardware/esp8266com/esp8266/bootloaders/eboot$ objdump -t ./eboot.elf  | sort -k1
00000000 l    d  .comment       00000000 .comment
00000000 l    d  .debug_abbrev  00000000 .debug_abbrev
00000000 l    d  .debug_aranges 00000000 .debug_aranges
00000000 l    d  .debug_frame   00000000 .debug_frame
00000000 l    d  .debug_info    00000000 .debug_info
00000000 l    d  .debug_line    00000000 .debug_line
00000000 l    d  .debug_loc     00000000 .debug_loc
00000000 l    d  .debug_ranges  00000000 .debug_ranges
00000000 l    d  .debug_str     00000000 .debug_str
00000000 l    df *ABS*  00000000 eboot.c
00000000 l    df *ABS*  00000000 eboot_command.c
00000000 l    df *ABS*  00000000 tinfgzip.c
00000000 l    df *ABS*  00000000 tinflate.c
00000000 l    d  .xtensa.info   00000000 .xtensa.info
00000110 g       *ABS*  00000000 _memmap_cacheattr_wb_base
00000110 g       *ABS*  00000000 _memmap_cacheattr_wt_base
00000220 g       *ABS*  00000000 _memmap_cacheattr_bp_base
22222112 g       *ABS*  00000000 _memmap_cacheattr_wb_allvalid
22222112 g       *ABS*  00000000 _memmap_cacheattr_wt_allvalid
2222211f g       *ABS*  00000000 _memmap_cacheattr_wba_trapnull
2222211f g       *ABS*  00000000 _memmap_cacheattr_wbna_trapnull
2222211f g       *ABS*  00000000 _memmap_cacheattr_wb_trapnull
2222211f g       *ABS*  00000000 _memmap_cacheattr_wt_trapnull
22222222 g       *ABS*  00000000 _memmap_cacheattr_bp_allvalid
2222222f g       *ABS*  00000000 _memmap_cacheattr_bp_trapnull
3ff00000 g       *ABS*  00000000 _dport0_data_end
3ff00000 g       *ABS*  00000000 _dport0_data_start
3ff00000 g       *ABS*  00000000 _dport0_literal_end
3ff00000 g       *ABS*  00000000 _dport0_literal_start
3ff00000 g       *ABS*  00000000 _dport0_rodata_end
3ff00000 g       *ABS*  00000000 _dport0_rodata_start
3ffe8000 g       *ABS*  00000000 _heap_start
3ffe8000 l    d  .data  00000000 .data
400024cc g       *ABS*  00000000 ets_printf
40002be8 g       *ABS*  00000000 ets_putc
40002fa0 g       *ABS*  00000000 ets_wdt_enable
400030f0 g       *ABS*  00000000 ets_wdt_disable
40004a00 g       *ABS*  00000000 SPIEraseSector
40004a4c g       *ABS*  00000000 SPIWrite
40004b1c g       *ABS*  00000000 SPIRead
4000dc88 g       *ABS*  00000000 __divsi3
4000e268 g       *ABS*  00000000 __umodsi3
4010f000 g       *ABS*  00000000 _text_start
4010f000 g       .text  00000000 _stext
4010f000 l    d  .text  00000000 .text
4010f068 g     F .text  00000041 print_version
4010f0ac g     F .text  000000ad load_app_from_flash_raw
4010f15c g     F .text  00000272 copy_raw
4010f3d0 g     F .text  000000fe main
4010f4d0 g     F .text  00000038 crc_update
4010f508 g     F .text  00000019 eboot_command_calculate_crc32
4010f524 g     F .text  0000004f eboot_command_read
4010f574 g     F .text  00000014 eboot_command_clear
4010f588 g     F .text  00000036 tinf_get_uint16
4010f5c0 g     F .text  000000b9 uzlib_gzip_parse_header
4010f67c g     F .text  00000013 uzlib_uncompress_init
4010f690 l     F .text  00000013 pgm_read_byte_inlined
4010f6a4 g     F .text  00000011 tinf_skip_bytes
4010f6b5 g       *ABS*  00000000 _text_end
4010f6b5 g       .text  00000000 _etext
4010f6b8 g       *ABS*  00000000 _data_end
4010f6b8 g       *ABS*  00000000 _data_start
4010f6b8 g       *ABS*  00000000 _rodata_start
4010f6c1 g       *ABS*  00000000 __XT_EXCEPTION_DESCS__
4010f6c1 g       *ABS*  00000000 __XT_EXCEPTION_DESCS_END__
4010f6c1 g       *ABS*  00000000 __XT_EXCEPTION_TABLE__
4010f6c4 g       *ABS*  00000000 _bss_table_start
4010f6cc g       *ABS*  00000000 _bss_table_end
4010f6cc g       *ABS*  00000000 _rodata_end
4010f6d0 g       *ABS*  00000000 _bss_end
4010f6d0 g       *ABS*  00000000 _bss_start
4010f6d0 g       *ABS*  00000000 _lit4_end
4010f6d0 g       *ABS*  00000000 _lit4_start
40240000 g       *ABS*  00000000 _irom0_text_end
40240000 g       *ABS*  00000000 _irom0_text_start
./eboot.elf:     file format elf32-little
fffff00f g       *ABS*  00000000 _memmap_cacheattr_unused_mask
fffff11f g       *ABS*  00000000 _memmap_cacheattr_wb_strict
fffff11f g       *ABS*  00000000 _memmap_cacheattr_wt_strict
fffff22f g       *ABS*  00000000 _memmap_cacheattr_bp_strict
SYMBOL TABLE:
````

**Comment by earlephilhower** [comment]
This PR can now automatically decompress GZIP'd .BIN files and run them.  

Prior versions had an incorrectly low code size due to me forgetting to set the "use gzip" flag.  D'oh.

Real memory usage is 0xee0, leaving ~260 bytes free in the 4K sector.

````
objdump -t eboot.elf  | sort -k1


00000000 l    d  .comment	00000000 .comment
00000000 l    d  .debug_abbrev	00000000 .debug_abbrev
00000000 l    d  .debug_aranges	00000000 .debug_aranges
00000000 l    d  .debug_frame	00000000 .debug_frame
00000000 l    d  .debug_info	00000000 .debug_info
00000000 l    d  .debug_line	00000000 .debug_line
00000000 l    d  .debug_loc	00000000 .debug_loc
00000000 l    d  .debug_ranges	00000000 .debug_ranges
00000000 l    d  .debug_str	00000000 .debug_str
00000000 l    df *ABS*	00000000 eboot.c
00000000 l    df *ABS*	00000000 eboot_command.c
00000000 l    df *ABS*	00000000 tinfgzip.c
00000000 l    df *ABS*	00000000 tinflate.c
00000000 l    d  .xtensa.info	00000000 .xtensa.info
00000110 g       *ABS*	00000000 _memmap_cacheattr_wb_base
00000110 g       *ABS*	00000000 _memmap_cacheattr_wt_base
00000220 g       *ABS*	00000000 _memmap_cacheattr_bp_base
22222112 g       *ABS*	00000000 _memmap_cacheattr_wb_allvalid
22222112 g       *ABS*	00000000 _memmap_cacheattr_wt_allvalid
2222211f g       *ABS*	00000000 _memmap_cacheattr_wba_trapnull
2222211f g       *ABS*	00000000 _memmap_cacheattr_wbna_trapnull
2222211f g       *ABS*	00000000 _memmap_cacheattr_wb_trapnull
2222211f g       *ABS*	00000000 _memmap_cacheattr_wt_trapnull
22222222 g       *ABS*	00000000 _memmap_cacheattr_bp_allvalid
2222222f g       *ABS*	00000000 _memmap_cacheattr_bp_trapnull
3ff00000 g       *ABS*	00000000 _dport0_data_end
3ff00000 g       *ABS*	00000000 _dport0_data_start
3ff00000 g       *ABS*	00000000 _dport0_literal_end
3ff00000 g       *ABS*	00000000 _dport0_literal_start
3ff00000 g       *ABS*	00000000 _dport0_rodata_end
3ff00000 g       *ABS*	00000000 _dport0_rodata_start
3ffe8000 g     O .data	00008000 gzip_dict
3ffe8000 l    d  .data	00000000 .data
3fff0000 g     O .data	00001000 uzlib_flash_read_cb_buff
3fff1000 g     O .data	00000004 uzlib_flash_read_cb_addr
3fff1004 g     O .data	0000001e length_bits
3fff1024 g     O .data	00000013 clcidx
3fff1038 g     O .data	0000003c length_base
3fff1074 g     O .data	0000001e dist_bits
3fff1094 g     O .data	0000003c dist_base
3fff10d0 g       *ABS*	00000000 _heap_start
400024cc g       *ABS*	00000000 ets_printf
40002be8 g       *ABS*	00000000 ets_putc
40002fa0 g       *ABS*	00000000 ets_wdt_enable
400030f0 g       *ABS*	00000000 ets_wdt_disable
40004a00 g       *ABS*	00000000 SPIEraseSector
40004a4c g       *ABS*	00000000 SPIWrite
40004b1c g       *ABS*	00000000 SPIRead
4000dc88 g       *ABS*	00000000 __divsi3
4010f000 g       *ABS*	00000000 _text_start
4010f000 g       .text	00000000 _stext
4010f000 l    d  .text	00000000 .text
4010f090 g     F .text	0000003f uzlib_flash_read_cb
4010f0d0 g     F .text	00000041 print_version
4010f114 g     F .text	000000ad load_app_from_flash_raw
4010f1c4 g     F .text	00000312 copy_raw
4010f4d8 g     F .text	000000fe main
4010f5d8 g     F .text	00000041 crc_update
4010f61c g     F .text	00000052 eboot_command_read
4010f670 g     F .text	00000014 eboot_command_clear
4010f684 l     F .text	0000008d tinf_build_bits_base
4010f714 l     F .text	00000033 tinf_getbit
4010f748 l     F .text	00000047 tinf_read_bits
4010f790 l     F .text	0000005e tinf_decode_symbol
4010f7f0 l     F .text	0000013b tinf_decode_trees
4010f92c g     F .text	0000009f uzlib_init
4010f9cc g     F .text	0000033c uzlib_uncompress
4010fd08 g     F .text	0000002c tinf_get_uint16
4010fd34 g     F .text	000000b6 uzlib_gzip_parse_header
4010fdec l     F .text	0000007b tinf_build_tree
4010fe68 g     F .text	00000041 uzlib_get_byte
4010feac g     F .text	0000001a uzlib_uncompress_init
4010fec6 g       *ABS*	00000000 _text_end
4010fec6 g       .text	00000000 _etext
4010fec8 g       *ABS*	00000000 _data_end
4010fec8 g       *ABS*	00000000 _data_start
4010fec8 g       *ABS*	00000000 _rodata_start
4010fed1 g       *ABS*	00000000 __XT_EXCEPTION_DESCS__
4010fed1 g       *ABS*	00000000 __XT_EXCEPTION_DESCS_END__
4010fed1 g       *ABS*	00000000 __XT_EXCEPTION_TABLE__
4010fed4 g       *ABS*	00000000 _bss_table_start
4010fedc g       *ABS*	00000000 _bss_table_end
4010fedc g       *ABS*	00000000 _rodata_end
4010fee0 g       *ABS*	00000000 _bss_end
4010fee0 g       *ABS*	00000000 _bss_start
4010fee0 g       *ABS*	00000000 _lit4_end
4010fee0 g       *ABS*	00000000 _lit4_start
40240000 g       *ABS*	00000000 _irom0_text_end
40240000 g       *ABS*	00000000 _irom0_text_start
eboot.elf:     file format elf32-little
fffff00f g       *ABS*	00000000 _memmap_cacheattr_unused_mask
fffff11f g       *ABS*	00000000 _memmap_cacheattr_wb_strict
fffff11f g       *ABS*	00000000 _memmap_cacheattr_wt_strict
fffff22f g       *ABS*	00000000 _memmap_cacheattr_bp_strict
SYMBOL TABLE:
````

**Comment by earlephilhower** [comment]
Fixes #6614

**Comment by earlephilhower** [comment]
Thanks, @d-a-v.  I tried the httpupdateserver, not the httpupdate path and I'll be sure to include your patch in the next push.

**Comment by TD-er** [comment]
Just curious, how should the bin be compressed in order to be uncompressed with this bootloader?
Any specific gzip flags needed?

**Comment by earlephilhower** [comment]
It should be able to parse any valid gzip file.  I just use `gzip sketch.elf.bin`and upload the `sketch.elf.bin.gz` file.  `-9` might make sense since every byte counts and images are <16MB by definition.

**Comment by csgregg** [comment]
Are there any working examples of compressed for file system update (LittleFS) OTA using ESP8266httpUpdate? I can't seem to find any. 
I can successfully OTA update a compressed program image but it fails with a compressed file system image.

**Pull request merged**
