### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by fabianoms**
FLASH_SECTOR_SIZE defined in terms of SPI_FLASH_SEC_SIZE (issue #2421).

### CODE REVIEW

**Comment by devyte** [comment]
@fabianoms Thanks, but looks like something is still missing, because CI didn't build. Can you figure it out?

**Comment by fabianoms** [comment]
@devyte just one check failing now. Looks like the host tests don't reference files from "tools/sdk/include/".  I'm not sure if I forgot to add something in flash_utils.h or I have to edit the "Arduino/tests/host" to add some reference to sdk files.

**Comment by devyte** [comment]
@fabianoms I was just looking at the same. Honestly, I'm not sure what's the best way to go here.
@igrr would it be correct to copy c_types.h from the sdk include dir into the host/common dir, and edit as necessary, similar to how it's done with Arduino.h?

**Comment by igrr** [comment]
TBH, i would much rather not pull the stuff defined in c_types.h into the global namespace. Easiest is probably replace all `uint32` with `uint32_t` in spi_flash.h. But then, spi_flash.h also declares a bunch of functions. Do we need them there, just for the flash sector size definition? I'm not sure.

**Comment by devyte** [comment]
Closing in favor of #5327 .

**Pull request closed without merging**
