### PR TITLE
Puyafix

### PR DESCRIPTION
**Pull request by d-a-v**
`PUYA_SUPPORT` was not correctly enabled by default.

It was originally defined to 0 by default in `Esp.h` and later to 1 in `Arduino.h` (!).
Its definition is now only in `Esp.cpp`.

@TD-er should the definition of `PUYA_SUPPORT` be visible if it is not user-defined ?

### CODE REVIEW

**Comment by TD-er** [comment]
I do use it to create a descriptive string for the core libraries and give some warning if support is not enabled and a puya device is found.
So it would be a nice to have if it is "publicly" visible.
But you already have it wrapped in #ifndef statements, so I can define it in the platformio.ini file and thus still have it publicly available.
Only thing is, if someone has made a build of its own it may not show the errors.

Maybe you could add a public function for "non supported flash found" ?

**Comment by d-a-v** [comment]
> Maybe you could add a public function for "non supported flash found" ?

Could you please elaborate ?

**Comment by TD-er** [comment]
Well, in the CPP file you now have the define for PUYA support.
So that's not "public", which is fine.
But to be able to check whether or not PUYA support is enabled, it could check for the existence of a puya chip and whether it has PUYA support enabled.
Maybe later there will be other patches for other non standard flash chips, so I thought it would be a bad idea to have this check function named after "puya", so maybe a more generic function name to check whether we may expect issues with the current firmware.

`bool nonSupportedFlashChipFound();`
Or something like that.

**Comment by d-a-v** [comment]
it would be interesting to have a flash config/state bitfield-like API.
With #6559 we would be able to know whether the chip is
- unsupported (like puya, reporting when fix os not enabled)
- underclocked (can run faster, like XMC, reporting when not enabled)

**Comment by TD-er** [comment]
That would be great indeed.
Such information can really help in narrowing down the cause of reported issues.
What is left then is to do the correct interpretation of those bits :)   (e.g., is underclocked more stable? I would expect it to be)

**Pull request merged**
