### PR TITLE
Fix compiler warning about lambda capture initializers

### LINKED ISSUE #6253: LeaMDNS lambda capture initializer C++ standard warnings
We build the core with `--std=c++11`, but the following warning about using something only available under C++14 or later comes up with `-wextra`.

@LaborEtArs, can you please take a quick look at these and see if we're good or if the compiler is silently ignoring your initializer?

````
C++ ../../libraries/ESP8266WiFi/src/ESP8266WiFiSTA-WPS.cpp.32.o
../../libraries/ESP8266mDNS/src/LEAmDNS.cpp: In member function ‘bool esp8266::MDNSImplementation::MDNSResponder::setHostProbeResultCallback(esp8266::MDNSImplementation::MDNSResponder::MDNSHostProbeFn1)’:
../../libraries/ESP8266mDNS/src/LEAmDNS.cpp:1054:40: warning: lambda capture initializers only available with -std=c++14 or -std=gnu++14
     return setHostProbeResultCallback([resp=std::ref(*this), pfn](const char* p_pcDomainName, bool p_bProbeResult) { pfn(resp, p_pcDomainName, p_bProbeResult); });
                                        ^~~~
../../libraries/ESP8266mDNS/src/LEAmDNS.cpp: In member function ‘bool esp8266::MDNSImplementation::MDNSResponder::setServiceProbeResultCallback(esp8266::MDNSImplementation::MDNSResponder::hMDNSService, esp8266::MDNSImplementation::MDNSResponder::MDNSServiceProbeFn1)’:
../../libraries/ESP8266mDNS/src/LEAmDNS.cpp:1083:55: warning: lambda capture initializers only available with -std=c++14 or -std=gnu++14
     return setServiceProbeResultCallback(p_hService, [resp=std::ref(*this), p_fnCallback](const char* p_pcServiceName, const hMDNSService p_hMDNSService, bool p_bProbeResult) {
                                                       ^~~~

````

### PR DESCRIPTION
**Pull request by dok-net**
Fixes #6253

### CODE REVIEW

**Comment by devyte** [comment]
This looks good to me, but needs to be tested.
@hreintke @dok-net or anyone else that can help.

**Comment by hreintke** [comment]
@devyte I will test the solution

**Comment by hreintke** [comment]
@devyte @dok-net 
Quick tested, works OK.

**Comment by devyte** [comment]
@hreintke thanks!

**Pull request merged**
