### PR TITLE
Add 2MB obtion to 8285 generic board

### LINKED ISSUE #7161: Support ESP8285 (2MB flash)
Hello!
I have ESP8285 installed with 2MB flash (new version of chips).
I understand you need to edit the file boards.txt
How to make support for these chips?

### PR DESCRIPTION
**Pull request by earlephilhower**
The ESP8285H16 is reported to have 2MB of flash, so add an option the
the Generic 8285 board for 2MB.

Fixes #7161

### CODE REVIEW

**Comment by Fibrino** [comment]
Hello!
Where can I select this option for the ESP8285 generic board with 2MB of flash?

**Comment by d-a-v** [comment]
85-2m

**Comment by Fibrino** [comment]
I use Visual Studio Code + PlatformIO.
Isn't this view available with this configuration? I was getting crazy!

**Comment by d-a-v** [comment]
I showed you the Arduino IDE.
I'm afraid I don't know about @platformio.
They will hopefully answer (@ivankravets @valeros).

**Comment by valeros** [comment]
@Fibrino Take a look at this page https://docs.platformio.org/en/latest/platforms/espressif8266.html#flash-size

In a nutshell, you need to specify the correct linker script in your `platformio.ini`:
```
board_build.ldscript = eagle.flash.2m64.ld
```

**Comment by Fibrino** [comment]
So I was looking in the right place.
I was hoping there was a menu to select the desired option (as for Arduino) rather than entering it manually.
Thanks so much!

**Pull request merged**
