### PR TITLE
defined SDA and SCL pins for Olimex MOD-WIFI-ESP8266(-DEV)

### PR DESCRIPTION
**Pull request by mabi**
Changed from generic I2C SDA and SCL pin mapping to specific mapping for board modwifi, Olimex MOD-WIFI-ESP8266(-DEV)

### CODE REVIEW

**Comment by devyte** [comment]
@mabi boards.txt is generated by a tool, you need to modify the tool instead.

**Comment by mabi** [comment]
@devyte thank you for the explanation, I will fix shortly

**Comment by mabi** [comment]
@devyte I will shortly squash the commits in one

**Comment by d-a-v** [comment]
@mabi 
You need to regenerate boards.txt with the script and re-add/commit it.
CI also generates it and complains when result differs (yes this is minor diff :)

**Comment by mabi** [comment]
@d-a-v thank you very much, I didn't expect that that line would change place re-running the tool :-)
@devyte is this commit OK for your change request?

**Comment by devyte** [comment]
Yes, but I'll let @d-a-v merge this 😝

**Pull request merged**
