### PR TITLE
added public cleanAPlist() function.

### PR DESCRIPTION
**Pull request by NayanKaran**
cleaning AP list without calling destructor.

### CODE REVIEW

**Comment by bapidebabrata** [comment]
@igrr can you please help me to commit this?

**Comment by devyte** [comment]
@bapidebabrata I can help with this, I need to look at wifimulti again anyways as part of another issue, and I'm familiar with the code.
It might take me a couple of days to get to it, though, I'm currently looking at something else.

**Comment by earlephilhower** [comment]
This conflicts and looks like it's missing bits to actually do anything.  Closing.

**Comment by devyte** [comment]
This just exposes a private method, which allows clearing the content. I wanted to remove the public methods and make the private ones public +rename, but it's not really necessary.

**Comment by earlephilhower** [comment]
Closing as #4107 is identical and doesn't have the linefeed changes.

**Pull request closed without merging**
