### PR TITLE
replace old Ethernet Arduino-library with v2, submoduled

### LINKED ISSUE #2671: Basic example for modified ethernet.h
Hi !

Is possible give us a working basic example for this modified ethernet.h library?
The default examples available here doesn't work without changes.
https://github.com/esp8266/Arduino/tree/master/libraries/Ethernet/examples
Best regards.

### LINKED ISSUE #3943: Please add support WizNet W5500 for Ethernet lib.

### PR DESCRIPTION
**Pull request by d-a-v**
supports W5500, W5200 and W5100

*edit*:
closes #2671 
fixes #3943

### CODE REVIEW

**Comment by devyte** [comment]
Fixes #3943

**Comment by d-a-v** [comment]
@Misiu 
@mynameisbill2

Have you had success with this updated ethernet driver ?

**Comment by Misiu** [comment]
@d-a-v sadly I didn't have a chance to try this out. I'm still waiting for boards. It's my third order, previous didn't arrived. Hopefully this one will.

**Comment by mynameisbill2** [comment]
@d-a-v I have tested the [d-a-v:arduinoethernet](https://github.com/d-a-v/Arduino/tree/arduinoethernet), it's OK, but the [esp8266:master](https://github.com/esp8266/Arduino)'s code haven't been replaced. I don't familiar whith the Github, which time the [d-a-v:arduinoethernet](https://github.com/d-a-v/Arduino/tree/arduinoethernet) barnch can be mereged into the  [esp8266:master](https://github.com/esp8266/Arduino)? I hope it more quickly!

**Comment by d-a-v** [comment]
@mynameisbill2 
Thanks for the report !
You can also try with #6680 which proposes more integrated drivers that will allow you to use any network library available with WiFi but with your ethernet adapter (mqtt/webserver/webclient/any other).
Both will be merged soon (or at least #6680) after release 2.7.0 of this core is out.

Also, [alpha version 0.0.2](https://d-a-v.github.io) already contains this (#6812) pull request.

**Pull request merged**
