### PR TITLE
esp8285: properly initialize available gpio as inputs

### PR DESCRIPTION
**Pull request by d-a-v**
per https://github.com/esp8266/Arduino/issues/7041#issuecomment-602249112 following #7044 @dok-net

### CODE REVIEW

**Comment by d-a-v** [comment]
@ivankravets @valeros Something has gone [wrong](https://travis-ci.org/github/esp8266/Arduino/jobs/667015382#L241) with CI on platformio:
```
fatal: Remote branch feature/stage not found in upstream origin

Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', '--branch', 'feature/stage', 'https://github.com/platformio/platform-espressif8266.git', '/home/travis/.platformio/platforms/_tmp_installing-bew4mnvj-package']
```

Please tell us (or @ivankravets can fix it) which branch we should run CI against, thanks !

**Comment by ivankravets** [comment]
Sorry for the issue, we removed legacy `stage` branch due to a new way how developers can switch to dev-version of this repository. See https://docs.platformio.org/en/latest/platforms/espressif8266.html#using-arduino-framework-with-staging-version

@valeros will provide PR soon.

**Comment by ivankravets** [comment]
Resolved in https://github.com/esp8266/Arduino/pull/7170

**Comment by d-a-v** [comment]
Thanks !

**Pull request merged**
