### PR TITLE
FunctionalScheduledTicker

### PR DESCRIPTION
**Pull request by hreintke**
Implementation of functional callbacks to Ticker library
Adding option to schedule Ticker callback

### CODE REVIEW

**Comment by hreintke** [comment]
New PR identical to #4209

**Comment by devyte** [comment]
@hreintke this doesn't look the same as #4209 . In fact, to my eye it looks like an earlier more primitive version, e.g.: _timer(nullptr) => _timer(0), no typedef std::function<void(void)> TickerFunction, etc.
Did something regress, or is this on purpose?

**Comment by hreintke** [comment]
@devyte 
It is the correct version for the scheduled and functional implementation,
Will check the details but the TickerFunction was from an earlier version which is updated to callback_function_t on request of igrr to make it compliant for naming conventions.

But : I missed the PR which added the Ticker::active() function (and also updated _timer(0) -> _timer(nullptr)0.  Was already long time ago for the initial PR.

I will rebase to get this updated or make another PR. 
Sorry for the inconvenience,

**Comment by devyte** [comment]
No worries, as long as we're moving forward to getting this merged :)

**Comment by hreintke** [comment]
Replaced by #5030

**Pull request closed without merging**
