### PR TITLE
Python 3 fixes

### PR DESCRIPTION
**Pull request by scop**
Probably not quite enough to get the code running with Python 3, but it's a start and doesn't hurt with Python 2.

### CODE REVIEW

**Comment by igrr** [comment]
Don't you need to add `from __future__ import print_function` to be compatible with Python 2?

**Comment by scop** [comment]
On Sun, Oct 15, 2017 at 10:08 AM, Ivan Grokhotkov
<notifications@github.com> wrote:
>
> Don't you need to add from __future__ import print_function to be compatible with Python 2?

Not in simple cases like these.

**Comment by devyte** [comment]
@scop @igrr Is this PR still valid? Is anything pending?

**Comment by scop** [comment]
Still valid, yes, nothing pending from me. Just rebased against current master.

**Comment by scop** [comment]
I think the CI failures are unrelated to these changes.

**Pull request merged**
