### PR TITLE
Added support for 40MHz crystal frequency

### PR DESCRIPTION
**Pull request by jeremypoulter**
This is needed for some ESP8266 modules that, for example the module in [this](http://www.banggood.com/Smart-Home-WiFi-Socket-Switch-UK-Plug-Wireless-Timer-Remote-Control-p-1022471.html?p=7U30132019453201507N) SmartPlug, that have a 40Mhz crystal rather than the 'normal' 26MHz.

### CODE REVIEW

**Comment by torntrousers** [comment]
Hi Jeremy, that SmartPlug looks interesting but I can't find much on it, do you have any links to more about it - photos of inside or info about re-programing it etc?

**Comment by jeremypoulter** [comment]
Some info on the module can be found here; https://detail.1688.com/offer/45107082796.html and there is some discussion on it in this forum; https://www.letscontrolit.com/forum/viewtopic.php?t=2159 however I am still working on the full documentation of my efforts with this plug.

**Comment by gvJaime** [comment]
I've had issues #3004 and #3094 with the Arduino UNO WiFi, because of this little 40MHz crystal detail.

It would be great that this pull request gets merged because right now I have to modify the framework by hand to make it work. It would be easier with this simple flag.

**Comment by jeremypoulter** [comment]
Somewhat frustratingly this change was added (not quite as cleanly IMHO) by #3121 so closing this

**Pull request closed without merging**
