### PR TITLE
Fix for #3408 

### PR DESCRIPTION
**Pull request by torntrousers**
As per https://github.com/esp8266/Arduino/issues/3408#issuecomment-413661491 undo the change in https://github.com/esp8266/Arduino/commit/e02932fcddc24740852ec0e39e494e57a8906df2. I've tried the sketch in #619 that the commit was original done to fix and it does work now without the commit.

### CODE REVIEW

**Comment by devyte** [comment]
Merging this after confirmation from several users.

**Comment by torntrousers** [comment]
Not that this change appears to have broken RF_CAL, see the on going discussion in https://github.com/esp8266/Arduino/issues/3408#issuecomment-414159385

**Comment by devyte** [comment]
@torntrousers should this be rolled back, new changes added on top, or is further investigation needed to figure out the problem/solution?

**Comment by torntrousers** [comment]
Its really unclear what RF calibration does, for me it appears to work ok without calibration running, and there's the work around of using an RF_PRE_INIT function to force calibration to run - https://github.com/esp8266/Arduino/issues/3408#issuecomment-414477566. And without this change here its impossible to get the fast startup times which make running off small batteries practical. SO IMHO I'd prefer this fix to stay on, at least for now.

**Pull request merged**
