### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by caffeinator13**
I've received many errors while doing `python get.py` until I realised I needed `python3` after looking at the code. Please merge the PR to make it easy for others. Thanks.

### CODE REVIEW

**Comment by igrr** [comment]
Actually it should work with python2 as well. Could you describe the errors you got?

**Comment by caffeinator13** [comment]
This came up when I tried with python2 
 `Downloading esptool-0.4.12-linux64.tar.gz
Traceback (most recent call last):
  File "get.py", line 126, in <module>
    get_tool(tool)
  File "get.py", line 85, in get_tool
    urlretrieve(url, local_path, report_progress)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 271, in retrieve
    reporthook(blocknum, bs, size)
  File "get.py", line 51, in report_progress
    percent = int(count*blockSize*100/totalSize)
ZeroDivisionError: integer division or modulo by zero
`

**Comment by devyte** [comment]
@caffeinator13 @igrr What is the status of this? Is a fix needed, or is it a platform config issue (i.e.. path/symlink to the python interpreter)?

**Comment by earlephilhower** [comment]
Closing this due to lack of feedback and having nothing but Python 2.7 on my systems and not noticing any issues.  From the error, looks like there was a network/server hiccup at one point and the total size to download came back as 0.

**Pull request closed without merging**
