### PR TITLE
lwip2: lighter implementation

### PR DESCRIPTION
**Pull request by d-a-v**
This PR is replaced by #3783 
---------------

full sources are separate and available as a submodule
included in this PR: include/ and liblwip2.a + Makefile for pull&rebuild

I guess this is the way @igrr imports his cloned axtls, so arduino/esp8266 is lighter.

aside from this lwip2 implementation gets more genericity for other esp8266 projects.

### CODE REVIEW

**Comment by devyte** [comment]
@igrr are we waiting until after the next release to merge this, or do we want it in the next release?

**Comment by igrr** [comment]
Yes, we're waiting until after the next release.

**Comment by igrr** [comment]
@d-a-v  FYI the latest SDK has changed the type of err_t from int8_t to int32_t (or rather, to `signed long`). I think lwip2 headers should be in sync.
(Sorry if you have done this already, i was't able to load all the diffs in this PR).

**Comment by d-a-v** [comment]
I did not notice, thanks. I will sync lwip2 according to this new err_t.

**Comment by d-a-v** [comment]
Is there another way of getting the SDK version apart from reading ```tools/sdk/version``` file ?

**Comment by devyte** [comment]
@d-a-v I created a project to track what is relevant for lwip2. So far we've been sort of testing sketches and issues on an ad-hoc basis, but eventually we'll want to have a full collection of what gets fixed.
Please feel free to use.

**Comment by d-a-v** [comment]
Thanks (however I can't seem to be able to write anything in it).
The first Todo would be to improve heap usage as per #3733: lwip2 seems to have solved stability but eats too much ram.
I'll try to work on that asap. As a start it could be a comparison of old and new lwipopts.h, also @earlephilhower's suggestion about dns table's size and all info/help from #3740.

**Comment by devyte** [comment]
@igrr could we get @d-a-v access to the projects?

**Comment by d-a-v** [comment]
ram + flash footprint is now better than with lwip1.4.
Below the footprint variation with one of my sketches. the two last colums shows the latest commits benefits.
mainly: I had forgotten to disable lwip internal asserts :-/
```
                1.4             v2              -assert         optsync+dns
sketch          373912          380616          367684          367236
sketch%         74              76              73              73
ram             40396           47940           40932           40020
ram%            49              58              49              48
heap            33240           25360           32872           33280
```

**Comment by d-a-v** [comment]
@igrr @devyte @davisonja At this point, and
- because people are beginning to be aware that lwip2 can solve some old issues and some of them already use it,
- because this PR cannot not be merged as-is (gitk shows real tube map due to repaired mistakes and also to my inability to stay clean in the long run with git and the multiple branches I'm dealing with - I lost liblwip2.a the other day, and I regularly lose myself in suddenly appearing head-detached branch  :),
- because this PR is really small (it's one makefile, one line in the main ldscript, the include directory+lib which are however auto-generated, and a submodule ref),
- because memory footprint seems equivalent to lwip1.4's,
- because lwip2 needs more serious testing
- because I don't want to and will not advertise my own repo

What do you think if
- I include in here the regenerated boards.txt from #3722 so it is tested too (and has lwip2+debug for all known boards)
- lwip2 is advertised in issues where relevant with an easy step-by-step setup doc
- and of course I keep up syncing with master so testers can always have master+lwip2

**Comment by igrr** [comment]
That sounds very good to me @d-a-v. Let's add it to master to make things
easier in terms of testing and updates.

**Comment by d-a-v** [comment]
To master, I was not asking for that much :) Did I understand well ?
The boards.txt issue must be solved first so lwip2 can be available in menus, but still along with the former one that we must have around. @davisonja what about #3722 and ldscripts ?
Or should we provide a generated boards.txt at first ?
Or simply keep the modified master's boards.txt from this PR ?

**Comment by davisonja** [comment]
Because the ldscripts need to match I would vote to include a generated boards.txt, though in practice since it should look the same as the modified version in this pr its probably just as simple to leave the current one. I've got some queries about the current script, but been tied up with new child, hopefully can post them tonight 😊

**Comment by devyte** [comment]
@d-a-v if this PR is superseded, should it be closed?
Similar question for PR #3206

**Comment by d-a-v** [comment]
closing in favour of #3783

**Comment by igrr** [comment]
@d-a-v  I did mean master. Since lwip v2 is optional, it shouldn't be any harm, and hopefully will help folks who run into lwip related issues.

**Pull request closed without merging**
