### PR TITLE
Add TestEspApi example, exercising the non-RTOS C API.

### PR DESCRIPTION
**Pull request by nuket**
Wrote a little code to exercise the C API, using the CallSDKFunctions example as a starting point. It doesn't exercise every last function, but is helpful for learning how the C API works.

### CODE REVIEW

**Comment by ibaranov-cp** [comment]
This looks really good to me!

**Comment by nuket** [comment]
Thanks! 

Curiosity: Is the latest 1.5.1 non-RTOS SDK planned to be merged into the codebase? I noticed some new forced-sleep API calls that might be interesting to use. Wondering if I could help out in porting this stuff.

It also seems like the PlatformIO guys are still using the esp8266/Arduino with the 1.3.0 version of the SDK? (off-topic, I know).

**Comment by igrr** [comment]
- We are actually using 1.5.1 at this time (see https://github.com/esp8266/Arduino/blob/master/tools/sdk/version)
- PlatformIO has been updated to use the latest 2.1.0 release yesterday (https://twitter.com/PlatformIO_Org/status/704304862998224896)

**Comment by krzychb** [comment]
@nuket 

This part of code is my favourite :smile:
```
Serial.begin(74880); 
system_update_cpu_freq(SYS_CPU_160MHZ); 
```

Nice example :+1:

Krzysztof

**Pull request merged**
